### ISSUE TITLE
Simulation Error: 502 Bad Gateway 

### ISSUE THREAD

**Issue by osama989** [radiasoft/sirepo#1023]
When running this simulation 
https://uspas-sirepo.radiasoft.org/elegant#/source/CSQ0ivrc

I got the following error

Simulation Error: 502 Bad Gateway

**Comment by robnagler** [comment]
```text
Jan 17 20:38:42   212 20747 /home/vagrant/.pyenv/versions/2.7.12/envs/py2/lib/python2.7/site-packages/sirepo-20180112.181239-py2.7.egg/sirepo/uri_router.py:17
4:_dispatch run-simulation: error: Exception: no value for field "name" and no default value in schema
  File "/home/vagrant/.pyenv/versions/2.7.12/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vagrant/.pyenv/versions/2.7.12/envs/py2/lib/python2.7/site-packages/beaker/middleware.py", line 156, in __call__
    return self.wrap_app(environ, session_start_response)
  File "/home/vagrant/.pyenv/versions/2.7.12/envs/py2/lib/python2.7/site-packages/sirepo-20180112.181239-py2.7.egg/sirepo/server.py", line 783, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vagrant/.pyenv/versions/2.7.12/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vagrant/.pyenv/versions/2.7.12/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vagrant/.pyenv/versions/2.7.12/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vagrant/.pyenv/versions/2.7.12/envs/py2/lib/python2.7/site-packages/sirepo-20180112.181239-py2.7.egg/sirepo/uri_router.py", line 168, in _dispat
ch
    return route.func(**kwargs)
  File "/home/vagrant/.pyenv/versions/2.7.12/envs/py2/lib/python2.7/site-packages/sirepo-20180112.181239-py2.7.egg/sirepo/server.py", line 484, in api_runSimu
lation
    _start_simulation(data)
  File "/home/vagrant/.pyenv/versions/2.7.12/envs/py2/lib/python2.7/site-packages/sirepo-20180112.181239-py2.7.egg/sirepo/server.py", line 1092, in _start_sim
ulation
    cfg.job_queue(data)
  File "/home/vagrant/.pyenv/versions/2.7.12/envs/py2/lib/python2.7/site-packages/sirepo-20180112.181239-py2.7.egg/sirepo/runner.py", line 208, in __init__
    self.cmd, self.run_dir = simulation_db.prepare_simulation(data)
  File "/home/vagrant/.pyenv/versions/2.7.12/envs/py2/lib/python2.7/site-packages/sirepo-20180112.181239-py2.7.egg/sirepo/simulation_db.py", line 517, in prep
are_simulation
    is_parallel=is_p,
  File "/home/vagrant/.pyenv/versions/2.7.12/envs/py2/lib/python2.7/site-packages/sirepo-20180112.181239-py2.7.egg/sirepo/template/elegant.py", line 528, in w
rite_parameters
    is_parallel,
  File "/home/vagrant/.pyenv/versions/2.7.12/envs/py2/lib/python2.7/site-packages/sirepo-20180112.181239-py2.7.egg/sirepo/template/elegant.py", line 229, in g
enerate_parameters_file
    _validate_data(data, _SCHEMA)
  File "/home/vagrant/.pyenv/versions/2.7.12/envs/py2/lib/python2.7/site-packages/sirepo-20180112.181239-py2.7.egg/sirepo/template/elegant.py", line 1152, in
_validate_data
    enum_info = template_common.validate_models(data, schema)
  File "/home/vagrant/.pyenv/versions/2.7.12/envs/py2/lib/python2.7/site-packages/sirepo-20180112.181239-py2.7.egg/sirepo/template/template_common.py", line 2
50, in validate_models
    validate_model(model_data['models'][k], model_schema['model'][k], enum_info)
  File "/home/vagrant/.pyenv/versions/2.7.12/envs/py2/lib/python2.7/site-packages/sirepo-20180112.181239-py2.7.egg/sirepo/template/template_common.py", line 2
15, in validate_model
    raise Exception('no value for field "{}" and no default value in schema'.format(k))
Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/2.7.12/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vagrant/.pyenv/versions/2.7.12/envs/py2/lib/python2.7/site-packages/beaker/middleware.py", line 156, in __call__
    return self.wrap_app(environ, session_start_response)
  File "/home/vagrant/.pyenv/versions/2.7.12/envs/py2/lib/python2.7/site-packages/sirepo-20180112.181239-py2.7.egg/sirepo/server.py", line 783, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vagrant/.pyenv/versions/2.7.12/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/vagrant/.pyenv/versions/2.7.12/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/.pyenv/versions/2.7.12/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vagrant/.pyenv/versions/2.7.12/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vagrant/.pyenv/versions/2.7.12/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/.pyenv/versions/2.7.12/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vagrant/.pyenv/versions/2.7.12/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vagrant/.pyenv/versions/2.7.12/envs/py2/lib/python2.7/site-packages/sirepo-20180112.181239-py2.7.egg/sirepo/uri_router.py", line 168, in _dispat
ch
    return route.func(**kwargs)
  File "/home/vagrant/.pyenv/versions/2.7.12/envs/py2/lib/python2.7/site-packages/sirepo-20180112.181239-py2.7.egg/sirepo/server.py", line 484, in api_runSimulation
    _start_simulation(data)
  File "/home/vagrant/.pyenv/versions/2.7.12/envs/py2/lib/python2.7/site-packages/sirepo-20180112.181239-py2.7.egg/sirepo/server.py", line 1092, in _start_simulation
    cfg.job_queue(data)
  File "/home/vagrant/.pyenv/versions/2.7.12/envs/py2/lib/python2.7/site-packages/sirepo-20180112.181239-py2.7.egg/sirepo/runner.py", line 208, in __init__
    self.cmd, self.run_dir = simulation_db.prepare_simulation(data)
  File "/home/vagrant/.pyenv/versions/2.7.12/envs/py2/lib/python2.7/site-packages/sirepo-20180112.181239-py2.7.egg/sirepo/simulation_db.py", line 517, in prepare_simulation
    is_parallel=is_p,
  File "/home/vagrant/.pyenv/versions/2.7.12/envs/py2/lib/python2.7/site-packages/sirepo-20180112.181239-py2.7.egg/sirepo/template/elegant.py", line 528, in write_parameters
    is_parallel,
  File "/home/vagrant/.pyenv/versions/2.7.12/envs/py2/lib/python2.7/site-packages/sirepo-20180112.181239-py2.7.egg/sirepo/template/elegant.py", line 229, in generate_parameters_file
    _validate_data(data, _SCHEMA)
  File "/home/vagrant/.pyenv/versions/2.7.12/envs/py2/lib/python2.7/site-packages/sirepo-20180112.181239-py2.7.egg/sirepo/template/elegant.py", line 1152, in _validate_data
    enum_info = template_common.validate_models(data, schema)
  File "/home/vagrant/.pyenv/versions/2.7.12/envs/py2/lib/python2.7/site-packages/sirepo-20180112.181239-py2.7.egg/sirepo/template/template_common.py", line 250, in validate_models
    validate_model(model_data['models'][k], model_schema['model'][k], enum_info)
  File "/home/vagrant/.pyenv/versions/2.7.12/envs/py2/lib/python2.7/site-packages/sirepo-20180112.181239-py2.7.egg/sirepo/template/template_common.py", line 215, in validate_model
    raise Exception('no value for field "{}" and no default value in schema'.format(k))
Exception: no value for field "name" and no default value in schema
```

**Comment by moellep** [comment]
I've seen this before. The simulation.name field is getting cleared by the safePath component firing at the wrong time. Then when autosave is activated, the save fails on the server. Reworking the cancelChanges call in safePath should fix the problem.
