### ISSUE TITLE
build errors on CentOS but travis is fine

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#1077]
[Travis passed](https://travis-ci.org/radiasoft/sirepo/builds/342156749), but I'm getting these errors on fnl1:
```text
_____________________________ test_processed_image _____________________________
[snip]
  File "/rscontainers/sirepo/sirepo/template/__init__.py", line 25, in import_module
    return importlib.import_module('.' + assert_sim_type(type_or_data), __name__)
  File "/home/vagrant/.pyenv/versions/2.7.14/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/rscontainers/sirepo/sirepo/template/rs4pi.py", line 18, in <module>
    import dicom
ImportError: No module named dicom
[snip]
_______________________________ test_create_zip ________________________________
Traceback (most recent call last):
  File "/rscontainers/sirepo/tests/exporter_test.py", line 22, in test_create_zip
    imported = _import(fc)
  File "/rscontainers/sirepo/tests/exporter_test.py", line 67, in _import
    res.append((d.simulationType, d.models.simulation.name, expect))
  File "/home/vagrant/.pyenv/versions/py2/lib/python2.7/site-packages/pykern-20180120.32202-py2.7.egg/pykern/pkcollections.py", line 56, in __getattr__
    return self.__getattribute__(name)
AttributeError: 'Dict' object has no attribute 'simulationType'
```

**Comment by robnagler** [comment]
pydicom went to 1.0.0, which involved a rename, which broke everything. Thanks @moellep
