### ISSUE TITLE
importer_test failing for chx.py because mirror file not there

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#110]
```text
pytest importer_test.py
================================= test session starts =================================
platform linux2 -- Python 2.7.10, pytest-2.9.0, py-1.4.30, pluggy-0.3.1
rootdir: /home/vagrant/src/radiasoft/sirepo, inifile:
plugins: xdist-1.13.1
collected 1 items

importer_test.py F

====================================== FAILURES =======================================
_________________________________ test_sirepo_parser __________________________________

    def test_sirepo_parser():
        with pkunit.save_chdir_work():
            for b in ['SRWLIB_VirtBL_LCLS_SXR_01', 'chx']:
                base_py = '{}.py'.format(b)
                code = pkio.read_text(pkunit.data_dir().join(base_py))
                error, actual = import_python(
                    code,
                    tmp_dir='.',
                    lib_dir='.',
                    user_filename=r'c:\x\{}.y'.format('SRWLIB_VirtBL_LCLS_SXR_01'),
                )
>               assert not error, \
                    '{}: should import with an error: {}'.format(base_py, error)
E               AssertionError: chx.py: should import with an error: Error on line 213: [Errno 2] No such file or directory: '/home/vagran
E               assert not "Error on line 213: [Errno 2] No such file or directory: '/home/vagran"

importer_test.py:27: AssertionError
-------------------------------- Captured stderr call ---------------------------------
../sirepo/importer.py:66:import_python Error: Import failed: error unknown; exception=[Errno 2] No such file or directory: '/home/vagrant/src/radiasoft/sirepo/tests/importer_work/data_CHX/CHX_DCM_height_prof_1d.dat'; script=/home/vagrant/src/radiasoft/sirepo/tests/importer_work/in.py; filename=c:\x\SRWLIB_VirtBL_LCLS_SXR_01.y; stack:
Traceback (most recent call last):
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/importer.py", line 54, in import_python
    user_filename=user_filename,
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/importer.py", line 707, in __init__
    self.optics = getattr(m, 'set_optics')(self.var_param)
  File "/home/vagrant/src/radiasoft/sirepo/tests/importer_work/in.py", line 213, in set_optics
    hProfDataDCME = srwl_uti_read_data_cols(ifnDCME, '\t', 0, 1)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/srwlib.py", line 3505, in srwl_uti_read_data_cols
    f = open(_file_path, 'r')
IOError: [Errno 2] No such file or directory: '/home/vagrant/src/radiasoft/sirepo/tests/importer_work/data_CHX/CHX_DCM_height_prof_1d.dat'

============================== 1 failed in 3.45 seconds ===============================
```

**Comment by robnagler** [comment]
Fixed with 75cea364289ccd992931aeada8b840b985c8db3e
