### ISSUE TITLE
Cannot start sirepo in Python 3.6

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#1161]
It throws an error:
```python
$ sirepo service http
Traceback (most recent call last):
  File "/Users/mrakitin/anaconda3/envs/sirepo_py3.6/bin/sirepo", line 11, in <module>
    load_entry_point('sirepo', 'console_scripts', 'sirepo')()
  File "/Users/mrakitin/src/radiasoft/sirepo/sirepo/sirepo_console.py", line 18, in main
    return pkcli.main('sirepo')
  File "/Users/mrakitin/anaconda3/envs/sirepo_py3.6/lib/python3.6/site-packages/pykern/pkcli/__init__.py", line 98, in main
    argh.dispatch(parser, argv=argv)
  File "/Users/mrakitin/anaconda3/envs/sirepo_py3.6/lib/python3.6/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/Users/mrakitin/anaconda3/envs/sirepo_py3.6/lib/python3.6/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/Users/mrakitin/anaconda3/envs/sirepo_py3.6/lib/python3.6/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "/Users/mrakitin/src/radiasoft/sirepo/sirepo/pkcli/service.py", line 62, in http
    from sirepo import server
  File "/Users/mrakitin/src/radiasoft/sirepo/sirepo/server.py", line 12, in <module>
    from sirepo import runner
  File "/Users/mrakitin/src/radiasoft/sirepo/sirepo/runner.py", line 11, in <module>
    from sirepo import simulation_db
  File "/Users/mrakitin/src/radiasoft/sirepo/sirepo/simulation_db.py", line 15, in <module>
    from sirepo.template import template_common
  File "/Users/mrakitin/src/radiasoft/sirepo/sirepo/template/template_common.py", line 367
    if attrs < 2 << 16L:
                      ^
SyntaxError: invalid syntax
```

It used to work 80 commits before.

**Comment by robnagler** [comment]
We should definitely avoid any Python 2'isms, but we don't intend to test on Python 3. It will not work (easily) as long the codes aren't upgraded. I don't want to have to have development split between two pyenvs.

**Comment by mrakitin** [comment]
More info about the bug: http://www.diveintopython3.net/porting-code-to-python-3-with-2to3.html#long

**Comment by robnagler** [comment]
There has to be a better way to write this code, because there are only 4 bytes and that's an "int" in Python 2 afaik. I think we can remove the "L" and it would be fine.

**Comment by mrakitin** [comment]
Thanks @robnagler! The code in question (for reference):

https://github.com/radiasoft/sirepo/blob/a5c8180f1d5d0c3cdd09427dabd061da76afecd6/sirepo/template/template_common.py#L364-L375
