### ISSUE TITLE
Accessing Sirepo from a docker container fails

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#1395]
I was helping a visitor from Australian Synchrotron to setup Sirepo server on a local system. Sirepo was attempted to start following the instructions at https://github.com/radiasoft/sirepo#manual-install-with-docker. The server starts fine, but when http://localhost:8000 is accessed, the following error is thrown:
```bash
$ docker run --rm -p 8000:8000 -v "$PWD:/sirepo" radiasoft/sirepo
 * Serving Flask app "sirepo.server" (lazy loading)
 * Environment: development
 * Debug mode: off
 * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
172.17.0.1 - - [24/Oct/2018 13:33:39] "GET / HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/sirepo/uri_router.py", line 188, in _dispatch_empty
    return _dispatch(None)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/sirepo/uri_router.py", line 148, in _dispatch
    cookie.init()
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/sirepo/cookie.py", line 68, in init
    _State(unit_test or flask.request.environ.get('HTTP_COOKIE', ''))
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/sirepo/cookie.py", line 136, in __init__
    self._from_cookie_header(header)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/sirepo/cookie.py", line 206, in _from_cookie_header
    import sirepo.beaker_compat
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/sirepo/beaker_compat.py", line 84, in <module>
    secret=(None, _cfg_session_secret, 'Beaker: Used with the HMAC to ensure session integrity'),
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/pykern/pkconfig.py", line 369, in init
    _iter_decls(decls, res)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/pykern/pkconfig.py", line 671, in _iter_decls
    r[kp] = _resolver(d)(k, d)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/pykern/pkconfig.py", line 750, in _resolve_value
    return decl.parser(res)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/sirepo/beaker_compat.py", line 62, in _cfg_session_secret
    assert pkconfig.channel_in('dev'), 'missing session secret configuration'
AssertionError: missing session secret configuration
```
It should be either fixed in the docker image, or correct instructions should be provided.

@robnagler, any ideas?

**Comment by robnagler** [comment]
Tricky. We don't know all the installations so we've required beaker_compat config to help people migrate to the new cookie structure.

Perhaps we should change it now to not support compatibility mode if there's no config.

@moellep @mkeilman thoughts?

**Comment by moellep** [comment]
Yes, I think if there is no config, or other way to determine if the old beaker cookies were not present, then it shouldn't bring in those modules.

**Comment by mrakitin** [comment]
Thanks @robnagler. I tried the new image, and got this error in the very beginning, though the execution proceeded fine:
```
$ docker run --rm -p 8000:8000 -v "$PWD:/sirepo" radiasoft/sirepo
 * Serving Flask app "sirepo.server" (lazy loading)
 * Environment: development
 * Debug mode: off
 * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/sirepo/cookie.py:221:_from_cookie_header Unconfiguring beaker_compat: AssertionError: missing session secret configuration
  File "/home/vagrant/.pyenv/versions/2.7.14/lib/python2.7/threading.py", line 774, in __bootstrap
    self.__bootstrap_inner()
  File "/home/vagrant/.pyenv/versions/2.7.14/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/vagrant/.pyenv/versions/2.7.14/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/vagrant/.pyenv/versions/2.7.14/lib/python2.7/SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "/home/vagrant/.pyenv/versions/2.7.14/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/vagrant/.pyenv/versions/2.7.14/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/werkzeug/serving.py", line 293, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/home/vagrant/.pyenv/versions/2.7.14/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/werkzeug/serving.py", line 328, in handle_one_request
    return self.run_wsgi()
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/sirepo/uri_router.py", line 188, in _dispatch_empty
    return _dispatch(None)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/sirepo/uri_router.py", line 148, in _dispatch
    cookie.init()
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/sirepo/cookie.py", line 70, in init
    _State(unit_test or flask.request.environ.get('HTTP_COOKIE', ''))
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/sirepo/cookie.py", line 138, in __init__
    self._from_cookie_header(header)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/sirepo/cookie.py", line 211, in _from_cookie_header
    import sirepo.beaker_compat
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/sirepo/beaker_compat.py", line 84, in <module>
    secret=(None, _cfg_session_secret, 'Beaker: Used with the HMAC to ensure session integrity'),
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/pykern/pkconfig.py", line 369, in init
    _iter_decls(decls, res)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/pykern/pkconfig.py", line 671, in _iter_decls
    r[kp] = _resolver(d)(k, d)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/pykern/pkconfig.py", line 750, in _resolve_value
    return decl.parser(res)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/sirepo/beaker_compat.py", line 62, in _cfg_session_secret
    assert pkconfig.channel_in('dev'), 'missing session secret configuration'
/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/sirepo/cookie.py:225:_from_cookie_header Cookie decoding failed: <class 'cryptography.fernet.InvalidToken'> value=None
172.17.0.1 - - [05/Nov/2018 16:45:48] "GET / HTTP/1.1" 200 -
172.17.0.1 - - [05/Nov/2018 16:45:48] "GET /static/js/ext/ie10-viewport-bug-workaround.js HTTP/1.1" 200 -
172.17.0.1 - - [05/Nov/2018 16:45:48] "GET /static/css/ext/cookieconsent.min.css?20181031.213307 HTTP/1.1" 200 -
172.17.0.1 - - [05/Nov/2018 16:45:49] "GET /static/css/landing-page.css HTTP/1.1" 200 -
172.17.0.1 - - [05/Nov/2018 16:45:49] "GET /static/css/ext/bootstrap-toggle.min.css?20181031.213307 HTTP/1.1" 200 -
172.17.0.1 - - [05/Nov/2018 16:45:49] "GET /static/css/ext/bootstrap-colxl.css HTTP/1.1" 200 -
172.17.0.1 - - [05/Nov/2018 16:45:49] "GET /static/js/ext/angular-route.min.js HTTP/1.1" 200 -
172.17.0.1 - - [05/Nov/2018 16:45:49] "GET /static/js/ext/angular.min.js HTTP/1.1" 200 -
172.17.0.1 - - [05/Nov/2018 16:45:49] "GET /static/js/ext/jquery-2.2.4.min.js HTTP/1.1" 200 -
172.17.0.1 - - [05/Nov/2018 16:45:49] "GET /static/css/ext/bootstrap-3.3.7.min.css HTTP/1.1" 200 -
172.17.0.1 - - [05/Nov/2018 16:45:49] "GET /static/js/ext/bootstrap-3.3.7.min.js HTTP/1.1" 200 -
172.17.0.1 - - [05/Nov/2018 16:45:49] "GET /static/js/landing-page.js?20181031.213307 HTTP/1.1" 200 -
172.17.0.1 - - [05/Nov/2018 16:45:49] "GET /static/js/sirepo-common.js?20181031.213307 HTTP/1.1" 200 -
172.17.0.1 - - [05/Nov/2018 16:45:49] "GET /static/js/ext/cookieconsent.min.js?20181031.213307 HTTP/1.1" 200 -
172.17.0.1 - - [05/Nov/2018 16:45:49] "GET /static/json/srw-examples.json?20181031.213307 HTTP/1.1" 200 -
172.17.0.1 - - [05/Nov/2018 16:45:49] "GET /static/img/favicon.ico HTTP/1.1" 200 -
172.17.0.1 - - [05/Nov/2018 16:45:50] "GET /static/json/landing-page-schema.json?20181031.213307 HTTP/1.1" 200 -
172.17.0.1 - - [05/Nov/2018 16:45:50] "GET /static/html/landing-page-about.html?20181031.213307 HTTP/1.1" 200 -
172.17.0.1 - - [05/Nov/2018 16:45:50] "GET /static/img/RSLogo.png?20181031.213307 HTTP/1.1" 200 -
172.17.0.1 - - [05/Nov/2018 16:45:50] "GET /static/img/SirepoLogo.png?20181031.213307 HTTP/1.1" 200 -
172.17.0.1 - - [05/Nov/2018 16:45:50] "GET /static/img/background_21.png HTTP/1.1" 200 -
172.17.0.1 - - [05/Nov/2018 16:46:00] "GET /static/html/landing-page-x-ray.html?20181031.213307 HTTP/1.1" 200 -
172.17.0.1 - - [05/Nov/2018 16:46:02] "GET /static/html/landing-page-srw.html?20181031.213307 HTTP/1.1" 200 -
172.17.0.1 - - [05/Nov/2018 16:46:02] "GET /static/img/RGB_White-Seal_White-Mark_SC_Horizontal.png?20181031.213307 HTTP/1.1" 200 -
172.17.0.1 - - [05/Nov/2018 16:46:04] "GET /srw HTTP/1.1" 200 -
```

Also, at some point I got this error:
```
172.17.0.1 - - [05/Nov/2018 17:10:36] "GET /static/js/ext/jquery-2.2.4.min.js?20181031.213307 HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('172.17.0.1', 36946)
----------------------------------------
Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/2.7.14/lib/python2.7/SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "/home/vagrant/.pyenv/versions/2.7.14/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/vagrant/.pyenv/versions/2.7.14/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/home/vagrant/.pyenv/versions/2.7.14/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/home/vagrant/.pyenv/versions/2.7.14/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/home/vagrant/.pyenv/versions/2.7.14/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
172.17.0.1 - - [05/Nov/2018 17:10:36] "GET /static/js/ext/cookieconsent.min.js?20181031.213307 HTTP/1.1" 200 -
```

Are they both expected?

**Comment by mrakitin** [comment]
Oh, just noticed issues with the partially-coherent simulations of the CHX beamline:
```
172.17.0.1 - - [05/Nov/2018 17:14:57] "GET /simulation-frame/srw*nWnNHCDO*multiElectronAnimation*v1_0_linear_grayscale__*4 HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/sirepo/uri_router.py", line 171, in _dispatch
    return _dispatch_call(route.func, kwargs)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/sirepo/uri_router.py", line 181, in _dispatch_call
    resp = flask.make_response(func(**kwargs))
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/sirepo/server.py", line 543, in api_simulationFrame
    frame = template.get_simulation_frame(run_dir, data, model_data)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/sirepo/template/srw.py", line 507, in get_simulation_frame
    return extract_report_data(str(run_dir.join(get_filename_for_model(data['report']))), model_data)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/sirepo/template/srw.py", line 310, in extract_report_data
    info = _remap_3d(info, allrange, file_info[filename][0][3], file_info[filename][1][2], width_pixels, scale)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/sirepo/template/srw.py", line 1762, in _remap_3d
    auxAr = np.array('d', [0] * lenAr2d)
TypeError: data type not understood
```

The result was not displayed properly. The second time I ran it, I wasn't able to reproduce it.

**Comment by mrakitin** [comment]
Actually, it's reproducible:
![image](https://user-images.githubusercontent.com/13209176/48014748-66bbe780-e0f5-11e8-97bb-86bec59a6fab.png)

**Comment by robnagler** [comment]
I'm not seeing this when I try the CHX example (not tabulated). Could you discard changes to example, and try again?

**Comment by mrakitin** [comment]
Yes, I tried to discard the changes before runnin the example.

**Comment by robnagler** [comment]
What do you have for:

```sh
docker inspect radiasoft/sirepo:alpha|grep Id
```

**Comment by mrakitin** [comment]
```
        "Id": "sha256:27c84e648bbb3b74a45998c4b043826d471e5d2702986591b010c71e15b0a69d",
```

**Comment by robnagler** [comment]
That image is six months old. Please run:

```sh
docker pull radiasoft/sirepo:alpha
```

**Comment by mrakitin** [comment]
Oh, but I pulled `radiasoft/sirepo` (which should be `latest`?), and ran against it.

Anyway, I tried the `alpha` channel, and got another error:
```
docker run --rm -p 8000:8000 -v "$PWD:/sirepo" radiasoft/sirepo:alpha
 * Serving Flask app "sirepo.server" (lazy loading)
 * Environment: development
 * Debug mode: off
 * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
172.17.0.1 - - [05/Nov/2018 20:59:14] "GET / HTTP/1.1" 200 -
172.17.0.1 - - [05/Nov/2018 20:59:14] "GET /static/js/ext/ie10-viewport-bug-workaround.js HTTP/1.1" 200 -
172.17.0.1 - - [05/Nov/2018 20:59:14] "GET /static/css/ext/cookieconsent.min.css?20181031.213307 HTTP/1.1" 200 -
172.17.0.1 - - [05/Nov/2018 20:59:14] "GET /static/css/ext/bootstrap-toggle.min.css?20181031.213307 HTTP/1.1" 200 -
172.17.0.1 - - [05/Nov/2018 20:59:14] "GET /static/css/ext/bootstrap-3.3.7.min.css HTTP/1.1" 200 -
172.17.0.1 - - [05/Nov/2018 20:59:14] "GET /static/css/landing-page.css HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/2.7.14/lib/python2.7/SocketServer.py", line 596, in process_request_thread
----------------------------------------
Exception happened during processing of request from ('172.17.0.1', 37976)
    self.finish_request(request, client_address)
  File "/home/vagrant/.pyenv/versions/2.7.14/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/vagrant/.pyenv/versions/2.7.14/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/home/vagrant/.pyenv/versions/2.7.14/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/home/vagrant/.pyenv/versions/2.7.14/lib/python2.7/socket.py", line 283, in close
----------------------------------------
Exception happened during processing of request from ('172.17.0.1', 37978)
Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/2.7.14/lib/python2.7/SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "/home/vagrant/.pyenv/versions/2.7.14/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/vagrant/.pyenv/versions/2.7.14/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/home/vagrant/.pyenv/versions/2.7.14/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/home/vagrant/.pyenv/versions/2.7.14/lib/python2.7/socket.py", line 283, in close
----------------------------------------    self.flush()
  File "/home/vagrant/.pyenv/versions/2.7.14/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe

----------------------------------------
    self.flush()
  File "/home/vagrant/.pyenv/versions/2.7.14/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
```

The issue with plotting the image still exists:
```
172.17.0.1 - - [05/Nov/2018 21:02:46] "GET /simulation-frame/srw*5HActMay*multiElectronAnimation*v1_0_linear_grayscale__*10 HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/sirepo/uri_router.py", line 171, in _dispatch
    return _dispatch_call(route.func, kwargs)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/sirepo/uri_router.py", line 181, in _dispatch_call
    resp = flask.make_response(func(**kwargs))
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/sirepo/server.py", line 543, in api_simulationFrame
    frame = template.get_simulation_frame(run_dir, data, model_data)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/sirepo/template/srw.py", line 507, in get_simulation_frame
    return extract_report_data(str(run_dir.join(get_filename_for_model(data['report']))), model_data)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/sirepo/template/srw.py", line 310, in extract_report_data
    info = _remap_3d(info, allrange, file_info[filename][0][3], file_info[filename][1][2], width_pixels, scale)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/sirepo/template/srw.py", line 1762, in _remap_3d
    auxAr = np.array('d', [0] * lenAr2d)
TypeError: data type not understood
```

**Comment by mrakitin** [comment]
Version information:
```bash
$ docker inspect radiasoft/sirepo:alpha|grep Id
        "Id": "sha256:5ad5f9b600ed401f300e571375bb6fdba6ec3811c844ab996cf409ec9018f9ee",
```

**Comment by robnagler** [comment]
This was a bug in that `template/srw.py`. This probably should have been a separate Issue. I'll close the issue, which was getting sirepo to run at all.

To be clear as to why there was so much back and forth....

When I asked you to run:

```sh
docker run --rm -p 8000:8000 -v "$PWD:/sirepo" radiasoft/sirepo:alpha
```

You ended up running:

```sh
docker run --rm -p 8000:8000 -v "$PWD:/sirepo" radiasoft/sirepo
```

I didn't notice that you ran a different command so I asked for the wrong image Id. That led to the confusion. I understood this only when you asked me about `latest`.

**Comment by mrakitin** [comment]
Thanks, @robnagler, I'm glad it's resolved. I ran the same command which was in my bash history, and which was used in the issue's description (and is the same as in the [README](https://github.com/radiasoft/sirepo#manual-install-with-docker)). Now I have both `latest` and `alpha` of the same version:
```
radiasoft/sirepo                 alpha                       5ad5f9b600ed        4 days ago          5.81GB
radiasoft/sirepo                 latest                      5ad5f9b600ed        4 days ago          5.81GB
```

Agree about a separate issue for the fix https://github.com/radiasoft/sirepo/commit/fa29aea161add77e89905d11a47f40dd508e8dd7, anyway, thanks for the fix!
