### ISSUE TITLE
SRW: corrupt _user_undulator_list.json

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#1454]
Dear colleagues,

This problem was reported today while using our local Docker-based installation of Sirepo at NSLS-II (https://expdev.nsls2.bnl.gov). An IT event occurred on the server causing the lack of free space. Most likely this resulted in a broken file for one of our users. Namely, the file `/sirepo/user/<uid>/srw/lib/_user_undulator_list.json` was empty, which caused all user's simulations to be inaccessible. There were the following exceptions appearing in the Sirepo service log:
```py
/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/sirepo-20180721.1617-py2.7.egg/sirepo/uri_router.py:187:_dispatch simulation/srw/ih9GKiOP/0/source: error: ValueError: No JSON object could be decoded
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/Beaker-1.10.0-py2.7.egg/beaker/middleware.py", line 156, in __call__
    return self.wrap_app(environ, session_start_response)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/sirepo-20180721.1617-py2.7.egg/sirepo/server.py", line 828, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/sirepo-20180721.1617-py2.7.egg/sirepo/uri_router.py", line 181, in _dispatch
    return route.func(**kwargs)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/sirepo-20180721.1617-py2.7.egg/sirepo/server.py", line 562, in api_simulationData
    data = template.prepare_for_client(data)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/sirepo-20180721.1617-py2.7.egg/sirepo/template/srw.py", line 724, in prepare_for_client
    user_model_list = _load_user_model_list(model_name)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/sirepo-20180721.1617-py2.7.egg/sirepo/template/srw.py", line 1755, in _load_user_model_list
    return simulation_db.read_json(filepath)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/sirepo-20180721.1617-py2.7.egg/sirepo/simulation_db.py", line 591, in read_json
    return json_load(f)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/sirepo-20180721.1617-py2.7.egg/sirepo/simulation_db.py", line 401, in json_load
    return pkcollections.json_load_any(*args, **kwargs)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/pykern-20180721.1349-py2.7.egg/pykern/pkcollections.py", line 199, in json_load_any
    return json.loads(o, *args, **kwargs)
  File "/home/vagrant/.pyenv/versions/2.7.14/lib/python2.7/json/__init__.py", line 352, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/home/vagrant/.pyenv/versions/2.7.14/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/vagrant/.pyenv/versions/2.7.14/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/Beaker-1.10.0-py2.7.egg/beaker/middleware.py", line 156, in __call__
    return self.wrap_app(environ, session_start_response)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/sirepo-20180721.1617-py2.7.egg/sirepo/server.py", line 828, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/sirepo-20180721.1617-py2.7.egg/sirepo/uri_router.py", line 181, in _dispatch
    return route.func(**kwargs)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/sirepo-20180721.1617-py2.7.egg/sirepo/server.py", line 562, in api_simulationData
    data = template.prepare_for_client(data)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/sirepo-20180721.1617-py2.7.egg/sirepo/template/srw.py", line 724, in prepare_for_client
    user_model_list = _load_user_model_list(model_name)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/sirepo-20180721.1617-py2.7.egg/sirepo/template/srw.py", line 1755, in _load_user_model_list
    return simulation_db.read_json(filepath)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/sirepo-20180721.1617-py2.7.egg/sirepo/simulation_db.py", line 591, in read_json
    return json_load(f)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/sirepo-20180721.1617-py2.7.egg/sirepo/simulation_db.py", line 401, in json_load
    return pkcollections.json_load_any(*args, **kwargs)
  File "/home/vagrant/.pyenv/versions/2.7.14/envs/py2/lib/python2.7/site-packages/pykern-20180721.1349-py2.7.egg/pykern/pkcollections.py", line 199, in json_load_any
    return json.loads(o, *args, **kwargs)
  File "/home/vagrant/.pyenv/versions/2.7.14/lib/python2.7/json/__init__.py", line 352, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/home/vagrant/.pyenv/versions/2.7.14/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/vagrant/.pyenv/versions/2.7.14/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

The problem was resolved by placing an empty list (`[]`) into the file. Is there any better way to diagnose this kind of problems for all users and resolve it automatically? Thanks.

Observed with @ochubar and @kuchanNo5.

**Comment by moellep** [comment]
I've seen similar behavior before - for example the disk is full, and the sirepo-data.json file gets truncated when a save is attempted, corrupting the simulation. I'm curious if @robnagler has ideas. One solution would be to have the server monitor disk space during requests and abort immediately if space is limited.

**Comment by mrakitin** [comment]
Thanks for the thoughts, @moellep. What about the scenario when the space is reclaimed, and the server can overwrite the broken empty file with a valid default contents?

**Comment by robnagler** [comment]
A few points/questions:

* The docker image is very old (sirepo-20180721.1617). You should update that.
* I don't know how we would recover from a corrupt _user_undulator_list.json, because there's no backup accessible to the server.
* I don't understand why all user simulations were unavailable. This is the api_simulationData, which only should happen when the simulation is loaded. Are all simulations loaded by the client when we display the simulation list?

Things that we know we need to do:
* #1422 Change write operations to always write to a temporary then rename. This would avoid the corrupt file issue.
* #1312 Monitor disk use in the container and terminate the subprocess if too much. Alternatively, restrict the area where data can be written by mounting a restricted volume.
* #1064 Compress old simulations to free up disk space

Anything else relevant?

**Comment by moellep** [comment]
I can answer point 2 and 3.

The _user_undulator_list.json could be reset to empty "[]" in the case of a read failure. The file acts like a cache of all the user's different undulator settings and gets rebuilt as a user visits their individual simulations. I'll open a ticket for this.

If the _user_undulator_list.json is corrupted, it probably causes the SRW client to initialize incorrectly and causes it to become unusable.

**Comment by robnagler** [comment]
Could we rebuild _user_undulator_list.json completely by visiting all SRW simulations when it is corrupt? 

I was confused by "all simulations", when it should have read "all SRW simulations". It's not the simulation list that's corrupted, but you can't visit any SRW simulations.

The cookie code is definitely stable. The docker runner is not in use yet. We're working on rewriting it. 

You need these variables set:

```sh
export 'SIREPO_BEAKER_COMPAT_KEY=xyz'
export 'SIREPO_BEAKER_COMPAT_SECRET=/srv/sirepo/db/beaker_secret'
export 'SIREPO_COOKIE_HTTP_NAME=xyz'
export 'SIREPO_COOKIE_PRIVATE_KEY=qrs'
export 'SIREPO_RUNNER_JOB_CLASS=Celery'
```

The values `xyz` should be something like sirepo_alpha or sirepo_beta. I'm not sure how your system is set up.

The value `qrs` needs to be generated one time with `sirepo cookie gen_private_key`.

These values can be set in advance in your environment file, and then you can download the new image and restart.

**Comment by moellep** [comment]
The _user_undulator_list.json is like a favorite list. We don't want to scan all the simulations, because that would bring in all the example undulators which wouldn't be useful. The undulator/beam user lists could be improved, but for now #1456 fixes the bug.

**Comment by mrakitin** [comment]
> I was confused by "all simulations", when it should have read "all SRW simulations". It's not the simulation list that's corrupted, but you can't visit any SRW simulations.

@robnagler, yes, exactly, that's what I expressed in the issue's body ("... all user's simulations to be inaccessible"), and the title of the issue, starting with `SRW:` implied that the problem was observed with SRW simulations only. Sorry if it wasn't clear.

> The cookie code is definitely stable. The docker runner is not in use yet. We're working on rewriting it.
> 
> You need these variables set:
> 
> ```shell
> export 'SIREPO_BEAKER_COMPAT_KEY=xyz'
> export 'SIREPO_BEAKER_COMPAT_SECRET=/srv/sirepo/db/beaker_secret'
> export 'SIREPO_COOKIE_HTTP_NAME=xyz'
> export 'SIREPO_COOKIE_PRIVATE_KEY=qrs'
> export 'SIREPO_RUNNER_JOB_CLASS=Celery'
> ```
> 
> The values `xyz` should be something like sirepo_alpha or sirepo_beta. I'm not sure how your system is set up.
> 
> The value `qrs` needs to be generated one time with `sirepo cookie gen_private_key`.
> 
> These values can be set in advance in your environment file, and then you can download the new image and restart.

OK, thanks! I'll try it at some point once we have no users on the server. Should any old variables be removed?

**Comment by robnagler** [comment]
I don't know what variables you have set. These are the ones we have set:

```sh
PYKERN_PKCONFIG_CHANNEL
PYKERN_PKDEBUG_REDIRECT_LOGGING
PYKERN_PKDEBUG_WANT_PID_TIME
PYTHONUNBUFFERED
SIREPO_BEAKER_COMPAT_KEY
SIREPO_BEAKER_COMPAT_SECRET
SIREPO_CELERY_TASKS_BROKER_URL
SIREPO_COMSOL_REGISTER_MAIL_PASSWORD
SIREPO_COMSOL_REGISTER_MAIL_RECIPIENT_EMAIL
SIREPO_COMSOL_REGISTER_MAIL_SERVER
SIREPO_COMSOL_REGISTER_MAIL_SUPPORT_EMAIL
SIREPO_COMSOL_REGISTER_MAIL_USERNAME
SIREPO_COOKIE_HTTP_NAME
SIREPO_COOKIE_PRIVATE_KEY
SIREPO_FEATURE_CONFIG_API_MODULES
SIREPO_OAUTH_GITHUB_KEY
SIREPO_OAUTH_GITHUB_SECRET
SIREPO_PKCLI_SERVICE_IP
SIREPO_PKCLI_SERVICE_PORT
SIREPO_PKCLI_SERVICE_PROCESSES
SIREPO_PKCLI_SERVICE_RUN_DIR
SIREPO_PKCLI_SERVICE_THREADS
SIREPO_RUNNER_DOCKER_IMAGE
SIREPO_RUNNER_JOB_CLASS
SIREPO_SERVER_DB_DIR
TZ
```

**Comment by robnagler** [comment]
You don't need the COMSOL vars or, for now, SIREPO_RUNNER_DOCKER_IMAGE

**Comment by mrakitin** [comment]
Thanks, got it!
