### ISSUE TITLE
Fix readthedocs

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#1463]
Module index is broken. Works for pykern.

**Comment by robnagler** [comment]
Latest error. Need to add some code to fix problems like this with an pip upgrade:

```txt
Installed /home/docs/checkouts/readthedocs.org/user_builds/sirepo/envs/latest/lib/python2.7/site-packages/oauthlib-2.1.0-py2.7.egg
error: python-dateutil 2.4.2 is installed but python-dateutil>=2.6.0 is required by set(['github3.py'])
```

**Comment by robnagler** [comment]
Found this buried in https://readthedocs.org/projects/pykern/builds/8172720/ 

Need to build something in pkconfig when READTHEDOCS is on or autodoc(?).

```txt
WARNING: autodoc: failed to import module u'pykern.pkcli.github'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pykern/envs/latest/local/lib/python2.7/site-packages/sphinx/ext/autodoc/importer.py", line 152, in import_module
    __import__(modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pykern/checkouts/latest/pykern/pkcli/github.py", line 212, in <module>
    _cfg()
  File "/home/docs/checkouts/readthedocs.org/user_builds/pykern/checkouts/latest/pykern/pkcli/github.py", line 193, in _cfg
    cfg = pkconfig.init(**p)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pykern/checkouts/latest/pykern/pkconfig.py", line 369, in init
    _iter_decls(decls, res)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pykern/checkouts/latest/pykern/pkconfig.py", line 671, in _iter_decls
    r[kp] = _resolver(d)(k, d)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pykern/checkouts/latest/pykern/pkconfig.py", line 744, in _resolve_value
    '{}: config value missing and is required'.format(key.msg)
AssertionError: pykern.pkcli.github.password: config value missing and is required
```

**Comment by robnagler** [comment]
d74868ab4720913b235d1656452de32481a2dc0f does fix the issue, but it hardwires python-dateutil>=2.60 in a file that can't be generated in advance. Next step is to try to fix pksetup.py to workaround this.
