### ISSUE TITLE
ImportError: No module named opmd_viewer

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#152]
When I try to run Sirepo for SRW in a new browser (list all calculations in Expert mode), there is an exception:
```python
10.0.2.2 - - [07/Apr/2016 20:53:19] "POST /simulation-list HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/beaker/middleware.py", line 155, in __call__
    return self.wrap_app(environ, session_start_response)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/server.py", line 456, in app_simulation_list
    simulation_db.iterate_simulation_datafiles(simulation_type, simulation_db.process_simulation_list, search),
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/simulation_db.py", line 107, in iterate_simulation_datafiles
    str(simulation_dir(simulation_type).join('*', SIMULATION_DATA_FILE)),
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/simulation_db.py", line 212, in simulation_dir
    d = _user_dir().join(simulation_type)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/simulation_db.py", line 363, in _user_dir
    _user_dir_create()
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/simulation_db.py", line 384, in _user_dir_create
    for f in sirepo.template.import_module(app_name).static_lib_files():
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/template/__init__.py", line 22, in import_module
    return importlib.import_module('.' + simulation_type, __name__)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/template/warp.py", line 11, in <module>
    from opmd_viewer import OpenPMDTimeSeries
ImportError: No module named opmd_viewer
```

Probably it's caused by https://github.com/radiasoft/sirepo/commit/5de04e7b21e4a409954ef14ae083beeac9d15d76. @moellep, could you please have a look at it?

**Comment by moellep** [comment]
It is missing opmd_viewer module which I think is bundled with the
containers. Rob, how would Maksim pull the new containers into the dev?

Paul

**Comment by mrakitin** [comment]
OK, I see. I wonder if it's necessary to have all the codes available if I'm only interested in SRW?

**Comment by robnagler** [comment]
You can install it this way:

curl radia.run | bash -s containers/radiasoft/beamsim warp

It should be in the docker and vagrant image. We aren't supporting
non-image installs.

**Comment by mrakitin** [comment]
Thanks Rob. Still not sure, why SRW-related code requires something from WARP. Can it be handled somehow?

**Comment by robnagler** [comment]
The problem is that sirepo imports many codes. We haven't modularized it so
that it dynamically imports the modules based on incoming requests. It's
not clear that's a good idea, because server start should let you know if
the basic code is ok.

**Comment by mrakitin** [comment]
I think at least a simple try/except would not hurt in this case (https://github.com/radiasoft/sirepo/blob/master/sirepo/simulation_db.py#L384), especially when the code is pulled from GitHub to the older image:
```python
        try:
            for f in sirepo.template.import_module(app_name).static_lib_files():
                f.copy(d)
        except ImportError as e:
            print('\nCould not import a module: {}\n'.format(e.message))
```
This would be safer for other codes.

**Comment by robnagler** [comment]
Error messages do not get read by end users. Imagine if we deploy this, and
there is a bug in a any file related to that module. The import will fail,
and nobody will know why without digging in the logs. The server will start
so you won't see an error there.

Does this not work?

curl radia.run | bash -s containers/radiasoft/beamsim warp

**Comment by mrakitin** [comment]
OK, that makes sense to have an empty list of examples in case we have a problem in the imported module.

The command works fine on my system, though the compilation of warp took much time. Now the list of SRW examples is displayed.

**Comment by robnagler** [comment]
Great. I think since we are deploying with docker images, we can add a
feature that is invoked with a configuration parameter, e.g.
SIREPO_SERVER_CODES=srw:warp: ...  The default would be all codes, but if
you only wanted srw, you'd have to set this variable. server.py drives the
rest of the imports so no routes would be added for codes not in the list.

**Comment by mrakitin** [comment]
Nice idea Rob!

**Comment by mrakitin** [comment]
This issue is resolved. I'm closing it.
@robnagler, do you mind to create a separate ticket for configuration parameter `SIREPO_SERVER_CODES`?
