### ISSUE TITLE
warp field_reader: IOError: Unable to open file (File signature not found)

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#156]
I think field_reader needs better protection around which file it opens. I got this error when canceling a simulation:

```text
10.10.10.1 - - [08/Apr/2016 01:24:13] "POST /run-status HTTP/1.1" 200 -
10.10.10.1 - - [08/Apr/2016 01:24:13] "GET /simulation-frame/warp*oqwnkwIH*fieldAnimation*E_x_1*17*1460078639 HTTP/1.1" 200 -
10.10.10.1 - - [08/Apr/2016 01:24:13] "GET /simulation-frame/warp*oqwnkwIH*particleAnimation*z_x_219_0_0_0_0_0_0_0_0_0_0_0_0*17*1460078639 HTTP/1.1" 200 -
../sirepo/server.py:731:kill Killing: pid=11156 sid=oqwnkwIH-animation
../sirepo/server.py:757:sigchld_handler waitpid: pid=11156 status=9
../sirepo/server.py:762:sigchld_handler Deleted: sid=oqwnkwIH-animation
10.10.10.1 - - [08/Apr/2016 01:24:15] "POST /run-status HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/beaker/middleware.py", line 155, in __call__
    return self.wrap_app(environ, session_start_response)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/server.py", line 384, in app_run_status
    completion = template.background_percent_complete(data, run_dir, False)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/template/warp.py", line 48, in background_percent_complete
    Fr, info = field_reader.read_field_circ(str(files[file_index]), 'E/r')
  File "/home/vagrant/src/openPMD/openPMD-viewer/opmd_viewer/openpmd_timeseries/data_reader/field_reader.py", line 78, in read_field_circ
    dfile = h5py.File( filename, 'r' )
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/h5py/_hl/files.py", line 260, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/h5py/_hl/files.py", line 89, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/var/tmp/pip-build-bAFCRc/h5py/h5py/_objects.c:2574)

  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/var/tmp/pip-build-bAFCRc/h5py/h5py/_objects.c:2533)

  File "h5py/h5f.pyx", line 76, in h5py.h5f.open (/var/tmp/pip-build-bAFCRc/h5py/h5py/h5f.c:1811)

IOError: Unable to open file (File signature not found)
10.10.10.1 - - [08/Apr/2016 01:24:16] "POST /run-cancel HTTP/1.1" 200 -
10.10.10.1 - - [08/Apr/2016 01:24:17] "POST /simulation-list HTTP/1.1" 200 -
10.10.10.1 - - [08/Apr/2016 01:24:18] "GET /simulation/warp/Mv0uXDm3 HTTP/1.1" 200 -
```

**Comment by bruhwile** [comment]
Is this still open?

**Comment by robnagler** [comment]
I think I worked around it.
