### ISSUE TITLE
`module not found` error

### ISSUE THREAD

**Issue by awalter-bnl** [radiasoft/sirepo#1654]
Was attempting to follow some[ instructions]( https://github.com/NSLS-II/sirepo-bluesky#prepare-local-sirepo-server ) from @mrakitin for getting sirepo to work with bluesky. however when trying to start a sirepo server I get the following `module not found` error. 

```py
(Sirepo) alwalter@awalter01:~/sirepoSIREPO_FEATURE_CONFIG_SIM_TYPES=srw SIREPO_FEATURE_CONFIG_API_MODULES=bluesky SIREPO_BLUESKY_AUTH_SECRET=bluesky sirepo service http
Traceback (most recent call last):
  File "/home/alwalter/miniconda3/envs/Sirepo/bin/sirepo", line 11, in <module>
    load_entry_point('sirepo', 'console_scripts', 'sirepo')()
  File "/home/alwalter/sirepo/sirepo/sirepo_console.py", line 18, in main
    return pkcli.main('sirepo')
  File "/home/alwalter/miniconda3/envs/Sirepo/lib/python2.7/site-packages/pykern/pkcli/__init__.py", line 98, in main
    argh.dispatch(parser, argv=argv)
  File "/home/alwalter/miniconda3/envs/Sirepo/lib/python2.7/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/home/alwalter/miniconda3/envs/Sirepo/lib/python2.7/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/home/alwalter/miniconda3/envs/Sirepo/lib/python2.7/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "/home/alwalter/sirepo/sirepo/pkcli/service.py", line 66, in http
    app = server.init(use_reloader=use_reloader)
  File "/home/alwalter/sirepo/sirepo/server.py", line 724, in init
    uri_router.init(_app)
  File "/home/alwalter/sirepo/sirepo/uri_router.py", line 107, in init
    register_api_module(importlib.import_module('sirepo.' + n))
  File "/home/alwalter/miniconda3/envs/Sirepo/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named bluesky
```

**Comment by robnagler** [comment]
@awalter-bnl @mrakitin Please note that there were recent changes to the configuration: https://github.com/radiasoft/sirepo/issues/1626#issue-439235184

**Comment by mrakitin** [comment]
Thanks @robnagler. We updated the env vars, so the API works fine for us with:
```
SIREPO_FEATURE_CONFIG_SIM_TYPES=srw SIREPO_AUTH_METHODS=bluesky:guest SIREPO_AUTH_BLUESKY_SECRET=bluesky sirepo service http
```
