### ISSUE TITLE
sirepo admin purge_guest_users fails if link to file doesn't exist

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#1888]
Not sure why symlinks to files don't exist, that's a separate issue:

```txt
sirepo admin purge_guest_users --days=30
Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/py2/bin/sirepo", line 10, in <module>
    sys.exit(main())
  File "/home/vagrant/.pyenv/versions/2.7.16/envs/py2/lib/python2.7/site-packages/sirepo/sirepo_console.py", line 18, in main
    return pkcli.main('sirepo')
  File "/home/vagrant/.pyenv/versions/2.7.16/envs/py2/lib/python2.7/site-packages/pykern/pkcli/__init__.py", line 98, in main
    argh.dispatch(parser, argv=argv)
  File "/home/vagrant/.pyenv/versions/2.7.16/envs/py2/lib/python2.7/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/home/vagrant/.pyenv/versions/2.7.16/envs/py2/lib/python2.7/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/home/vagrant/.pyenv/versions/2.7.16/envs/py2/lib/python2.7/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "/home/vagrant/.pyenv/versions/2.7.16/envs/py2/lib/python2.7/site-packages/sirepo/pkcli/admin.py", line 109, in purge_guest_users
    if (now - now.fromtimestamp(f.mtime())).days <= days:
  File "/home/vagrant/.pyenv/versions/2.7.16/envs/py2/lib/python2.7/site-packages/py/_path/local.py", line 416, in mtime
    return self.stat().mtime
  File "/home/vagrant/.pyenv/versions/2.7.16/envs/py2/lib/python2.7/site-packages/py/_path/local.py", line 545, in stat
    return Stat(self, py.error.checked_call(os.stat, self.strpath))
  File "/home/vagrant/.pyenv/versions/2.7.16/envs/py2/lib/python2.7/site-packages/py/_error.py", line 86, in checked_call
    raise cls("%s%r" % (func.__name__, args))
py.error.ENOENT: [No such file or directory]: stat('/srv/sirepo/db/user/SNIP/srw/SNIP/intensityReport/magn_meas_chx.zip',)
```

**Comment by robnagler** [comment]
Will be taken care of in #2376
