### ISSUE TITLE
tornado callback exception logging behavior

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/sirepo#2055]
There is a problem with my configuration, pykern, and or tornado in the interaction between tornado logging and pykern logging. In the below example if I leave the pkdp import commented out I get a nice stack trace when the exception occurs in the callback. If I uncomment the line I get a not very helpful message that there was an exception but no stack trace.

```python
# from pykern.pkdebug import pkdp
import tornado.ioloop
import tornado.gen

async def a():
    await tornado.gen.sleep(0)
    b()

def b():
    10/0
tornado.ioloop.IOLoop.current().spawn_callback(a)
tornado.ioloop.IOLoop.current().start()
````

No pkdp. Exception with stack trace:
```
ERROR:tornado.application:Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object
at 0x7fa2cb979588>>, <Task finished coro=<a() done, defined at t.py:5> exception=ZeroDivisionError('division by zero')>)
Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "t.py", line 7, in a
    b()
  File "t.py", line 10, in b
    10/0
ZeroDivisionError: division by zero
```

With pkdp. Exception with no stack trace
```
../../../../.pyenv/versions/3.7.2/lib/python3.7/asyncio/selector_events.py:53:__init__ DEBUG:asyncio:Using selector: EpollSelector
../../../../.pyenv/versions/py3/lib/python3.7/site-packages/tornado/ioloop.py:763:_run_callback ERROR:tornado.application:Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7fbe97c73ba8>>, <Task finished coro=<a() done, defined at t.py:5> exception=ZeroDivisionError('division by zero')>)
```

@robnagler If you take a look at this let me know. Otherwise I will circle back today or tomorrow to figure out what is going.

**Comment by robnagler** [comment]
Let's debug tomorrow. It's probably a logging thing...

**Comment by robnagler** [comment]
Speaking of which, make sure you don't have PYKERN_* set when running your tests to see if one of those config vars are contributing (specifically redirecting logging)

**Comment by robnagler** [comment]
Yes, this shows a trace:

```sh
PYKERN_PKDEBUG_REDIRECT_LOGGING= python t.py
```

And, this doesn't:

```sh
PYKERN_PKDEBUG_REDIRECT_LOGGING=1 python t.py
```

**Comment by e-carlin** [comment]
Aha solved it for me. Thanks!

**Comment by robnagler** [comment]
I still want to figure out the logging issue. Python's logging handler needs to handle it, but it's not clear how....
