### ISSUE TITLE
Sbatch: Error getting raw data file

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/sirepo#2181]
Steps to reproduce:
1. Run supervisor with sbatch
2. Warppba -> electron beam -> dynamics
3. login and start the sim
4. let a frame come back
5. Select download raw data file

```
Jan 13 21:54:13 20529     0 job_driver/__init__.py:191:_receive agentId=6ehPDnmaRSgN54dKwtcOkCUoRySn3DTL msg={'agentId': '6ehPDnmaRSgN54dKwtcOkCUoRySn3DTL', 'opName': 'error', 'error': "exception='PKDict' object has no attribute 'sbatchCores'", 'stack': 'Traceback (most recent call last):\n  File "\
/home/vagrant/src/radiasoft/pykern/pykern/pkcollections.py", line 51, in __getattr__\n    return self.__getattribute__(name)\nAttributeError: \'PKDict\' object has no attribute \'sbatchCores\'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last\
):\n  File "/home/vagrant/src/radiasoft/pykern/pykern/pkcollections.py", line 54, in __getattr__\n    return self[name]\nKeyError: \'sbatchCores\'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/home/vagrant/src/radiasoft/sirepo\
/sirepo/pkcli/job_agent.py", line 134, in _op\n    return await getattr(self, \'_op_\' + m.opName)(m)\n  File "/home/vagrant/src/radiasoft/sirepo/sirepo/pkcli/job_agent.py", line 147, in _op_analysis\n    return await self._cmd(msg)\n  File "/home/vagrant/src/radiasoft/sirepo/sirepo/pkcli/job_agent\
.py", line 176, in _cmd\n    await p.start()\n  File "/home/vagrant/src/radiasoft/sirepo/sirepo/pkcli/job_agent.py", line 382, in start\n    (\'sbatch\', self._sbatch_script()),\n  File "/home/vagrant/src/radiasoft/sirepo/sirepo/pkcli/job_agent.py", line 458, in _sbatch_script\n    \'\'\'\n  File "\
/home/vagrant/src/radiasoft/pykern/pykern/pkcollections.py", line 56, in __getattr__\n    return self.__getattribute__(name)\nAttributeError: \'PKDict\' object has no attribute \'sbatchCores\'\n\nException was printed at:\n\nAttributeError: \'PKDict\' object has no attribute \'sbatchCores\'\n  File\
 "/home/vagrant/.pyenv/versions/py3/bin/sirepo", line 11, in <module>\n    load_entry_point(\'sirepo\', \'console_scripts\', \'sirepo\')()\n  File "/home/vagrant/src/radiasoft/sirepo/sirepo/sirepo_console.py", line 18, in main\n    return pkcli.main(\'sirepo\')\n  File "/home/vagrant/src/radiasoft/\
pykern/pykern/pkcli/__init__.py", line 108, in main\n    res = argh.dispatch(parser, argv=argv)\n  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/argh/dispatching.py", line 174, in dispatch\n    for line in lines:\n  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3\
/lib/python3.7/site-packages/argh/dispatching.py", line 277, in _execute_command\n    for line in result:\n  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/argh/dispatching.py", line 260, in _call\n    result = function(*positional, **keywords)\n  File "/home/vagrant\
/src/radiasoft/sirepo/sirepo/pkcli/job_agent.py", line 63, in default_command\n    i.start()\n  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/tornado/platform/asyncio.py", line 148, in start\n    self.asyncio_loop.run_forever()\n  File "/home/vagrant/.pyenv/versions\
/3.7.2/lib/python3.7/asyncio/base_events.py", line 539, in run_forever\n    self._run_once()\n  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/asyncio/base_events.py", line 1775, in _run_once\n    handle._run()\n  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/asyncio/events.py", \
line 88, in _run\n    self._context.run(self._callback, *self._args)\n  File "/home/vagrant/src/radiasoft/sirepo/sirepo/pkcli/job_agent.py", line 96, in loop\n    m = await self._op(m)\n', 'opId': 'QDsfprN2pEOpJLWy9wDokyHtvzueeujG'}
Jan 13 21:54:13 20529     0 job_driver/__init__.py:196:_receive agentId=6ehPDnmaRSgN54dKwtcOkCUoRySn3DTL No reply={'agentId': '6ehPDnmaRSgN54dKwtcOkCUoRySn3DTL', 'opName': 'error', 'error': "exception='PKDict' object has no attribute 'sbatchCores'", 'stack': 'Traceback (most recent call last):\n  F\
ile "/home/vagrant/src/radiasoft/pykern/pykern/pkcollections.py", line 51, in __getattr__\n    return self.__getattribute__(name)\nAttributeError: \'PKDict\' object has no attribute \'sbatchCores\'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call\
 last):\n  File "/home/vagrant/src/radiasoft/pykern/pykern/pkcollections.py", line 54, in __getattr__\n    return self[name]\nKeyError: \'sbatchCores\'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/home/vagrant/src/radiasoft/s\
irepo/sirepo/pkcli/job_agent.py", line 134, in _op\n    return await getattr(self, \'_op_\' + m.opName)(m)\n  File "/home/vagrant/src/radiasoft/sirepo/sirepo/pkcli/job_agent.py", line 147, in _op_analysis\n    return await self._cmd(msg)\n  File "/home/vagrant/src/radiasoft/sirepo/sirepo/pkcli/job_\
agent.py", line 176, in _cmd\n    await p.start()\n  File "/home/vagrant/src/radiasoft/sirepo/sirepo/pkcli/job_agent.py", line 382, in start\n    (\'sbatch\', self._sbatch_script()),\n  File "/home/vagrant/src/radiasoft/sirepo/sirepo/pkcli/job_agent.py", line 458, in _sbatch_script\n    \'\'\'\n  F\
ile "/home/vagrant/src/radiasoft/pykern/pykern/pkcollections.py", line 56, in __getattr__\n    return self.__getattribute__(name)\nAttributeError: \'PKDict\' object has no attribute \'sbatchCores\'\n\nException was printed at:\n\nAttributeError: \'PKDict\' object has no attribute \'sbatchCores\'\n \
 File "/home/vagrant/.pyenv/versions/py3/bin/sirepo", line 11, in <module>\n    load_entry_point(\'sirepo\', \'console_scripts\', \'sirepo\')()\n  File "/home/vagrant/src/radiasoft/sirepo/sirepo/sirepo_console.py", line 18, in main\n    return pkcli.main(\'sirepo\')\n  File "/home/vagrant/src/radia\
soft/pykern/pykern/pkcli/__init__.py", line 108, in main\n    res = argh.dispatch(parser, argv=argv)\n  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/argh/dispatching.py", line 174, in dispatch\n    for line in lines:\n  File "/home/vagrant/.pyenv/versions/3.7.2/env\
s/py3/lib/python3.7/site-packages/argh/dispatching.py", line 277, in _execute_command\n    for line in result:\n  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/argh/dispatching.py", line 260, in _call\n    result = function(*positional, **keywords)\n  File "/home/va\
grant/src/radiasoft/sirepo/sirepo/pkcli/job_agent.py", line 63, in default_command\n    i.start()\n  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/tornado/platform/asyncio.py", line 148, in start\n    self.asyncio_loop.run_forever()\n  File "/home/vagrant/.pyenv/ver\
sions/3.7.2/lib/python3.7/asyncio/base_events.py", line 539, in run_forever\n    self._run_once()\n  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/asyncio/base_events.py", line 1775, in _run_once\n    handle._run()\n  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/asyncio/events.\
py", line 88, in _run\n    self._context.run(self._callback, *self._args)\n  File "/home/vagrant/src/radiasoft/sirepo/sirepo/pkcli/job_agent.py", line 96, in loop\n    m = await self._op(m)\n', 'opId': 'QDsfprN2pEOpJLWy9wDokyHtvzueeujG'}
```

**Comment by robnagler** [comment]
A test for this case would be good.
