### ISSUE TITLE
nersc: stream closed in fastcgi job_cmd

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#2255]
Run with 512 cores.  Not sure what the issue was, but the stream was closed by job_cmd. I wonder if the json file was bad (srw young's).

```txt
Feb 08 02:37:12 47853     0 /global/homes/n/nagler/.pyenv/versions/3.7.2/envs/sirepo-alpha/lib/python3.7/site-packages/sirepo/pkcli/job_agent.py:200:_op op=analysis opId=qOK0zVwyb3A4vnxbfmMLFDyPbTyBlu54 runDir=/global/cscratch
1/sd/nagler/sirepo-alpha/user/PNS1DrRo/srw/PNS1DrRo-kaZBniUA-multiElectronAnimation
Feb 08 02:37:12 47853     0 /global/homes/n/nagler/.pyenv/versions/3.7.2/envs/sirepo-alpha/lib/python3.7/site-packages/sirepo/pkcli/job_agent.py:274:_fastcgi_handle_error msg={'analysisModel': 'multiElectronAnimation', 'api':
'api_simulationFrame', 'computeJid': 'PNS1DrRo-kaZBniUA-multiElectronAnimation', 'computeJobHash': 'HashIsUnused', 'computeJobSerial': 1581129311, 'computeModel': 'multiElectronAnimation', 'data': {'computeJobHash': 'HashIsUnu
sed', 'computeJobSerial': 1581129311, 'frameIndex': 1581129379, 'frameReport': 'multiElectronAnimation', 'intensityPlotsWidth': '0', 'rotateAngle': '0', 'rotateReshape': '1', 'simulationId': 'kaZBniUA', 'simulationType': 'srw'
}, 'isParallel': False, 'jobCmd': 'get_simulation_frame', 'jobRunMode': 'sbatch', 'opId': 'qOK0zVwyb3A4vnxbfmMLFDyPbTyBlu54', 'opName': 'analysis', 'reqId': 's3biL8cdyr7LVgjrgW6SFnROsTRZx1Al', 'runDir': '/global/cscratch1/sd/n
agler/sirepo-alpha/user/PNS1DrRo/srw/PNS1DrRo-kaZBniUA-multiElectronAnimation', 'shifterImage': 'radiasoft/sirepo:alpha', 'simulationId': 'kaZBniUA', 'simulationType': 'srw', 'uid': 'PNS1DrRo', 'userDir': '/global/cscratch1/sd
/nagler/sirepo-alpha/user/PNS1DrRo'} error=Stream is closed stack=Traceback (most recent call last):
  File "/global/homes/n/nagler/.pyenv/versions/3.7.2/envs/sirepo-alpha/lib/python3.7/site-packages/sirepo/pkcli/job_agent.py", line 323, in _fastcgi_read
    await s.write(pkjson.dump_bytes(m) + b'
')
  File "/global/homes/n/nagler/.pyenv/versions/3.7.2/envs/sirepo-alpha/lib/python3.7/site-packages/tornado/iostream.py", line 546, in write
    self._check_closed()
  File "/global/homes/n/nagler/.pyenv/versions/3.7.2/envs/sirepo-alpha/lib/python3.7/site-packages/tornado/iostream.py", line 1009, in _check_closed
    raise StreamClosedError(real_error=self.error)
tornado.iostream.StreamClosedError: Stream is closed

Exception was printed at:

Feb 08 02:37:12 47853     0 /global/homes/n/nagler/.pyenv/versions/3.7.2/envs/sirepo-alpha/lib/python3.7/site-packages/tornado/ioloop.py:763:_run_callback ERROR:tornado.application:Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x2aab3f311550>>, <Task finished coro=<_Dispatcher._fastcgi_read() done, defined at /global/homes/n/nagler/.pyenv/versions/3.7.2/envs/sirepo-alpha/lib/python3.7/site-packages/sirepo/pkcli/job_agent.py:313> exception=AttributeError("'_SbatchCmd' object has no attribute '_destroy'")>)
Traceback (most recent call last):
  File "/global/homes/n/nagler/.pyenv/versions/3.7.2/envs/sirepo-alpha/lib/python3.7/site-packages/sirepo/pkcli/job_agent.py", line 323, in _fastcgi_read
    await s.write(pkjson.dump_bytes(m) + b'\n')
  File "/global/homes/n/nagler/.pyenv/versions/3.7.2/envs/sirepo-alpha/lib/python3.7/site-packages/tornado/iostream.py", line 546, in write
    self._check_closed()
  File "/global/homes/n/nagler/.pyenv/versions/3.7.2/envs/sirepo-alpha/lib/python3.7/site-packages/tornado/iostream.py", line 1009, in _check_closed
    raise StreamClosedError(real_error=self.error)
tornado.iostream.StreamClosedError: Stream is closed
```

Nothing in the logs. run.log says:
```txt
Warning: Computation of terminating terms of radiation integrals WAS NOT PERFORMED for some values of input parameters ^M because asymptotic expansion validity criterion was not satisfied. This may influence the accuracy of the computation. ^M One can try to fix the problem by modifying Magnetic Field definition range and/or Integration limits.
```

**Comment by e-carlin** [comment]
Closing this for now as it isn't reproducible and we are handling the error.
