### ISSUE TITLE
_SbatchCmd' object has no attribute '_destroy

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#2256]
During #2255 

```txt
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/global/homes/n/nagler/.pyenv/versions/3.7.2/envs/sirepo-alpha/lib/python3.7/site-packages/pykern/pkcollections.py", line 51, in __getattr__
    return self.__getattribute__(name)
AttributeError: '_SbatchCmd' object has no attribute '_destroy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/global/homes/n/nagler/.pyenv/versions/3.7.2/envs/sirepo-alpha/lib/python3.7/site-packages/pykern/pkcollections.py", line 54, in __getattr__
    return self[name]
KeyError: '_destroy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/global/homes/n/nagler/.pyenv/versions/3.7.2/envs/sirepo-alpha/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/global/homes/n/nagler/.pyenv/versions/3.7.2/envs/sirepo-alpha/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/global/homes/n/nagler/.pyenv/versions/3.7.2/envs/sirepo-alpha/lib/python3.7/site-packages/sirepo/pkcli/job_agent.py", line 330, in _fastcgi_read
    await self._fastcgi_handle_error(m, e, pkdexc())
  File "/global/homes/n/nagler/.pyenv/versions/3.7.2/envs/sirepo-alpha/lib/python3.7/site-packages/sirepo/pkcli/job_agent.py", line 280, in _fastcgi_handle_error
    self._fastcgi_cmd._destroy()
  File "/global/homes/n/nagler/.pyenv/versions/3.7.2/envs/sirepo-alpha/lib/python3.7/site-packages/pykern/pkcollections.py", line 56, in __getattr__
    return self.__getattribute__(name)
AttributeError: '_SbatchCmd' object has no attribute '_destroy'
Feb 08 02:43:12 47853     0 /global/homes/n/nagler/.pyenv/versions/3.7.2/envs/sirepo-alpha/lib/python3.7/site-packages/sirepo/pkcli/job_agent.py:200:_op op=analysis opId=6HFPjfmFINv0RvO3nnx6KRSQEd2JCRTs runDir=/global/cscratch1/sd/nagler/sirepo-alpha/user/PNS1DrRo/srw/PNS1DrRo-kaZBniUA-multiElectronAnimation
Feb 08 02:43:12 47853     0 /global/homes/n/nagler/.pyenv/versions/3.7.2/envs/sirepo-alpha/lib/python3.7/site-packages/sirepo/pkcli/job_agent.py:210:_op op=analysis exception='NoneType' object has no attribute 'put_nowait' stack=Traceback (most recent call last):
  File "/global/homes/n/nagler/.pyenv/versions/3.7.2/envs/sirepo-alpha/lib/python3.7/site-packages/sirepo/pkcli/job_agent.py", line 202, in _op
    return await getattr(self, '_op_' + m.opName)(m)
  File "/global/homes/n/nagler/.pyenv/versions/3.7.2/envs/sirepo-alpha/lib/python3.7/site-packages/sirepo/pkcli/job_agent.py", line 215, in _op_analysis
    return await self._cmd(msg)
  File "/global/homes/n/nagler/.pyenv/versions/3.7.2/envs/sirepo-alpha/lib/python3.7/site-packages/sirepo/pkcli/job_agent.py", line 240, in _cmd
    return await self._fastcgi_op(msg)
  File "/global/homes/n/nagler/.pyenv/versions/3.7.2/envs/sirepo-alpha/lib/python3.7/site-packages/sirepo/pkcli/job_agent.py", line 310, in _fastcgi_op
    self._fastcgi_msg_q.put_nowait(msg)
AttributeError: 'NoneType' object has no attribute 'put_nowait'
```

**Comment by e-carlin** [comment]
Fixed by 1803b04
