### ISSUE TITLE
service.http doesn't handle reloads properly

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#2454]
Processes are still running, and outputing to the screen (below):

```txt
 1570 ?        Sl     0:03 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/bin/python /home/vagrant/.pyenv/versions/py3/bin/sirepo job_agent start
 1735 ?        Ssl    0:10 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/bin/python /home/vagrant/.pyenv/versions/py3/bin/sirepo job_cmd /home/vagrant/src/radiasoft/sirepo/run/user/GPgyplOD/agent-local/M\
DdIIlKiRImKH7wq0gD4IzaHk9GzSAS9/in-4bWSq3LCenvWHP8HEKv0HyUt1tZEi9rk.json
 1934 ?        Sl     0:01 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/bin/python /home/vagrant/.pyenv/versions/py3/bin/sirepo job_agent start
16190 pts/6    Sl     0:01 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/bin/python /home/vagrant/.pyenv/versions/py3/bin/sirepo job_agent start
16355 ?        Ssl    0:01 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/bin/python /home/vagrant/.pyenv/versions/py3/bin/sirepo job_cmd /home/vagrant/src/radiasoft/sirepo/run/user/GPgyplOD/agent-local/W\
pvWovABc9YrEBJBQ1CRPjo336T68mXv/in-402ZYyh7SCPOdQ24ilwsXjHEUDoDreL3.json
16952 pts/4    S+     0:00 grep py
20490 pts/2    S+     1:11 /home/vagrant/.pyenv/versions/py3/bin/python -m http.server 2916
```

```txt
Apr 17 23:14:29 16190     0 ../../../../../sirepo/pkcli/job_agent.py:176:loop websocket closed in response to len=None send=None
Apr 17 23:14:29 16190     0 ../../../../../sirepo/pkcli/job_agent.py:181:loop error=Stream is closed stack=Traceback (most recent call last):
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/pkcli/job_agent.py", line 178, in loop
    'websocket closed in response to len={} send={}',
tornado.iostream.StreamClosedError: Stream is closed

Exception was printed at:

tornado.iostream.StreamClosedError: Stream is closed
  File "/home/vagrant/.pyenv/versions/py3/bin/sirepo", line 11, in <module>
    load_entry_point('sirepo', 'console_scripts', 'sirepo')()
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/sirepo_console.py", line 18, in main
    return pkcli.main('sirepo')
  File "/home/vagrant/src/radiasoft/pykern/pykern/pkcli/__init__.py", line 108, in main
    res = argh.dispatch(parser, argv=argv)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/pkcli/job_agent.py", line 69, in start
    return i.add_callback_from_signal(_terminate, d)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/tornado/platform/asyncio.py", line 149, in start
    self.asyncio_loop.run_forever()
  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/asyncio/base_events.py", line 539, in run_forever
    self._run_once()
  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/asyncio/base_events.py", line 1775, in _run_once
    handle._run()
  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
usage: sirepo service [-h] {celery,flower,http,nginx-proxy,rabbitmq,uwsgi} ...
sirepo service: error: invalid choice: 'flask' (choose from 'celery', 'flower', 'http', 'nginx-proxy', 'rabbitmq', 'uwsgi')
[py3;@v sirepo]$ Apr 17 23:14:30 16190     0 ../../../../../sirepo/pkcli/job_agent.py:181:loop error=[Errno 111] Connection refused stack=Traceback (most recent call last):
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/pkcli/job_agent.py", line 165, in loop
    validate_cert=sirepo.job.cfg.verify_tls,
ConnectionRefusedError: [Errno 111] Connection refused
```

**Comment by robnagler** [comment]
This might have been caused by checking out master, which was still py2.

**Comment by e-carlin** [comment]
Can this be closed? I haven't seen the bug.

**Comment by robnagler** [comment]
Sure, if it surfaces, we'll fix.
