### ISSUE TITLE
unit test random failures with radia enabled in feature config

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#2469]
On master, unit test pass if you comment out "radia" from the feature_config.py ALPHA_CODES.

WIth radia present, tests fail randomly with "msg=invalid simulation type=radia".

For example, run "py.test tests/job_concurrency1_test.py" multiple times. Sometimes it passes, sometimes it fails:

```
[py3;@v4 sirepo]$ py.test tests/job_concurrency1_test.py
================================================== test session starts ===================================================
platform linux -- Python 3.7.2, pytest-5.4.1, py-1.8.1, pluggy-0.13.1
rootdir: /home/vagrant/src/radiasoft/sirepo
collected 1 item

tests/job_concurrency1_test.py .                                                                                   [100%]

==================================================== warnings summary ====================================================
tests/job_concurrency1_test.py::test_myapp
  /home/vagrant/src/radiasoft/pykern/pykern/pkrunpy.py:10: DeprecationWarning: the imp module is deprecated in favour of i
mportlib; see the module's documentation for alternative uses
    import imp

-- Docs: https://docs.pytest.org/en/latest/warnings.html
============================================== 1 passed, 1 warning in 4.68s ==============================================
[py3;@v4 sirepo]$ py.test tests/job_concurrency1_test.py
================================================== test session starts ===================================================
platform linux -- Python 3.7.2, pytest-5.4.1, py-1.8.1, pluggy-0.13.1
rootdir: /home/vagrant/src/radiasoft/sirepo
collected 1 item

tests/job_concurrency1_test.py E                                                                                   [100%]

========================================================= ERRORS =========================================================
______________________________________________ ERROR at setup of test_myapp ______________________________________________
Traceback (most recent call last):
  File "/home/vagrant/src/radiasoft/sirepo/tests/conftest.py", line 75, in fc
    return _fc(request, fc_module)
  File "/home/vagrant/src/radiasoft/sirepo/tests/conftest.py", line 268, in _fc
    fc_module.sr_login_as_guest(sim_type=c)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/srunit.py", line 324, in sr_login_as_guest
    self.sr_get('authGuestLogin', {'simulation_type': self.sr_sim_type})
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/srunit.py", line 271, in sr_get
    return self.__req(route_or_uri, params, query, self.get, raw_response=True, **kwargs)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/srunit.py", line 562, in __req
    PKDict(error='server error uri={}'.format(m.group(1))),
sirepo.util.Error: Error(error=server error uri=/#/error)
...
Apr 29 23:41:18 21416     0 sirepo/http_reply.py:246:_gen_exception_error unsupported exception=<class 'AssertionError'> msg=invalid simulation type=radia
```

**Comment by robnagler** [comment]
@moellep What happens when you run:

```sh
pykern test tests/job_concurrency1_test.py
```

And, what happens with:

```sh
py.test --tb=native -v -s -rs tests/job_concurrency1_test.py
```

**Comment by robnagler** [comment]
Never mind. I'm seeing it fail now.
