### ISSUE TITLE
TypeError: 'function' object is not iterable

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#2479]
```txt
May 04 23:35:54 fnl6b.bivio.biz sirepo[9699]: Traceback (most recent call last):
May 04 23:35:54 fnl6b.bivio.biz sirepo[9699]: File "/home/vagrant/.pyenv/versions/py3/bin/sirepo", line 8, in <module>
May 04 23:35:54 fnl6b.bivio.biz sirepo[9699]: sys.exit(main())
May 04 23:35:54 fnl6b.bivio.biz sirepo[9699]: File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/sirepo_console.py", line 18, in main
May 04 23:35:54 fnl6b.bivio.biz sirepo[9699]: return pkcli.main('sirepo')
May 04 23:35:54 fnl6b.bivio.biz sirepo[9699]: File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/pykern/pkcli/__init__.py", line 108, in main
May 04 23:35:54 fnl6b.bivio.biz sirepo[9699]: res = argh.dispatch(parser, argv=argv)
May 04 23:35:54 fnl6b.bivio.biz sirepo[9699]: File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/argh/dispatching.py", line 174, in dispatch
May 04 23:35:54 fnl6b.bivio.biz sirepo[9699]: for line in lines:
May 04 23:35:54 fnl6b.bivio.biz sirepo[9699]: File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/argh/dispatching.py", line 277, in _execute_command
May 04 23:35:54 fnl6b.bivio.biz sirepo[9699]: for line in result:
May 04 23:35:54 fnl6b.bivio.biz sirepo[9699]: File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/argh/dispatching.py", line 260, in _call
May 04 23:35:54 fnl6b.bivio.biz sirepo[9699]: result = function(*positional, **keywords)
May 04 23:35:54 fnl6b.bivio.biz sirepo[9699]: File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/pkcli/service.py", line 140, in uwsgi
May 04 23:35:54 fnl6b.bivio.biz sirepo[9699]: values = dict(pkcollections.map_items(cfg))
May 04 23:35:54 fnl6b.bivio.biz sirepo[9699]: File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/pykern/pkcollections.py", line 304, in map_items
May 04 23:35:54 fnl6b.bivio.biz sirepo[9699]: return [(k, value[k]) for k in value]
May 04 23:35:54 fnl6b.bivio.biz sirepo[9699]: TypeError: 'function' object is not iterable
```

**Comment by e-carlin** [comment]
Argh that's on me. Should be cfg().
