### ISSUE TITLE
supervisor_purge_free_sims_test.py:75:_status_eq expect=free_user_purged != actual=completed

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#2481]
I'm rerunning the build, because it failed with, which I assume is spurious:

```txt
_______________________ test_myapp_free_user_sim_purged ________________________
Traceback (most recent call last):
  File "/rscontainers/sirepo/tests/supervisor_purge_free_sims_test.py", line 93, in test_myapp_free_user_sim_purged
    _status_eq(next_req_free, 'free_user_purged')
  File "/rscontainers/sirepo/tests/supervisor_purge_free_sims_test.py", line 75, in _status_eq
    fc.sr_post('runStatus', next_req).state
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/pykern/pkunit.py", line 217, in pkeq
    pkfail('expect={} != actual={}', expect, actual)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/pykern/pkunit.py", line 230, in pkfail
    raise PKFail('{} {}'.format(call, msg))
pykern.pkunit.PKFail: tests/supervisor_purge_free_sims_test.py:75:_status_eq expect=free_user_purged != actual=completed
```

**Comment by robnagler** [comment]
failed again. I will debug tomorrow. I'll revert the build.

**Comment by e-carlin** [comment]
I've identified the bug. To reproduce, set cfg.purge_free_after_start to some time in the future (in UTC). Run the test and the bug should appear.

The problem is that if purge_free_after_start is in the future compared to now. Then we won't run the purge until that time. Our test expects the next purge to happen in purge_free_after_period + 1 second.
