### ISSUE TITLE
SRW - recalculation of the reports on the Source page

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#250]
Request from @ochubar: the reports on the Source page are essentially independent, therefore change of parameters in one report (e.g., Photon Energy in the Intensity Report) should not cause recalculation of other reports.

**Comment by mrakitin** [comment]
Oleg reminded about this issue, raise the priority since it's important for real use case.

**Comment by robnagler** [comment]
I think this is fixed. Would you check @mrakitin?

**Comment by mrakitin** [comment]
This works fine now, thanks, but there is the following error in the server log when I click <kbd>Save Changes</kbd> button:
```python
10.0.2.2 - - [22/Sep/2016 14:02:34] "POST /save-simulation HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/beaker/middleware.py", line 155, in __call__
    return self.wrap_app(environ, session_start_response)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/server.py", line 407, in app_save_simulation_data
    res = _validate_serial(data)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/server.py", line 824, in _validate_serial
    res = simulation_db.validate_serial(data)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/simulation_db.py", line 602, in validate_serial
    req_ser = req_data['models']['simulation']['simulationSerial']
KeyError: 'simulationSerial'
```
So I have to click <kbd>Save Changes</kbd> twice. Probably we have this issue reported?

**Comment by mrakitin** [comment]
I didn't do <kbd>Discard Changes to Example</kbd>. After I did, the problem was solved.

**Comment by robnagler** [comment]
Can you send me the file that causes the error or the steps to reproduce
it? It should always add a simulationSerial on the incoming before it
checks it so I don't quite understand unless the version is somehow current.

**Comment by mrakitin** [comment]
The version of the example was obsolete. Since the schema was changed, the changes to the example should be discarded - after that it works fine.

**Comment by robnagler** [comment]
However, it should detect this case in fixup_old_data, which is why I'm
confused. Do you have the original example file in error?

**Comment by mrakitin** [comment]
Unfortunately no, I already reverted it.

**Comment by robnagler** [comment]
I didn't update the version number between the time of the last checkin and
the latest fix that "guarantees" fixup_old_data is called. There was a bug
in the discard example case which was fixed. The schema didn't change, but
the code did so I guess we should just update the version anyway.

**Comment by mrakitin** [comment]
OK, thanks for the explanation.

**Comment by mrakitin** [comment]
@moellep, I think I mentioned this issue during our today's telecon. I'll create a new issue to make the report's parameters like photon energy independent.
