### ISSUE TITLE
sbatch_test.test_srw_data_file failing with _timeout MAX_CASE_RUN_SECS

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#2550]
@e-carlin is this working in your environment? This is the only case that fails on master:

```sh
SIREPO_CONFTEST_MAX_CASE_RUN_SECS=20 pykern test sbatch_test.py case=srw
```

The job_agent is still running after the failure, which is strange. Here's some of the log and the first stack:

```txt
Jun 02 20:48:52 24432     0 ../sirepo/job_api.py:209:_request api=api_runStatus runDir=/home/vagrant/src/radiasoft/sirepo/tests/sbatch_work/db/user/RPFetQWC/srw/EDcWREFx/multiElectronAnimation
Jun 02 20:48:52 24432     0 ../sirepo/srunit.py:417:sr_run_sim pending
Jun 02 20:48:53 24432     0 ../sirepo/job_api.py:209:_request api=api_runStatus runDir=/home/vagrant/src/radiasoft/sirepo/tests/sbatch_work/db/user/RPFetQWC/srw/EDcWREFx/multiElectronAnimation
Jun 02 20:48:54 24432     0 ../sirepo/srunit.py:417:sr_run_sim pending
Jun 02 20:48:55 24432     0 ../sirepo/srunit.py:429:sr_run_sim runCancel
Jun 02 20:48:55 24432     0 ../sirepo/job_api.py:209:_request api=api_runCancel runDir=/home/vagrant/src/radiasoft/sirepo/tests/sbatch_work/db/user/RPFetQWC/srw/EDcWREFx/multiElectronAnimation
Jun 02 20:48:55 24439     0 ../sirepo/job_supervisor.py:334:receive ServerReq(api_runCancel, RPFetQWC-EDcWREFx-multiElectronAnimation)
Jun 02 20:48:55 24439     0 ../sirepo/job_supervisor.py:919:__init__ _Op(cancel, weUZ) runDir=/home/vagrant/src/radiasoft/sirepo/tests/sbatch_work/db/user/RPFetQWC/srw/EDcWREFx/multiElectronAni\
mation
Jun 02 20:48:55 24439     0 ../sirepo/job_supervisor.py:617:_receive_api_runCancel _ComputeJob(RPFetQWC-EDcWREFx-multiElectronAnimation u=RPFetQWC canceled [_Op(run, gUky), _Op(cancel, weUZ)]) \
cancel=[_Op(run, gUky), _Op(cancel, weUZ)]
Jun 02 20:48:55 24439     0 ../sirepo/job_driver/__init__.py:180:send SbatchDriver(a=rRn4 k=parallel u=RPFe [_Op(cancel, weUZ)]) _Op(cancel, weUZ) runDir=/home/vagrant/src/radiasoft/sirepo/test\
s/sbatch_work/vagrant/sirepo/user/RPFetQWC/srw/RPFetQWC-EDcWREFx-multiElectronAnimation
Jun 02 20:48:55 24439     0 ../sirepo/job_supervisor.py:959:reply_get _Op(cancel, weUZ) await _reply_q.get()
Jun 02 20:48:57 24432     0 ../sirepo/job_api.py:135:api_runCancel ignoring exception=conftest.py:180:_timeout MAX_CASE_RUN_SECS=20 exceeded stack=Traceback (most recent call last):
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/job_api.py", line 133, in api_runCancel
    return _request()
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/job_api.py", line 214, in _request
    verify=sirepo.job.cfg.verify_tls,
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/http/client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/http/client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/home/vagrant/src/radiasoft/sirepo/tests/conftest.py", line 180, in _timeout
    pkunit.pkfail('MAX_CASE_RUN_SECS={} exceeded', MAX_CASE_RUN_SECS)
  File "/home/vagrant/src/radiasoft/pykern/pykern/pkunit.py", line 230, in pkfail
    raise PKFail('{} {}'.format(call, msg))
pykern.pkunit.PKFail: conftest.py:180:_timeout MAX_CASE_RUN_SECS=20 exceeded
```

**Comment by e-carlin** [comment]
Works for me. Looking into it more.

**Comment by robnagler** [comment]
Here's the [sbatch_test.log.gz](https://github.com/radiasoft/sirepo/files/4719978/sbatch_test.log.gz). Thanks.

**Comment by e-carlin** [comment]
What is the status of your sbatch cluster? Run `sinfo`.

My best guess is that the node is down. This has [happened before](https://github.com/radiasoft/sirepo/issues/2136). The problem is that sbatch allows jobs submissions even when a node is down. The job is stuck in the "pending" state for ever (or at least a "long" time mine has been pending for 10 mins). This triggers the max_case_run_secs and the test fails. I don't know exactly what to do in this case. At a minimum we could log the reason whenever we get the sbatch status. 

The agent won't die probably because we aren't handling SIGALRM properly. It doesn't look like a kill is ever sent to the agent from the supervisor. It is a bit of a mystery to me how exactly the supervisor is dying because I added a handler for sigalrm and it wasn't called. I can investigate more if you think it is worth the time.
