### ISSUE TITLE
flash variable plot params.xmin missing

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#2569]
```txt
Jun 06 01:06:27     6     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_driver/__init__.py:274:_receive DockerDriver(a=NeL8 k=sequential u=PNS1 [_Op(analysis, WsQc)]) error msg={'agentId': 'NeL8hCyIlVfXZmD8ekb0Q8b90HRdFLK9', 'opId': 'WsQcVk4yxil23RVHMBgFpxL3Vqh3IvM1', 'opName': 'analysis', 'reply': {'error': 'report not generated', 'stack': 'Traceback (most recent call last):
File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/pkcli/job_cmd.py", line 202, in _do_get_simulation_frame
msg.data.copy().pkupdate(run_dir=msg.runDir),
File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/template/template_common.py", line 350, in sim_frame_dispatch
res = o(frame_args)
File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/template/flash.py", line 329, in sim_frame_varAnimation
xdomain = [params['xmin'], params['xmax']]
KeyError: 'xmin'
Exception was printed at:
KeyError: 'xmin'
File "/home/vagrant/.pyenv/versions/py3/bin/sirepo", line 8, in <module>
sys.exit(main())
File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/sirepo_console.py", line 18, in main
return pkcli.main('sirepo')
File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/pykern/pkcli/__init__.py", line 108, in main
res = argh.dispatch(parser, argv=argv)
File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/argh/dispatching.py", line 174, in dispatch
for line in lines:
File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/argh/dispatching.py", line 277, in _execute_command
for line in result:
File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/argh/dispatching.py", line 260, in _call
result = function(*positional, **keywords)
File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/pkcli/job_cmd.py", line 50, in default_command
sirepo.template.import_module(msg.simulationType)
File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/pkcli/job_cmd.py", line 181, in _do_fastcgi
sirepo.template.import_module(m.simulationType)
', 'state': 'error'}}
```

**Comment by ncook882** [comment]
Is this related to the density plot error in visualization tab?

![Screen Shot 2020-06-09 at 6 07 56 PM](https://user-images.githubusercontent.com/11053323/84212865-3def9700-aa7c-11ea-8c89-6694785bb0cc.png)

Currently seeing this error when running the RT Flame example at https://alpha.sirepo.com/flash#/visualization/WDLc54eL
