### ISSUE TITLE
CancelledError alpha status

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#2570]
status got a CancelledError. There must be some kind of race condition:

```txt
Jun 08 19:32:24     6     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_supervisor.py:334:receive ServerReq(api_runSimulation, 5ldIIHrF-QZuJXo6U-initialIntensityReport)
Jun 08 19:32:24     6     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_supervisor.py:919:__init__ _Op(run, jB6F) runDir=/srv/sirepo/db/user/5ldIIHrF/srw/QZuJXo6U/initialIntensityReport
Jun 08 19:32:24     6     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_driver/__init__.py:241:_agent_start DockerDriver(a=binf k=sequential u=5ldI [_Op(run, jB6F)]) _Op(run, jB6F) await _do_agent_start
Jun 08 19:32:24     6     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_driver/docker.py:111:kill DockerDriver(a=binf k=sequential u=5ldI [_Op(run, jB6F)]) cid=None
Jun 08 19:32:24     6     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_driver/docker.py:170:_do_agent_start DockerDriver(a=binf k=sequential u=5ldI [_Op(run, jB6F)]) agent_exec_dir=/srv/sirepo/db/user/5ldIIHrF/agent-docker/fnl6b.bivio.biz/srj-s-5ldIIHrF
Jun 08 19:32:29     6     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_driver/__init__.py:264:_agent_starting_timeout_handler DockerDriver(a=binf k=sequential u=5ldI [_Op(run, jB6F)]) timeout=5
Jun 08 19:32:29     6     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_driver/__init__.py:104:free_resources DockerDriver(a=binf k=sequential u=5ldI [_Op(run, jB6F)]) internal_error=timeout waiting for agent to start
Jun 08 19:32:29     6     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_driver/__init__.py:252:_agent_start DockerDriver(a=binf k=sequential u=5ldI []) error= stack=Traceback (most recent call last):
File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_driver/__init__.py", line 250, in _agent_start
await self._do_agent_start(op)
File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_driver/docker.py", line 189, in _do_agent_start
self._cid = await self._cmd(p + cmd, stdin=stdin, env=env)
File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_driver/docker.py", line 211, in _cmd
o = (await p.stdout.read_until_close()).decode('utf-8').rstrip()
concurrent.futures._base.CancelledError
Exception was printed at:
concurrent.futures._base.CancelledError
File "/home/vagrant/.pyenv/versions/py3/bin/sirepo", line 8, in <module>
sys.exit(main())
File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/sirepo_console.py", line 18, in main
return pkcli.main('sirepo')
File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/pykern/pkcli/__init__.py", line 108, in main
res = argh.dispatch(parser, argv=argv)
File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/argh/dispatching.py", line 174, in dispatch
for line in lines:
File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/argh/dispatching.py", line 277, in _execute_command
for line in result:
File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/argh/dispatching.py", line 260, in _call
result = function(*positional, **keywords)
File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/pkcli/job_supervisor.py", line 64, in default_command
tornado.ioloop.IOLoop.current().start()
File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/tornado/platform/asyncio.py", line 149, in start
self.asyncio_loop.run_forever()
File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/asyncio/base_events.py", line 539, in run_forever
self._run_once()
File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/asyncio/base_events.py", line 1775, in _run_once
handle._run()
File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/asyncio/events.py", line 88, in _run
self._context.run(self._callback, *self._args)
Jun 08 19:32:29     6     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_driver/__init__.py:104:free_resources DockerDriver(a=binf k=sequential u=5ldI []) internal_error=failure starting agent
Jun 08 19:32:30     6     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/tornado/web.py:2250:log_request INFO:tornado.access:200 POST /job-api-request (127.0.0.1) 6084.40ms
Jun 08 19:32:30     6     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_supervisor.py:334:receive ServerReq(api_runCancel, 5ldIIHrF-QZuJXo6U-initialIntensityReport)
Jun 08 19:32:30     6     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/tornado/web.py:2250:log_request INFO:tornado.access:200 POST /job-api-request (127.0.0.1) 1.51ms
Jun 08 19:32:34     6     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/tornado/web.py:2250:log_request INFO:tornado.access:101 GET /job-agent-websocket (10.1.2.6) 1.06ms
Jun 08 19:32:34     6     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/pkcli/job_supervisor.py:89:open uri=/job-agent-websocket remote_ip=10.1.2.6
Jun 08 19:32:34     6     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_driver/__init__.py:279:_receive DockerDriver(a=binf k=sequential u=5ldI []) opName=alive o=None
Jun 08 20:02:34     6     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_driver/docker.py:268:_kill_if_idle DockerDriver(a=binf k=sequential u=5ldI [])
Jun 08 20:02:34     6     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_driver/docker.py:111:kill DockerDriver(a=binf k=sequential u=5ldI []) cid=None
Jun 08 20:02:35     6     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_driver/__init__.py:198:websocket_on_close DockerDriver(a=binf k=sequential u=5ldI [])
Jun 08 20:02:35     6     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_driver/__init__.py:104:free_resources DockerDriver(a=binf k=sequential u=5ldI []) internal_error=None
Jun 08 20:05:40     6     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_supervisor.py:334:receive ServerReq(api_runSimulation, o9CpxGdO-F3i0cjUk-bunchReport)
Jun 08 20:05:40     6     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_driver/__init__.py:90:__init__ DockerDriver(a=Kkyi k=sequential u=o9Cp [])
Jun 08 20:05:40     6     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_supervisor.py:919:__init__ _Op(run, dJhM) runDir=/srv/sirepo/db/user/o9CpxGdO/elegant/F3i0cjUk/bunchReport
Jun 08 20:05:40     6     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_driver/__init__.py:241:_agent_start DockerDriver(a=Kkyi k=sequential u=o9Cp [_Op(run, dJhM)]) _Op(run, dJhM) await _do_agent_start
Jun 08 20:05:40     6     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_driver/docker.py:111:kill DockerDriver(a=Kkyi k=sequential u=o9Cp [_Op(run, dJhM)]) cid=None
Jun 08 20:05:40     6     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_driver/docker.py:170:_do_agent_start DockerDriver(a=Kkyi k=sequential u=o9Cp [_Op(run, dJhM)]) agent_exec_dir=/srv/sirepo/db/user/o9CpxGdO/agent-docker/fnl6b.bivio.biz/srj-s-o9CpxGdO
```

**Comment by robnagler** [comment]
Same thing

```txt
Jun 26 09:17:37     6     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_supervisor.py:333:receive ServerReq(api_runSimulation, 5ldIIHrF-QZuJXo6U-initialIntensityReport)
Jun 26 09:17:37     6     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_supervisor.py:918:__init__ _Op(run, YLd1) runDir=/srv/sirepo/db/user/5ldIIHrF/srw/QZuJXo6U/initialIntensityReport
Jun 26 09:17:37     6     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_driver/__init__.py:241:_agent_start DockerDriver(a=zBaW k=sequential u=5ldI [_Op(run, YLd1)]) _Op(run, YLd1) await _do_agent_start
Jun 26 09:17:37     6     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_driver/docker.py:111:kill DockerDriver(a=zBaW k=sequential u=5ldI [_Op(run, YLd1)]) cid=None
Jun 26 09:17:42     6     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_driver/__init__.py:264:_agent_starting_timeout_handler DockerDriver(a=zBaW k=sequential u=5ldI [_Op(run, YLd1)]) timeout=5
Jun 26 09:17:42     6     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_driver/__init__.py:104:free_resources DockerDriver(a=zBaW k=sequential u=5ldI [_Op(run, YLd1)]) internal_error=timeout waiting for agent to start
Jun 26 09:17:42     6     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_driver/__init__.py:252:_agent_start DockerDriver(a=zBaW k=sequential u=5ldI []) error= stack=Traceback (most recent call last):
File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_driver/__init__.py", line 249, in _agent_start
await self.kill()
File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_driver/docker.py", line 119, in kill
self._cname
File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_driver/docker.py", line 211, in _cmd
o = (await p.stdout.read_until_close()).decode('utf-8').rstrip()
concurrent.futures._base.CancelledError
Exception was printed at:
concurrent.futures._base.CancelledError
File "/home/vagrant/.pyenv/versions/py3/bin/sirepo", line 8, in <module>
sys.exit(main())
File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/sirepo_console.py", line 18, in main
return pkcli.main('sirepo')
File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/pykern/pkcli/__init__.py", line 108, in main
res = argh.dispatch(parser, argv=argv)
File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/argh/dispatching.py", line 174, in dispatch
for line in lines:
File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/argh/dispatching.py", line 277, in _execute_command
for line in result:
File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/argh/dispatching.py", line 260, in _call
result = function(*positional, **keywords)
File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/pkcli/job_supervisor.py", line 64, in default_command
tornado.ioloop.IOLoop.current().start()
File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/tornado/platform/asyncio.py", line 149, in start
self.asyncio_loop.run_forever()
File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/asyncio/base_events.py", line 539, in run_forever
self._run_once()
File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/asyncio/base_events.py", line 1775, in _run_once
handle._run()
File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/asyncio/events.py", line 88, in _run
self._context.run(self._callback, *self._args)
Jun 26 09:17:42     6     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_driver/__init__.py:104:free_resources DockerDriver(a=zBaW k=sequential u=5ldI []) internal_error=failure starting agent
Jun 26 09:17:42     6     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/tornado/web.py:2250:log_request INFO:tornado.access:200 POST /job-api-request (127.0.0.1) 5065.91ms
Jun 26 09:17:42     6     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_supervisor.py:333:receive ServerReq(api_runCancel, 5ldIIHrF-QZuJXo6U-initialIntensityReport)
Jun 26 09:17:42     6     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/tornado/web.py:2250:log_request INFO:tornado.access:200 POST /job-api-request (127.0.0.1) 3.03ms
```
