### ISSUE TITLE
Server Error- Sirepo Beamline report

### ISSUE THREAD

**Issue by messamer** [radiasoft/sirepo#2650]
I'm seeing a server error on beamline tab in alpha: https://alpha.sirepo.com/srw#/beamline/j0lipE6K

![Screen Shot 2020-07-08 at 11 01 11 AM](https://user-images.githubusercontent.com/29441306/86949541-08d27500-c10c-11ea-83d0-76581a773dc0.png)

**Comment by moellep** [comment]
This seems to be a cancel-job related problem. The report directory has one file:

```
$ ls j0lipE6K/initialIntensityReport/
sirepo-lib-file-list.txt
```

The log files show some odd canceling:
```
Jul 08 17:00:28 fnl6b.bivio.biz sirepo_job_supervisor[1221]: Jul 08 17:00:28     6     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_supervisor.py:321:receive ServerReq(api_runSimulation, tz89sKSM-j0lipE6K-initialIntensityReport)
Jul 08 17:00:28 fnl6b.bivio.biz sirepo_job_supervisor[1221]: Jul 08 17:00:28     6     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_supervisor.py:906:__init__ _Op(run, Cl5a) runDir=/srv/sirepo/db/user/tz89sKSM/srw/j0lipE6K/initialIntensityReport
Jul 08 17:00:28 fnl6b.bivio.biz sirepo_job_supervisor[1221]: Jul 08 17:00:28     6     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_driver/__init__.py:227:_agent_ready DockerDriver(a=8h0D k=sequential u=tz89 [_Op(run, DhUa), _Op(cancel, vS3p), _Op(run, Cl5a)]) _Op(run, Cl5a) await _websocket_ready
Jul 08 17:00:29 fnl6b.bivio.biz sirepo_job_supervisor[1221]: Jul 08 17:00:29     6     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_supervisor.py:321:receive ServerReq(api_runCancel, tz89sKSM-j0lipE6K-initialIntensityReport)
Jul 08 17:00:29 fnl6b.bivio.biz sirepo_job_supervisor[1221]: Jul 08 17:00:29     6     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_supervisor.py:906:__init__ _Op(cancel, Gi8R) runDir=/srv/sirepo/db/user/tz89sKSM/srw/j0lipE6K/initialIntensityReport
Jul 08 17:00:29 fnl6b.bivio.biz sirepo_job_supervisor[1221]: Jul 08 17:00:29     6     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_driver/__init__.py:227:_agent_ready DockerDriver(a=8h0D k=sequential u=tz89 [_Op(run, DhUa), _Op(cancel, vS3p), _Op(run, Cl5a), _Op(cancel, Gi8R)]) _Op(cancel, Gi8R) await _websocket_ready
Jul 08 17:00:29 fnl6b.bivio.biz sirepo_job_supervisor[1221]: Jul 08 17:00:29     6     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_supervisor.py:321:receive ServerReq(api_runSimulation, tz89sKSM-j0lipE6K-initialIntensityReport)
Jul 08 17:00:29 fnl6b.bivio.biz sirepo_job_supervisor[1221]: Jul 08 17:00:29     6     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_supervisor.py:906:__init__ _Op(run, 1aSz) runDir=/srv/sirepo/db/user/tz89sKSM/srw/j0lipE6K/initialIntensityReport
Jul 08 17:00:29 fnl6b.bivio.biz sirepo_job_supervisor[1221]: Jul 08 17:00:29     6     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_driver/__init__.py:227:_agent_ready DockerDriver(a=8h0D k=sequential u=tz89 [_Op(run, DhUa), _Op(cancel, vS3p), _Op(run, Cl5a), _Op(cancel, Gi8R), _Op(run, 1aSz)]) _Op(run, 1aSz) await _websocket_ready
Jul 08 17:00:30 fnl6b.bivio.biz sirepo_job_supervisor[1221]: Jul 08 17:00:30     6     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/tornado/web.py:2250:log_request INFO:tornado.access:101 GET /job-agent-websocket (10.1.2.6) 1.81ms
Jul 08 17:00:30 fnl6b.bivio.biz sirepo_job_supervisor[1221]: Jul 08 17:00:30     6     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/pkcli/job_supervisor.py:89:open uri=/job-agent-websocket remote_ip=10.1.2.6
Jul 08 17:00:30 fnl6b.bivio.biz sirepo_job_supervisor[1221]: Jul 08 17:00:30     6     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_driver/__init__.py:279:_receive DockerDriver(a=8h0D k=sequential u=tz89 [_Op(run, DhUa), _Op(cancel, vS3p), _Op(run, Cl5a), _Op(cancel, Gi8R), _Op(run, 1aSz)]) opName=alive o=None
Jul 08 17:00:30 fnl6b.bivio.biz sirepo_job_supervisor[1221]: Jul 08 17:00:30     6     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_driver/__init__.py:181:send DockerDriver(a=8h0D k=sequential u=tz89 [_Op(run, DhUa), _Op(cancel, vS3p), _Op(run, Cl5a), _Op(cancel, Gi8R), _Op(run, 1aSz)]) _Op(run, Cl5a) runDir=/srv/sirepo/db/user/tz89sKSM/srw/j0lipE6K/initialIntensityReport
Jul 08 17:00:30 fnl6b.bivio.biz sirepo_job_supervisor[1221]: Jul 08 17:00:30     6     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/tornado/web.py:2250:log_request INFO:tornado.access:200 POST /job-api-request (127.0.0.1) 1632.07ms
Jul 08 17:00:30 fnl6b.bivio.biz sirepo_job_supervisor[1221]: Jul 08 17:00:30     6     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_supervisor.py:604:_receive_api_runCancel _ComputeJob(tz89sKSM-j0lipE6K-intensityReport u=tz89sKSM canceled [_Op(run, DhUa), _Op(cancel, vS3p)]) cancel=[_Op(cancel, vS3p), _Op(run, DhUa)]
Jul 08 17:00:30 fnl6b.bivio.biz sirepo_job_supervisor[1221]: Jul 08 17:00:30     6     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_driver/__init__.py:181:send DockerDriver(a=8h0D k=sequential u=tz89 [_Op(cancel, vS3p), _Op(run, Cl5a), _Op(cancel, Gi8R), _Op(run, 1aSz)]) _Op(cancel, vS3p) runDir=/srv/sirepo/db/user/tz89sKSM/srw/j0lipE6K/intensityReport
Jul 08 17:00:30 fnl6b.bivio.biz sirepo_job_supervisor[1221]: Jul 08 17:00:30     6     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_supervisor.py:943:reply_get _Op(cancel, vS3p) await _reply_q.get()
Jul 08 17:00:30 fnl6b.bivio.biz sirepo_job_supervisor[1221]: Jul 08 17:00:30     6     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_supervisor.py:604:_receive_api_runCancel _ComputeJob(tz89sKSM-j0lipE6K-initialIntensityReport u=tz89sKSM pending [_Op(run, Cl5a), _Op(cancel, Gi8R), _Op(run, 1aSz)]) cancel=[_Op(cancel, Gi8R), _Op(run, Cl5a), _Op(run, 1aSz)]
Jul 08 17:00:30 fnl6b.bivio.biz sirepo_job_supervisor[1221]: Jul 08 17:00:30     6     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_driver/__init__.py:181:send DockerDriver(a=8h0D k=sequential u=tz89 [_Op(cancel, vS3p), _Op(cancel, Gi8R)]) _Op(cancel, Gi8R) runDir=/srv/sirepo/db/user/tz89sKSM/srw/j0lipE6K/initialIntensityReport

```

**Comment by robnagler** [comment]
@messamer is this reproducible for you?

**Comment by moellep** [comment]
From the logs, it looks like a cancel request is getting applied to 2 run requests. The order looks like:

Cl5a: j0lipE6K/initialIntensityReport (run)
Gi8R: j0lipE6K/initialIntensityReport (cancel)
1aSz: j0lipE6K/initialIntensityReport (run)

but when Gi8R is applied it cancels both Cl5a and 1aSz:

_receive_api_runCancel _ComputeJob(tz89sKSM-j0lipE6K-initialIntensityReport u=tz89sKSM pending [_Op(run, Cl5a), _Op(cancel, Gi8R), _Op(run, 1aSz)]) cancel=[_Op(cancel, Gi8R), _Op(run, Cl5a), _Op(run, 1aSz)]

**Comment by robnagler** [comment]
I think this is programmed behavior. The problem in this case is that the docker container took a long time to startup. It might have also been a burst of requests as the GUI thinks that something is canceled immediately. 

I was able to reproduce this way:

1. close all reports except Intensity on the Source tab
2. close all reports except Initial Intensity on the Beam tab
3. put time.sleep(10) just before sending "alive" in job_agent.py and set _AGENT_STARTING_SECS_DEFAULT = 20
4. restart supervisor
5. go to Source tab and edit Period or something
6. go to Beamline tab 
7. close Initial Intensity
8. open Initial Intensity

Interestingly, if you do something more complicated, you'll get a concurrent.futures._base.CancelledError:

```
Jul 08 23:50:36  9957     0 sirepo/job_driver/__init__.py:181:send LocalDriver(a=sE5U k=sequential u=5glK [_Op(cancel, pktm), _Op(cancel, i5CZ)]) _Op(cancel, pktm) runDir=/home/vagrant/src/radiasoft/sirepo/run/user/5glKnIAG/srw/nwjdGNjM/powerDensityR\
eport
Jul 08 23:50:36  9957     0 sirepo/job_supervisor.py:943:reply_get _Op(cancel, pktm) await _reply_q.get()
Jul 08 23:50:36  9957     0 sirepo/job_supervisor.py:974:set_job_status _Op(run, 23Z2) status=Waiting for CPU resources stack=Traceback (most recent call last):
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/job_supervisor.py", line 971, in set_job_status
    yield
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/job_supervisor.py", line 115, in alloc
    self._value = await self._q.get()
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/tornado.py", line 26, in get
    return await x
concurrent.futures._base.CancelledError

Exception was printed at:

concurrent.futures._base.CancelledError
  File "/home/vagrant/.pyenv/versions/py3/bin/sirepo", line 11, in <module>
    load_entry_point('sirepo', 'console_scripts', 'sirepo')()
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/sirepo_console.py", line 18, in main
    return pkcli.main('sirepo')
  File "/home/vagrant/src/radiasoft/pykern/pykern/pkcli/__init__.py", line 108, in main
    res = argh.dispatch(parser, argv=argv)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/pkcli/job_supervisor.py", line 64, in default_command
    tornado.ioloop.IOLoop.current().start()
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/tornado/platform/asyncio.py", line 149, in start
    self.asyncio_loop.run_forever()
  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/asyncio/base_events.py", line 539, in run_forever
    self._run_once()
  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/asyncio/base_events.py", line 1775, in _run_once
    handle._run()
  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/job_supervisor.py", line 115, in alloc
    self._value = await self._q.get()
  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
Jul 08 23:50:36  9957     0 sirepo/job_supervisor.py:974:set_job_status _Op(run, cgwi) status=Waiting for another simulation to complete stack=Traceback (most recent call last):
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/job_supervisor.py", line 971, in set_job_status
    yield
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/job_supervisor.py", line 115, in alloc
    self._value = await self._q.get()
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/tornado.py", line 26, in get
    return await x
concurrent.futures._base.CancelledError
```

I hate cancel.

**Comment by robnagler** [comment]
Wrote a test with a jig to insert a delay in the agent startup. myapp is sufficient to demonstrate the problem. In the GUI, it gets a server error. 

In the test, the simulation is left in a `pending` state after the runCancel executes.

The `concurrent.futures._base.CancelledError` is being thrown by a wait on a lock.  That's easy to check for, but not sure it is the right fix.

**Comment by e-carlin** [comment]
What is the desired behavior? That the second runSim comes back with data (as is written in the test) or that it comes back cancelled?

**Comment by robnagler** [comment]
I think the appropriate behavior is documented by the test:

1. t1 = runSim
2. sleep 1
3. runCanel t1
4. sleep 1
5. t2 = runSim
6. [sometime later] runStatus t2 returns plots

Note that with the agent startup delay step (1) does not return until the agent starts up. This is a bug or a feature, depending on how you look at it, but it can be ignored for now, since the GUI does not block on anything.

Another problem is that runCancel is idempotent. Inside the job_supervisor, at least, I don't think it should be. I think we would have a problem making it transactional over the wire unless we redesign how the GUI maintains state about simulations. I think that would be possible, but requires more thought. For this issue, when runCancel comes in, it should only operate on the existing queue. Probably could take a snapshot of the queue at its entry point, and validate it when it actually is canceling things. It is unlikely that runSimulation and runCancel will get out of order, and the consequence of the idempotent protocol is that this might happen, and a simulation might "run away" but highly unlikely.  (Cancels happen at "human speed".)

I don't think we need to bundle the CanceledError probably into this issue. It's an issue, but it is not caused by the above.
