### ISSUE TITLE
status failure 00:28:13 UTC 7/19/20

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#2672]
```txt
00:28:13 sirepo/job_api.py:212:_request api=api_runCancel runDir=/srv/sirepo/db/user/3MLgynkF/srw/qGZwT5aX/initialIntensityReport
00:28:13 sirepo/uri_router.py:93:call_api api=<function api_serverStatus at 0x7fd790e20d08> exception='PKDict' object has no attribute 'nextRequest' stack=Traceback (most recent call last):
00:28:13 pykern/pkcollections.py", line 51, in __getattr__
00:28:13 return self.__getattribute__(name)
00:28:13 AttributeError: 'PKDict' object has no attribute 'nextRequest'
00:28:13 During handling of the above exception, another exception occurred:
00:28:13 Traceback (most recent call last):
00:28:13 pykern/pkcollections.py", line 54, in __getattr__
00:28:13 return self[name]
00:28:13 KeyError: 'nextRequest'
00:28:13 During handling of the above exception, another exception occurred:
00:28:13 Traceback (most recent call last):
00:28:13 sirepo/uri_router.py", line 85, in call_api
00:28:13 r = flask.make_response(f(**kwargs) if kwargs else f())
00:28:13 sirepo/status.py", line 42, in api_serverStatus
00:28:13 _run_tests()
00:28:13 sirepo/status.py", line 85, in _run_tests
00:28:13 d = r.nextRequest
00:28:13 pykern/pkcollections.py", line 56, in __getattr__
00:28:13 return self.__getattribute__(name)
00:28:13 AttributeError: 'PKDict' object has no attribute 'nextRequest'
00:28:13 Exception was printed at:
00:28:13 AttributeError: 'PKDict' object has no attribute 'nextRequest'
00:28:13 flask/app.py", line 2464, in __call__
00:28:13 return self.wsgi_app(environ, start_response)
00:28:13 flask/app.py", line 2447, in wsgi_app
00:28:13 response = self.full_dispatch_request()
00:28:13 flask/app.py", line 1950, in full_dispatch_request
00:28:13 rv = self.dispatch_request()
00:28:13 flask/app.py", line 1936, in dispatch_request
00:28:13 return self.view_functions[rule.endpoint](**req.view_args)
00:28:13 sirepo/uri_router.py", line 224, in _dispatch
00:28:13 return call_api(route.func, kwargs)
00:28:13 sirepo/http_reply.py:246:_gen_exception_error unsupported exception=<class 'AttributeError'> msg='PKDict' object has no attribute 'nextRequest'
```

sirepo_job_supervisor

```txt
00:28:02 Jul 19 00:28:02     6     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/s
ite-packages/sirepo/job_supervisor.py:336:receive ServerReq(api_runSimulation, 3MLgynkF-qGZwT5aX-initialIntensityReport)
00:28:02 sirepo/job_supervisor.py:921:__init__ _Op(analysis, qZ5X) runDir=/srv/sirepo/db/user/3MLgynkF/srw/qGZwT5aX/initialIntensityReport
00:28:02 sirepo/job_driver/__init__.py:232:_agent_start DockerDriver(a=4WWP k=sequential u=3MLg [_Op(analysis, qZ5X)]) _Op(analysis, qZ5X) await _do_agent_start
00:28:02 sirepo/job_driver/docker.py:111:kill DockerDriver(a=4WWP k=sequential u=3MLg [_Op(analysis, qZ5X)]) cid=None
00:28:02 sirepo/job_driver/docker.py:170:_do_agent_start DockerDriver(a=4WWP k=sequential u=3MLg [_Op(analysis, qZ5X)]) agent_exec_dir=/srv/sirepo/db/user/3MLgynkF/agent-docker/fnl13b.bivio.biz/srj-s-3MLgynkF
00:28:07 sirepo/job_driver/__init__.py:255:_agent_starting_timeout_handler DockerDriver(a=4WWP k=sequential u=3MLg [_Op(analysis, qZ5X)]) timeout=5
00:28:07 sirepo/job_driver/__init__.py:97:free_resources DockerDriver(a=4WWP k=sequential u=3MLg [_Op(analysis, qZ5X)]) internal_error=timeout waiting for agent to start
00:28:07 sirepo/job_driver/__init__.py:243:_agent_start DockerDriver(a=4WWP k=sequential u=3MLg []) error= stack=Traceback (most recent call last):
00:28:07 sirepo/job_driver/__init__.py", line 241, in _agent_start
00:28:07 await self._do_agent_start(op)
00:28:07 sirepo/job_driver/docker.py", line 189, in _do_agent_start
00:28:07 self._cid = await self._cmd(p + cmd, stdin=stdin, env=env)
00:28:07 sirepo/job_driver/docker.py", line 211, in _cmd
00:28:07 o = (await p.stdout.read_until_close()).decode('utf-8').rstrip()
00:28:07 concurrent.futures._base.CancelledError
00:28:07 Exception was printed at:
00:28:07 concurrent.futures._base.CancelledError
00:28:07 File "/home/vagrant/.pyenv/versions/py3/bin/sirepo", line 8, in <module>
00:28:07 sys.exit(main())
00:28:07 sirepo/sirepo_console.py", line 18, in main
00:28:07 return pkcli.main('sirepo')
00:28:07 pykern/pkcli/__init__.py", line 108, in main
00:28:07 res = argh.dispatch(parser, argv=argv)
00:28:07 argh/dispatching.py", line 174, in dispatch
00:28:07 for line in lines:
00:28:07 argh/dispatching.py", line 277, in _execute_command
00:28:07 for line in result:
00:28:07 argh/dispatching.py", line 260, in _call
00:28:07 result = function(*positional, **keywords)
00:28:07 sirepo/pk
cli/job_supervisor.py", line 64, in default_command
00:28:07 tornado.ioloop.IOLoop.current().start()
00:28:07 tornado/platform/asyncio.py", line 149, in start
00:28:07 self.asyncio_loop.run_forever()
00:28:07 File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/asyncio/base_events.py", line 539, in run_forever
00:28:07 self._run_once()
00:28:07 File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/asyncio/base_events.py", line 1775, in _run_once
00:28:07 handle._run()
00:28:07 File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/asyncio/events.py", line 88, in _run
00:28:07 self._context.run(self._callback, *self._args)
00:28:07 sirepo/job_driver/__init__.py:97:free_resources DockerDriver(a=4WWP k=sequential u=3MLg []) internal_error=failure starting agent
00:28:07 tornado/web.py:2250:log_request INFO:tornado.access:200 POST /job-api-request (127.0.0.1) 5021.91ms
00:28:08 sirepo/job_supervisor.py:921:__init__ _Op(analysis, jLGc) runDir=/srv/sirepo/db/user/3MLgynkF/srw/qGZwT5aX/initialIntensityReport
00:28:08 sirepo/job_driver/__init__.py:232:_agent_start DockerDriver(a=4WWP k=sequential u=3MLg [_Op(analysis, jLGc)]) _Op(analysis, jLGc) await _do_agent_start
00:28:08 sirepo/job_driver/docker.py:111:kill DockerDriver(a=4WWP k=sequential u=3MLg [_Op(analysis, jLGc)]) cid=None
00:28:13 sirepo/job_driver/__init__.py:255:_agent_starting_timeout_handler DockerDriver(a=4WWP k=sequential u=3MLg [_Op(analysis, jLGc)]) timeout=5
00:28:13 sirepo/job_driver/__init__.py:97:free_resources DockerDriver(a=4WWP k=sequential u=3MLg [_Op(analysis, jLGc)]) internal_error=timeout waiting for agent to start
00:28:13 sirepo/job_driver/__init__.py:243:_agent_start DockerDriver(a=4WWP k=sequential u=3MLg []) error= stack=Traceback (most recent call last):
00:28:13 sirepo/job_driver/__init__.py", line 240, in _agent_start
00:28:13 await self.kill()
00:28:13 sirepo/job_driver/docker.py", line 119, in kill
00:28:13 self._cname
00:28:13 sirepo/job_driver/docker.py", line 211, in _cmd
00:28:13 o = (await p.stdout.read_until_close()).decode('utf-8').rstrip()
00:28:13 concurrent.futures._base.CancelledError
00:28:13 Exception was printed at:
00:28:13 concurrent.futures._base.CancelledError
00:28:13 File "/home/vagrant/.pyenv/versions/py3/bin/sirepo", line 8, in <module>
00:28:13 sys.exit(main())
00:28:13 sirepo/sirepo_console.py", line 18, in main
00:28:13 return pkcli.main('sirepo')
00:28:13 pykern/pkcli/__init__.py", line 108, in main
00:28:13 res = argh.dispatch(parser, argv=argv)
00:28:13 argh/dispatching.py", line 174, in dispatch
00:28:13 for line in lines:
00:28:13 argh/dispatching.py", line 277, in _execute_command
00:28:13 for line in result:
00:28:13 argh/dispatching.py", line 260, in _call
00:28:13 result = function(*positional, **keywords)
00:28:13 sirepo/pkcli/job_supervisor.py", line 64, in default_command
00:28:13 tornado.ioloop.IOLoop.current().start()
00:28:13 tornado/platform/asyncio.py", line 149, in start
00:28:13 self.asyncio_loop.run_forever()
00:28:13 File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/asyncio/base_events.py", line 539, in run_forever
00:28:13 self._run_once()
00:28:13 File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/asyncio/base_events.py", line 1775, in _run_once
00:28:13 handle._run()
00:28:13 File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/asyncio/events.py", line 88, in _run
00:28:13 self._context.run(self._callback, *self._args)
00:28:13 sirepo/job_driver/__init__.py:97:free_resources DockerDriver(a=4WWP k=sequential u=3MLg []) internal_error=failure starting agent
00:28:13 tornado/web.py:2250:log_request INFO:tornado.access:200 POST /job-api-request (127.0.0.1) 5015.84ms
```

**Comment by robnagler** [comment]
@e-carlin lmk if you need help. (visit https://github.com/radiasoft/sirepo/issues/2672#issue-661923969 for full logs). I have a feeling that we just need to bump the timer.

**Comment by robnagler** [comment]
Oddly, we had the same error on alpha at Jul 19 00:31:11 UTC. I looked in the docker logs and only saw the start message. Normally, you'd see start followed by inputs to stdin.

**Comment by e-carlin** [comment]
Thoughts:
1. Yes, the timer should be increased. We timed out waiting to kill the existing agent. I'm not sure how much to increase it by. It is currently at 5 seconds. Maybe increase to 8?
2. Docker doesn't handle the [_base.CancelledError](https://github.com/radiasoft/sirepo/blob/c7285cf277d48b9642e5bd45a33c27d92270486a/sirepo/job_driver/docker.py#L122). It needs to. I'll fix this along with all of the other cases (#2664).
3. I can't reproduce the error exactly. This is somewhat concerning. Our error was that d had no attribute nextRequest. I get a server error back in my tests which leads me to believe we have another more subtle bug... Should I investigate some more or make these changes and we can wait and see?

**Comment by robnagler** [comment]
1. 10. It's a timeout so it shouldn't matter. I don't understand why it would take so long.
2. thanks
3. It's fine. Look at status.py. It doesn't test for error, which is fine, because it error, which is what we want.

**Comment by e-carlin** [comment]
Regarding point 3, I'm not sure I agree. It does [test for error](https://github.com/radiasoft/sirepo/blob/fe25da77b1131fd5a16fec0ffe2af511c3bf280e/sirepo/status.py#L77). We should've gotten back state=error (that is all I can get back in my tests) and we didn't which seems strange to me.

**Comment by robnagler** [comment]
Old eyes. :(  Maybe status.py needs to be fixed to log what it does get back. If it doesn't happen again, oh well. If it does, we'll have more info.
