### ISSUE TITLE
cancel_delay_test fails on alpha build

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#2712]
Disabled test for current alpha release. Failure log:
```
sirepo/job_supervisor.py:975:set_job_status _Op(run, 8NVF) status=Waiting for another simulation to complete stack=Traceback (most recent call last):
  File "sirepo/job_supervisor.py", line 972, in set_job_status
    yield
  File "sirepo/job_supervisor.py", line 115, in alloc
    self._value = await self._q.get()
  File "sirepo/tornado.py", line 26, in get
    return await x
concurrent.futures._base.CancelledError

Exception was printed at:

concurrent.futures._base.CancelledError
  File "bin/sirepo", line 8, in <module>
    sys.exit(main())
  File "sirepo/sirepo_console.py", line 18, in main
    return pkcli.main('sirepo')
  File "pykern/pkcli/__init__.py", line 108, in main
    res = argh.dispatch(parser, argv=argv)
  File "argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "sirepo/pkcli/job_supervisor.py", line 64, in default_command
    tornado.ioloop.IOLoop.current().start()
  File "tornado/platform/asyncio.py", line 149, in start
    self.asyncio_loop.run_forever()
  File "asyncio/base_events.py", line 539, in run_forever
    self._run_once()
  File "asyncio/base_events.py", line 1775, in _run_once
    handle._run()
  File "asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "sirepo/job_supervisor.py", line 115, in alloc
    self._value = await self._q.get()
  File "contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
sirepo/job_driver/__init__.py:290:_receive LocalDriver(a=GILh k=sequential u=UhgY [_Op(cancel, XwRo), _Op(run, hANv)]) opName=run o=hANv
sirepo/job_supervisor.py:817:_run error=Trying to overwrite existing jobStatusMessage="Exception: , while Waiting for another simulation to complete" with status="Running" stack=Traceback (most recent call last):
  File "sirepo/job_supervisor.py", line 789, in _run
    with op.set_job_status('Running'):
  File "contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "sirepo/job_supervisor.py", line 970, in set_job_status
    self.computeJob.set_status(self, status)
  File "sirepo/job_supervisor.py", line 342, in set_status
    f'Trying to overwrite existing jobStatusMessage="{s}" with status="{status}"'
AssertionError: Trying to overwrite existing jobStatusMessage="Exception: , while Waiting for another simulation to complete" with sta
tus="Running"

Exception was printed at:

AssertionError: Trying to overwrite existing jobStatusMessage="Exception: , while Waiting for another simulation to complete" with sta
tus="Running"
  File "bin/sirepo", line 8, in <module>
    sys.exit(main())
  File "sirepo/sirepo_console.py", line 18, in main
    return pkcli.main('sirepo')
  File "pykern/pkcli/__init__.py", line 108, in main
    res = argh.dispatch(parser, argv=argv)
  File "argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "sirepo/pkcli/job_supervisor.py", line 64, in default_command
    tornado.ioloop.IOLoop.current().start()
  File "tornado/platform/asyncio.py", line 149, in start
    self.asyncio_loop.run_forever()
  File "asyncio/base_events.py", line 539, in run_forever
    self._run_once()
  File "asyncio/base_events.py", line 1775, in _run_once
    handle._run()
  File "asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
sirepo/pkcli/job_agent.py:232:_op opName=cancel o=XwRo runDir=myapp/8PIzYNDM/heightWeightReport
sirepo/job_driver/__init__.py:290:_receive LocalDriver(a=GILh k=sequential u=UhgY [_Op(cancel, XwRo)]) opName=ok o=XwRo
sirepo/job_api.py:202:_request api=api_runStatus runDir=myapp/8PIzYNDM/heightWeightReport
sirepo/srunit.py:454:sr_run_sim error
FAILED
sirepo/job_driver/local.py:89:kill LocalDriver(a=GILh k=sequential u=UhgY []) pid=5807
sirepo/pkcli/job_agent.py:803:kill _Process(pid=6007 cmd=_Cmd(a=GILh jid=UhgYD13N-8PIzYNDM-heightWeightReport o=hANv job_cmd=compute run_dir=/rscontainers/sirepo/tests
/cancel_delay_work/db/user/UhgYD13N/myapp/8PIzYNDM/heightWeightReport))
sirepo/job_driver/local.py:109:_agent_on_exit LocalDriver(a=GILh k=sequential u=UhgY []) returncode=0
sirepo/job_driver/__init__.py:199:websocket_on_close LocalDriver(a=GILh k=sequential u=UhgY [])
sirepo/job_driver/__init__.py:105:free_resources LocalDriver(a=GILh k=sequential u=UhgY []) internal_error=None

```

**Comment by e-carlin** [comment]
One minor issue. `e` [here](https://github.com/radiasoft/sirepo/blob/fa854564c4422f803dd8683714ac0a44a97910b7/sirepo/job_supervisor.py#L978) is an error with no message. That is why we get the funny `Exception: , while Waiting` text. If str(exception) is False we need to call repr(exception) [here](https://github.com/radiasoft/sirepo/blob/fa854564c4422f803dd8683714ac0a44a97910b7/sirepo/job_supervisor.py#L343).

I'm pretty sure this code has an important bug to solve (something more than adjusting time values). I'm just not sure where it is. Need to do some more thinking.
