### ISSUE TITLE
Cannot process flags argument with a compiled patter

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/sirepo#2753]
```
../sirepo/job_driver/__init__.py:263:_agent_start LocalDriver(a=lWtQ k=sequential u=ncOc [_Op(run, y2cY)]) error=cannot process flags argument with a compiled pattern stack=Traceback (most recent call last):
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/job_driver/__init__.py", line 261, in _agent_start
    await self._do_agent_start(op)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/job_driver/local.py", line 115, in _do_agent_start
    cmd, stdin, env = self._agent_cmd_stdin_env(cwd=self._agent_exec_dir)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/job_driver/__init__.py", line 205, in _agent_cmd_stdin_env
    env=self._agent_env(),
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/job_driver/__init__.py", line 222, in _agent_env
    uid=self.uid,
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/job.py", line 176, in agent_env
    exclude_re=pykern.pkdebug.SECRETS_RE,
  File "/home/vagrant/src/radiasoft/pykern/pykern/pkconfig.py", line 493, in to_environ
    e = re.compile(exclude_re, flags=re.IGNORECASE)
  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/re.py", line 234, in compile
    return _compile(pattern, flags)
  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/re.py", line 282, in _compile
    "cannot process flags argument with a compiled pattern")
ValueError: cannot process flags argument with a compiled pattern
```

**Comment by e-carlin** [comment]
pykern git pull solved it.

**Comment by robnagler** [comment]
Should I always comment when pykern needs updating?

**Comment by e-carlin** [comment]
No need. Pulling pykern was my first stop so I wasn't down for long. I'll just do that before opening issues in the future.
