### ISSUE TITLE
Import error of h5py in radiasoft/sirepo:beta Docker

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#2761]
```py
$ docker run -it --rm -e SIREPO_AUTH_METHODS=bluesky:guest -e SIREPO_AUTH_BLUESKY_SECRET=bluesky -e SIREPO_SRDB_ROOT=/sirepo -e SIREPO_COOKIE_IS_SECURE=false -p 8000:8000 -v $HOME/sirepo_srdb_root:/sirepo radiasoft/sirepo:beta bash -c "/home/vagrant/.pyenv/shims/sirepo service http"
Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/py3/bin/sirepo", line 8, in <module>
    sys.exit(main())
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/sirepo_console.py", line 18, in main
    return pkcli.main('sirepo')
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/pykern/pkcli/__init__.py", line 108, in main
    res = argh.dispatch(parser, argv=argv)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/pkcli/service.py", line 104, in http
    with pkio.save_chdir(_run_dir()), \
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/pkcli/service.py", line 193, in _run_dir
    from sirepo import server
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/server.py", line 35, in <module>
    import h5py
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/h5py/__init__.py", line 34, in <module>
    from . import version
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/h5py/version.py", line 17, in <module>
    from . import h5 as _h5
  File "h5py/h5.pyx", line 1, in init h5py.h5
ImportError: /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/h5py/defs.cpython-37m-x86_64-linux-gnu.so: undefined symbol: H5Pget_dxpl_mpio
```

**Comment by robnagler** [comment]
The problem is that the environment is not fully set up. This worked for me:

```sh
$ docker run -it --rm -e SIREPO_AUTH_METHODS=bluesky:guest -e SIREPO_AUTH_BLUESKY_SECRET=bluesky -e SIREPO_SRDB_ROOT=/sirepo -e SIREPO_COOKIE_IS_SECURE=false -p 8000:8000 -v $HOME/sirepo_srdb_root:/sirepo radiasoft/sirepo:beta bash -l -c 'sirepo service http'
```

#2762 will fix the default command to work properly so you won't need to supply the bash command.

**Comment by mrakitin** [comment]
Thanks Rob! I didn't know about the `-l` option (Make bash act as if it had been invoked as a login shell). That makes sense to pick up all available env vars.

This exact problem is solved. How about the result? All widgets are displaying "no reply" message:
![image](https://user-images.githubusercontent.com/13209176/89778351-59f2d180-dadb-11ea-8939-d9104db5f28c.png)

Is something else expected to run? Here is a part of the server log (expandable):
<details>

```py
172.17.0.1 - - [10/Aug/2020 11:28:58] "POST /run-status HTTP/1.1" 200 -
/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_api.py:202:_request api=api_runSimulation runDir=/sirepo/user/McyjkNnm/srw/vdjEjXc5/powerDensityReport
/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_supervisor.py:329:receive ServerReq(api_runSimulation, McyjkNnm-vdjEjXc5-powerDensityReport)
/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_supervisor.py:917:__init__ _Op(run, ibaZ) runDir=/sirepo/user/McyjkNnm/srw/vdjEjXc5/powerDensityReport
/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_driver/__init__.py:182:send LocalDriver(a=pmkJ k=sequential u=Mcyj [_Op(run, ibaZ)]) _Op(run, ibaZ) runDir=/sirepo/user/McyjkNnm/srw/vdjEjXc5/powerDensityReport
Aug 10 11:28:58   363     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/pkcli/job_agent.py:232:_op opName=run o=ibaZ runDir=/sirepo/user/McyjkNnm/srw/vdjEjXc5/powerDensityReport
172.17.0.1 - - [10/Aug/2020 11:28:58] "POST /run-simulation HTTP/1.1" 200 -
/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_supervisor.py:954:reply_get _Op(run, ibaZ) await _reply_q.get()
/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_driver/__init__.py:290:_receive LocalDriver(a=pmkJ k=sequential u=Mcyj [_Op(run, ibaZ)]) opName=run o=ibaZ
Aug 10 11:28:58   363     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/pkcli/job_agent.py:821:start cmd=('/bin/bash', '-l') stdin=b"source $HOME/.bashrc
set -e
mkdir -p '.'
cd '.'
export SIREPO_MPI_CORES='1'
export SIREPO_SIM_DATA_LIB_FILE_URI='http://127.0.0.1:8001/job-cmd-lib-file/jRDhnyuX9XMxy8u8RQrpJufnlr3nwUtF/'
export SIREPO_SIM_DATA_LIB_FILE_LIST='/sirepo/user/McyjkNnm/srw/vdjEjXc5/powerDensityReport/sirepo-lib-file-list.txt'
export PYKERN_PKCONFIG_CHANNEL='dev'
export PYKERN_PKDEBUG_WANT_PID_TIME='1'
export PYTHONPATH=''
export PYTHONSTARTUP=''
export PYTHONUNBUFFERED='1'
export SIREPO_AUTH_LOGGED_IN_USER='McyjkNnm'
export SIREPO_JOB_VERIFY_TLS='False'
export SIREPO_JOB_MAX_MESSAGE_BYTES='200000000'
export SIREPO_JOB_PING_INTERVAL_SECS='120'
export SIREPO_JOB_PING_TIMEOUT_SECS='240'
export SIREPO_SRDB_ROOT='/sirepo'
exec 'sirepo' 'job_cmd' '/sirepo/user/McyjkNnm/srw/vdjEjXc5/powerDensityReport/in-VU1oKFDWCKhGzogB5RD5e0sBSaCUyuBf.json'
"
/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_supervisor.py:954:reply_get _Op(run, ibaZ) await _reply_q.get()
/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_api.py:202:_request api=api_runStatus runDir=/sirepo/user/McyjkNnm/srw/vdjEjXc5/powerDensityReport
172.17.0.1 - - [10/Aug/2020 11:28:59] "POST /run-status HTTP/1.1" 200 -
/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_api.py:202:_request api=api_runStatus runDir=/sirepo/user/McyjkNnm/srw/vdjEjXc5/powerDensityReport
172.17.0.1 - - [10/Aug/2020 11:29:00] "POST /run-status HTTP/1.1" 200 -
/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_api.py:202:_request api=api_runStatus runDir=/sirepo/user/McyjkNnm/srw/vdjEjXc5/powerDensityReport
172.17.0.1 - - [10/Aug/2020 11:29:01] "POST /run-status HTTP/1.1" 200 -
/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_api.py:202:_request api=api_runStatus runDir=/sirepo/user/McyjkNnm/srw/vdjEjXc5/powerDensityReport
172.17.0.1 - - [10/Aug/2020 11:29:02] "POST /run-status HTTP/1.1" 200 -
/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_driver/__init__.py:290:_receive LocalDriver(a=pmkJ k=sequential u=Mcyj [_Op(run, ibaZ)]) opName=run o=ibaZ
/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_api.py:202:_request api=api_runStatus runDir=/sirepo/user/McyjkNnm/srw/vdjEjXc5/powerDensityReport
/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_supervisor.py:917:__init__ _Op(analysis, OBqo) runDir=/sirepo/user/McyjkNnm/srw/vdjEjXc5/powerDensityReport
/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_driver/__init__.py:182:send LocalDriver(a=pmkJ k=sequential u=Mcyj [_Op(analysis, OBqo)]) _Op(analysis, OBqo) runDir=/sirepo/user/McyjkNnm/srw/vdjEjXc5/powerDensityReport
Aug 10 11:29:03   363     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/pkcli/job_agent.py:232:_op opName=analysis o=OBqo runDir=/sirepo/user/McyjkNnm/srw/vdjEjXc5/powerDensityReport
/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_supervisor.py:954:reply_get _Op(analysis, OBqo) await _reply_q.get()
Aug 10 11:29:03   363     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/pkcli/job_agent.py:243:_op opName=analysis o=OBqo exception=[Errno 36] File name too long stack=Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/pkcli/job_agent.py", line 234, in _op
    return await getattr(self, '_op_' + m.opName)(m)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/pkcli/job_agent.py", line 248, in _op_analysis
    return await self._cmd(msg)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/pkcli/job_agent.py", line 275, in _cmd
    return await self._fastcgi_op(msg)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/pkcli/job_agent.py", line 346, in _fastcgi_op
    tornado.netutil.bind_unix_socket(self._fastcgi_file),
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/tornado/netutil.py", line 214, in bind_unix_socket
    sock.bind(file)
OSError: [Errno 36] File name too long

Exception was printed at:

OSError: [Errno 36] File name too long
  File "/home/vagrant/.pyenv/versions/py3/bin/sirepo", line 8, in <module>
    sys.exit(main())
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/sirepo_console.py", line 18, in main
    return pkcli.main('sirepo')
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/pykern/pkcli/__init__.py", line 108, in main
    res = argh.dispatch(parser, argv=argv)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/pkcli/job_agent.py", line 74, in start
    i.start()
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/tornado/platform/asyncio.py", line 149, in start
    self.asyncio_loop.run_forever()
  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/asyncio/base_events.py", line 539, in run_forever
    self._run_once()
  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/asyncio/base_events.py", line 1775, in _run_once
    handle._run()
  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/pkcli/job_agent.py", line 189, in loop
    s = await self._op(r)
/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_driver/__init__.py:285:_receive LocalDriver(a=pmkJ k=sequential u=Mcyj [_Op(analysis, OBqo)]) error msg={'agentId': 'pmkJBN7bdLzX1QT7tfeaKnIOmz5eOquO', 'error': 'exception=[Errno 36] File name too long', 'opId': 'OBqoqEJ5pNYKoLuPTTv41ymLddHYrkPt', 'opName': 'error', 'stack': 'Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/pkcli/job_agent.py", line 234, in _op
    return await getattr(self, '_op_' + m.opName)(m)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/pkcli/job_agent.py", line 248, in _op_analysis
    return await self._cmd(msg)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/pkcli/job_agent.py", line 275, in _cmd
    return await self._fastcgi_op(msg)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/pkcli/job_agent.py", line 346, in _fastcgi_op
    tornado.netutil.bind_unix_socket(self._fastcgi_file),
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/tornado/netutil.py", line 214, in bind_unix_socket
    sock.bind(file)
OSError: [Errno 36] File name too long
```
</details>

**Comment by robnagler** [comment]
It's complaining about `File name too long` on Unix domain socket, which is being opened in the current directory with the name `job_cmd_fastcgi.sock`. 

Is this running on Windows? Running inside a VM? I couldn't find anything obvious on the web about this. It's using the unix domain socket internally to the container.

**Comment by mrakitin** [comment]
I am running it on my mac with Docker for Mac. Maybe it's due to the way I mount volumes?

**Comment by mrakitin** [comment]
I excluded the `-v` option and it seems to work!
```
$ docker run -it --rm -e SIREPO_AUTH_METHODS=bluesky:guest -e SIREPO_AUTH_BLUESKY_SECRET=bluesky -e SIREPO_SRDB_ROOT=/sirepo -e SIREPO_COOKIE_IS_SECURE=false -p 8000:8000 radiasoft/sirepo:beta bash -l -c "sirepo service http"
```

Maybe it's something in my old `sirepo_srdb_root` which I was mounting. Anything I can check in this dir?

**Comment by robnagler** [comment]
It's likely a bug in the fact that you can't create a bind socket on a mounted volume on a Mac. I added #2766 to fix this. Unfortunately, there's no easy work around.

**Comment by mrakitin** [comment]
Thank you! This issue is resolved.
