### ISSUE TITLE
SRW - mirror report error for LCLS simplified example

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#285]
I got a height profile file from Jacek ([1300eV.dat.txt](https://github.com/radiasoft/sirepo/files/416122/1300eV.dat.txt)), and when I try to visualize the corresponding data after uploading it to the LCLS simplified example, there is an error:
![error](https://cloud.githubusercontent.com/assets/13209176/17636297/3f20daf0-60aa-11e6-87b5-5537b37249e8.png)

In server log:
```python
../sirepo/server.py:937:run_and_read Error: cmd=['sirepo', u'srw', 'run', '/home/vagrant/src/radiasoft/sirepo/run/user/ItiHIOw5/srw/t6j6nGZv/mirrorReport'], returncode=1
../sirepo/server.py:358:app_run error: sid=t6j6nGZv, dir=/home/vagrant/src/radiasoft/sirepo/run/user/ItiHIOw5/srw/t6j6nGZv/mirrorReport, out=Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/2.7.10/bin/sirepo", line 9, in <module>
    load_entry_point('sirepo', 'console_scripts', 'sirepo')()
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/sirepo_console.py", line 18, in main
    return pkcli.main('sirepo')
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/pykern/pkcli/__init__.py", line 131, in main
    argh.dispatch(parser, argv=argv)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/pkcli/srw.py", line 45, in run
    _run_srw()
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/pkcli/srw.py", line 120, in _run_srw
    _process_output(_mirror_plot(data), data)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/pkcli/srw.py", line 75, in _mirror_plot
    mirror = model_data['models']['mirrorReport']
KeyError: 'mirrorReport'

Error: simulation failed
```

**Comment by mrakitin** [comment]
Assigned it to Paul since he has already implemented the fix. Thank Paul! I'll check the fix and close the issue if there is no problem with it.

**Comment by mrakitin** [comment]
Thanks Paul, there is no such errors anymore. I observe another issue with the `mirrorReport` key, but it's a separate minor issue and I created a ticket for it - #290.
