### ISSUE TITLE
tests/nginx_uwsgi_test.py failed during alpha build

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#2858]
```txt
^[[0m FAIL tests/nginx_uwsgi_test.log
too many failures=1 aborting
============================= test session starts ==============================
platform linux -- Python 3.7.2, pytest-6.0.1, py-1.9.0, pluggy-0.13.1 -- /home/vagrant/.pyenv/versions/3.7.2/envs/py3/bin/python
cachedir: .pytest_cache
rootdir: /rscontainers/sirepo
collecting ... collected 1 item

tests/nginx_uwsgi_test.py::test_ping Aug 25 22:00:02 12757     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_driver/__\
init__.py:382:init modules=['local']
nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)
2020/08/25 22:00:02 [warn] 12922#0: could not build optimal types_hash, you should increase either types_hash_max_size: 2048 or types_hash_bucket_size: 64; ig\
noring types_hash_bucket_size
Aug 25 22:00:02 12757     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/pkcli/job_supervisor.py:63:default_command ip=127.\
0.0.1 port=8002
[uWSGI] getting YAML configuration from /rscontainers/sirepo/tests/nginx_uwsgi_work/db/uwsgi.yml
*** Starting uWSGI 2.0.19.1 (64bit) on [Tue Aug 25 22:00:02 2020] ***
compiled with version: 8.3.1 20190223 (Red Hat 8.3.1-2) on 25 August 2020 21:55:02
os: Linux-3.10.0-1062.12.1.el7.x86_64 #1 SMP Tue Feb 4 23:02:59 UTC 2020
nodename: fnl1b.bivio.biz
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 40
current working directory: /rscontainers/sirepo/tests/nginx_uwsgi_work/db
writing pidfile to /rscontainers/sirepo/tests/nginx_uwsgi_work/db/uwsgi.pid
detected binary path: /home/vagrant/.pyenv/versions/3.7.2/envs/py3/bin/uwsgi
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:8003 fd 3
Python version: 3.7.2 (default, Aug 25 2020, 21:05:48)  [GCC 8.3.1 20190223 (Red Hat 8.3.1-2)]
Python main interpreter initialized at 0xe94a60
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 334048 bytes (326 KB) for 10 cores
*** Operational MODE: threaded ***
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0xe94a60 pid: 12924 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 12924)
spawned uWSGI worker 1 (pid: 12966, cores: 10)
*** Stats server enabled on /rscontainers/sirepo/tests/nginx_uwsgi_work/db/uwsgi.sock fd: 10 ***
ERROR
==================================== ERRORS ====================================
_________________________ ERROR at setup of test_ping __________________________
Traceback (most recent call last):
  File "/rscontainers/sirepo/tests/conftest.py", line 369, in _subprocess_start
    r = c.sr_post('jobSupervisorPing', PKDict(simulationType=sirepo.srunit.SR_SIM_TYPE_DEFAULT))
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/srunit.py", line 152, in sr_post
    r.raise_for_status()
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: http://0.0.0.0:8080/job-supervisor-ping

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/rscontainers/sirepo/tests/conftest.py", line 182, in uwsgi_module
    with _auth_client_module(request, uwsgi=True) as c:
  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/rscontainers/sirepo/tests/conftest.py", line 213, in _auth_client_module
    with _subprocess_start(request, cfg=cfg, uwsgi=uwsgi) as c:
  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/rscontainers/sirepo/tests/conftest.py", line 384, in _subprocess_start
    x.wait()
  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/subprocess.py", line 990, in wait
    return self._wait(timeout=timeout)
  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/subprocess.py", line 1624, in _wait
    (pid, sts) = self._try_wait(0)
  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/subprocess.py", line 1582, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
  File "/rscontainers/sirepo/tests/conftest.py", line 146, in _timeout
    pkunit.pkfail('MAX_CASE_RUN_SECS={} exceeded', MAX_CASE_RUN_SECS)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/pykern/pkunit.py", line 230, in pkfail
    raise PKFail('{} {}'.format(call, msg))
pykern.pkunit.PKFail: tests/conftest.py:146:_timeout MAX_CASE_RUN_SECS=120 exceeded
```

**Comment by robnagler** [comment]
Can't reproduce locally, going to try again

**Comment by robnagler** [comment]
Spurious. Didn't happen again.
