### ISSUE TITLE
SRW - errors in the server log

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#286]
Sometimes this kind of errors appear in the server log:

``` python
10.0.2.2 - - [12/Aug/2016 20:44:00] "POST /run HTTP/1.1" 200 -
../sirepo/server.py:937:run_and_read Error: cmd=['sirepo', u'srw', 'run', '/home/vagrant/src/radiasoft/sirepo/run/user/ItiHIOw5/srw/KvIqgGl3/watchpointReport3'], returncode=1
../sirepo/server.py:358:app_run error: sid=KvIqgGl3, dir=/home/vagrant/src/radiasoft/sirepo/run/user/ItiHIOw5/srw/KvIqgGl3/watchpointReport3, out=Single-electron SR calculatiton ... completed (lasted 6.437994 s)
Extracting intensity and saving it to a file ... Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/2.7.10/bin/sirepo", line 9, in <module>
    load_entry_point('sirepo', 'console_scripts', 'sirepo')()
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/sirepo_console.py", line 18, in main
    return pkcli.main('sirepo')
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/pykern/pkcli/__init__.py", line 131, in main
    argh.dispatch(parser, argv=argv)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/pkcli/srw.py", line 45, in run
    _run_srw()
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/pkcli/srw.py", line 130, in _run_srw
    srwl_bl.SRWLBeamline(_name=v.name, _mag_approx=mag).calc_all(v, op)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/srwl_bl.py", line 1061, in calc_all
    _fname = os.path.join(_v.fdir, _v.si_fn) if(len(_v.si_fn) > 0) else '')
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/srwl_bl.py", line 421, in calc_sr_se
    if(len(_fname) > 0): srwl_uti_save_intens_ascii(arI, wfr.mesh, _fname, 0, ['Photon Energy', 'Horizontal Position', 'Vertical Position', ''], _arUnits=['eV', 'm', 'm', 'ph/s/.1%bw/mm^2'])
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/srwlib.py", line 3412, in srwl_uti_save_intens_ascii
    f = open(_file_path, 'w')
IOError: [Errno 2] No such file or directory: 'res_int_se.dat'

Error: simulation failed
```

**Comment by mrakitin** [comment]
I don't observe the issues anymore.
