### ISSUE TITLE
rename beam line while calculating

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#29]
demo20 was being used. User changed the beamline name after making a copy while SRW was running. It seems to have screwed up the library. I renamed the directory to demo20-20151002

[2015-10-02 15:37:41,695] {/home/vagrant/.pyenv/versions/src/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py:1423} ERROR - Exception on /srw/run [POST]
Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/src/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vagrant/.pyenv/versions/src/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vagrant/.pyenv/versions/src/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/.pyenv/versions/src/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vagrant/.pyenv/versions/src/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/server.py", line 154, in srw_run
    with open('out.json') as f:
IOError: [Errno 2] No such file or directory: 'out.json'
[2015-10-02 15:39:54,505] {/home/vagrant/.pyenv/versions/src/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py:1423} ERROR - Exception on /srw/run [POST]
Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/src/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vagrant/.pyenv/versions/src/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vagrant/.pyenv/versions/src/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/.pyenv/versions/src/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vagrant/.pyenv/versions/src/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/server.py", line 154, in srw_run
    with open('out.json') as f:
IOError: [Errno 2] No such file or directory: 'out.json'

**Comment by bruhwile** [comment]
This may have been fixed.
Closing for now, as it has not been a problem.
