### ISSUE TITLE
flask crashes hard with new db and test_http

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#2933]
Flask just exits with status=0:

```txt
$ rm -rf run
$ bash etc/run-auth-email.sh
bash etc/run-auth-email.sh
Sep 09 20:58:54  9155     0 ../sirepo/job_driver/__init__.py:382:init modules=['local']
Sep 09 20:58:54  9155     0 ../sirepo/pkcli/job_supervisor.py:63:default_command ip=127.0.0.1 port=8001
 * Serving Flask app "sirepo.server" (lazy loading)
 * Environment: development
 * Debug mode: off
 * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
 * Restarting with stat
127.0.0.1 - - [09/Sep/2020 20:58:58] "POST /simulation-list HTTP/1.1" 200 -
127.0.0.1 - - [09/Sep/2020 20:58:58] "POST /simulation-list HTTP/1.1" 200 -
127.0.0.1 - - [09/Sep/2020 20:58:58] "POST /simulation-list HTTP/1.1" 200 -
Sep 09 20:58:58  9313     6 ../sirepo/auth/__init__.py:398:require_user user not logged in: logged out uid=None
Sep 09 20:58:58  9313     7 ../sirepo/auth/__init__.py:398:require_user user not logged in: logged out uid=None
Sep 09 20:58:58  9313     5 ../sirepo/auth/__init__.py:398:require_user user not logged in: logged out uid=None
127.0.0.1 - - [09/Sep/2020 20:58:58] "POST /simulation-list HTTP/1.1" 200 -
127.0.0.1 - - [09/Sep/2020 20:58:58] "POST /simulation-list HTTP/1.1" 200 -
127.0.0.1 - - [09/Sep/2020 20:58:58] "POST /simulation-list HTTP/1.1" 200 -
Sep 09 20:58:58  9313     8 ../sirepo/auth/email.py:178:_send_login_email http://0.0.0.0:8000/auth-email-authorized/elegant/MPRA4VNG34XDYDO4
127.0.0.1 - - [09/Sep/2020 20:58:58] "POST /auth-email-login HTTP/1.1" 200 -
Sep 09 20:58:58  9313     9 ../sirepo/auth/email.py:178:_send_login_email http://0.0.0.0:8000/auth-email-authorized/elegant/4N37BQR5NEJTRGUG
127.0.0.1 - - [09/Sep/2020 20:58:58] "POST /auth-email-login HTTP/1.1" 200 -
```

The client only gets a few requests in:

```txt
$ sirepo test_http
sirepo/pkcli/test_http.py:340:_timer http://0.0.0.0:8000/simulation-list _Client(email=three@radia.run) elapsed_time=0.04241633415222168
sirepo/pkcli/test_http.py:340:_timer http://0.0.0.0:8000/simulation-list _Client(email=two@radia.run) elapsed_time=0.04286050796508789
sirepo/pkcli/test_http.py:340:_timer http://0.0.0.0:8000/simulation-list _Client(email=one@radia.run) elapsed_time=0.05365324020385742
sirepo/pkcli/test_http.py:340:_timer http://0.0.0.0:8000/simulation-list _Client(email=one@radia.run) elapsed_time=0.013828039169311523
sirepo/pkcli/test_http.py:340:_timer http://0.0.0.0:8000/simulation-list _Client(email=three@radia.run) elapsed_time=0.026341676712036133
sirepo/pkcli/test_http.py:340:_timer http://0.0.0.0:8000/simulation-list _Client(email=two@radia.run) elapsed_time=0.03794980049133301
sirepo/pkcli/test_http.py:340:_timer http://0.0.0.0:8000/auth-email-login _Client(email=one@radia.run) elapsed_time=0.021625518798828125
sirepo/pkcli/test_http.py:340:_timer http://0.0.0.0:8000/auth-email-login _Client(email=three@radia.run) elapsed_time=0.02888035774230957
sirepo/pkcli/test_http.py:143:_run error=Stream closed stack=Traceback (most recent call last):
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/pkcli/test_http.py", line 134, in _run
    s = await _sims_tasks()
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/pkcli/test_http.py", line 148, in _sims_tasks
    for a in await _apps():
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/pkcli/test_http.py", line 113, in _apps
    for c in await _clients():
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/pkcli/test_http.py", line 123, in _clients
    return await asyncio.gather(*[_Client(u).login() for u in cfg.emails])
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/pkcli/test_http.py", line 263, in login
    self,
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/pkcli/test_http.py", line 320, in post
    **self._fetch_default_args()
tornado.simple_httpclient.HTTPStreamClosedError: Stream closed
```

**Comment by robnagler** [comment]
No longer fails.
