### ISSUE TITLE
WARP - bad report

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#313]
I just occasionally tried to open WARP page of Sirepo, and noticed the following problem:
```python
Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/2.7.10/bin/sirepo", line 9, in <module>
    load_entry_point('sirepo', 'console_scripts', 'sirepo')()
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/sirepo_console.py", line 18, in main
    return pkcli.main('sirepo')
  File "/home/vagrant/src/radiasoft/pykern/pykern/pkcli/__init__.py", line 131, in main
    argh.dispatch(parser, argv=argv)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/pkcli/warp.py", line 37, in run
    res = template.extract_particle_report([model['x'], model['y'], model['histogramBins']], 'beam', cfg_dir, data_file)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/template/warp.py", line 117, in extract_particle_report
    data_list.append(main.read_species_data(f, particle_type, 'w', ()))
AttributeError: 'module' object has no attribute 'read_species_data'
```
![warp](https://cloud.githubusercontent.com/assets/13209176/17824359/7905fe46-662f-11e6-8396-380488ee090c.png)

Is it because of the recent changes in the code?

**Comment by robnagler** [comment]
You need to update warp (as vagrant):

curl radia.run | bash -s code warp

Rob

**Comment by mrakitin** [comment]
Thanks Rob. I got this error during install:
```bash
RuntimeError: module compiled against API version 0xa but this version of numpy is 0x9
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    import opmd_viewer  # In order to extract the version number
  File "/var/tmp/install-10855-14727/codes-openPMD-1000-30645/openPMD-viewer/opmd_viewer/__init__.py", line 9, in <module>
    from .openpmd_timeseries import OpenPMDTimeSeries, FieldMetaInformation
  File "/var/tmp/install-10855-14727/codes-openPMD-1000-30645/openPMD-viewer/opmd_viewer/openpmd_timeseries/__init__.py", line 2, in <module>
    from .main import OpenPMDTimeSeries
  File "/var/tmp/install-10855-14727/codes-openPMD-1000-30645/openPMD-viewer/opmd_viewer/openpmd_timeseries/main.py", line 15, in <module>
    from .plotter import Plotter
  File "/var/tmp/install-10855-14727/codes-openPMD-1000-30645/openPMD-viewer/opmd_viewer/openpmd_timeseries/plotter.py", line 12, in <module>
    import matplotlib.pyplot as plt
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/matplotlib/pyplot.py", line 29, in <module>
    import matplotlib.colorbar
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/matplotlib/colorbar.py", line 32, in <module>
    import matplotlib.artist as martist
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/matplotlib/artist.py", line 14, in <module>
    from .transforms import (Bbox, IdentityTransform, TransformedBbox,
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/matplotlib/transforms.py", line 39, in <module>
    from matplotlib._path import (affine_transform, count_bboxes_overlapping_bbox,
ImportError: numpy.core.multiarray failed to import
2016-08-24T18:51:17Z install_main
2016-08-24T18:51:17Z curl -L -s -S https://raw.githubusercontent.com/radiasoft/download/master/installers/code/radiasoft-download.sh
Unexpected error; Install failed.
If you don't know what to do, please contact support@radiasoft.net.
```

**Comment by robnagler** [comment]
You need to revert to numpy 1.9.3. See

pip install -U numpy==1.9.3

Then run it again.

Rob

**Comment by mrakitin** [comment]
That's getting really strange, I already have NumPy 1.9.3:
```python
[2.7.10;@rs sirepo]$ python
Python 2.7.10 (default, Nov 20 2015, 13:25:19)
[GCC 4.9.2 20150212 (Red Hat 4.9.2-6)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> numpy
<module 'numpy' from '/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/numpy/__init__.pyc'>
>>> numpy.__version__
'1.9.3'
>>>
```
I tried to remove it and then install from scratch, but it did not work - still getting the same error.

**Comment by robnagler** [comment]
Let's debug tomorrow. What's your schedule?

**Comment by mrakitin** [comment]
Sounds good. I'm available till noon EST.

**Comment by robnagler** [comment]
I'll Skype at 11a EDT.
