### ISSUE TITLE
SRW - calculations not running after copying simulation with tabulated undulator or custom height profiles

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#321]
I copied a simulation with the uploaded magnetic measurements .zip file (which is not in the list of predefined files), the status of reports never changed, and there is the following error in the log:
```python
10.0.2.2 - - [25/Aug/2016 21:33:41] "POST /run-simulation HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/beaker/middleware.py", line 155, in __call__
    return self.wrap_app(environ, session_start_response)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/server.py", line 386, in app_run_simulation
    _start_simulation(data)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/server.py", line 748, in _start_simulation
    cfg.job_queue(data)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/server.py", line 905, in __init__
    self.cmd, self.run_dir = simulation_db.prepare_simulation(data)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/simulation_db.py", line 304, in prepare_simulation
    template.prepare_aux_files(run_dir, data)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/template/srw.py", line 583, in prepare_aux_files
    zip_file = zipfile.ZipFile(str(filepath))
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/zipfile.py", line 756, in __init__
    self.fp = open(file, modeDict[mode])
IOError: [Errno 2] No such file or directory: '/home/vagrant/src/radiasoft/sirepo/run/user/lNCNbdHT/srw/c5U5Mm04/sourceIntensityReport/magn_meas.zip'
../sirepo/server.py:199:app_error_logging 10.0.2.2: javascript error: {
    "cause": "",
    "message": "TypeError: can't assign to properties of (new String(\"<!DOCTYPE HTML PUBLIC \\\"-//W3C//DTD HTML 4.01 Transitional//EN\\\"\\n  \\\"http://www.w3.org/TR/html4/loose.dtd\\\">\\n<html>\\n  <head>\\n    <title>IOError: [Errno 2] No such file or directory: '/home/vagrant/src/radiasoft/sirepo/run/user/lNCNbdHT/srw/c5U5Mm04/sourceIntensityReport/magn_meas.zip' // Werkzeug Debugger</title>\\n    <link rel=\\\"stylesheet\\\" href=\\\"?__debugger__=yes&amp;cmd=resource&amp;f=style.css\\\"\\n        type=\\\"text/css\\\">\\n    <!-- We need to make sure this has a favicon so that the debugger does\\n         not by accident trigger a request to /favicon.ico which might\\n         change the application state. -->\\n    <link rel=\\\"shortcut icon\\\"\\n        href=\\\"?__debugger__=yes&amp;cmd=resource&amp;f=console.png\\\">\\n    <script src=\\\"?__debugger__=yes&amp;cmd=resource&amp;f=jquery.js\\\"></script>\\n    <script src=\\\"?__debugger__=yes&amp;cmd=resource&amp;f=debugger.js\\\"></script>\\n    <script type=\\\"text/javascript\\\">\\n      var TRACEBACK = 140396405788304,\\n          CONSOLE_MODE = false,\\n          EVALEX = true,\\n          EVALEX_TRUSTED = false,\\n          SECRET = \\\"xKqwN1Ta1iLO2Za5w9PH\\\";\\n    </script>\\n  </head>\\n  <body>\\n    <div class=\\\"debugger\\\">\\n<h1>IOError</h1>\\n<div class=\\\"detail\\\">\\n  <p class=\\\"errormsg\\\">IOError: [Errno 2] No such file or directory: '/home/vagrant/src/radiasoft/sirepo/run/user/lNCNbdHT/srw/c5U5Mm04/sourceIntensityReport/magn_meas.zip'</p>\\n</div>\\n<h2 class=\\\"traceback\\\">Traceback <em>(most recent call last)</em></h2>\\n<div class=\\\"traceback\\\">\\n  \\n  <ul><li><div class=\\\"frame\\\" id=\\\"frame-140396405887056\\\">\\n  <h4>File <cite class=\\\"filename\\\">\\\"/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py\\\"</cite>,\\n      line <em class=\\\"line\\\">2000</em>,\\n      in <code class=\\\"function\\\">__call__</code></h4>\\n  <div class=\\\"source\\\"><pre class=\\\"line before\\\"><span ....
```

**Comment by mrakitin** [comment]
Any related `.dat` files are not copies neither.

**Comment by mrakitin** [comment]
Thanks a lot Paul! I'll check how the fix works.
