### ISSUE TITLE
tests/nginx_uwsgi_test.py failing intermittently on alpha builds

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#3248]
something is happening that causes this test to fail more frequently on alpha builds.

```txt
2020/12/17 15:46:46 [warn] 12897#0: could not build optimal types_hash, you should increase either types_hash_max_size: 2048 or types_hash_bucket_size: 64; ignoring types_hash_bucket_size
[uWSGI] getting YAML configuration from /rscontainers/sirepo/tests/nginx_uwsgi_work/db/uwsgi.yml
*** Starting uWSGI 2.0.19.1 (64bit) on [Thu Dec 17 15:46:46 2020] ***
compiled with version: 8.3.1 20190223 (Red Hat 8.3.1-2) on 17 December 2020 15:41:46
os: Linux-3.10.0-1062.12.1.el7.x86_64 #1 SMP Tue Feb 4 23:02:59 UTC 2020
nodename: fnl1b.bivio.biz
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 40
current working directory: /rscontainers/sirepo/tests/nginx_uwsgi_work/db
writing pidfile to /rscontainers/sirepo/tests/nginx_uwsgi_work/db/uwsgi.pid
detected binary path: /home/vagrant/.pyenv/versions/3.7.2/envs/py3/bin/uwsgi
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:8102 fd 3
Python version: 3.7.2 (default, Nov  7 2020, 01:55:42)  [GCC 8.3.1 20190223 (Red Hat 8.3.1-2)]
Dec 17 15:46:46 12734     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_driver/__init__.py:382:init modules=['local']
Python main interpreter initialized at 0x1ed6ee0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 334048 bytes (326 KB) for 10 cores
*** Operational MODE: threaded ***
Dec 17 15:46:46 12734     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/pkcli/job_supervisor.py:63:default_command ip=127.0.0.1 port=8101
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x1ed6ee0 pid: 12899 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 12899)
spawned uWSGI worker 1 (pid: 12941, cores: 10)
*** Stats server enabled on /rscontainers/sirepo/tests/nginx_uwsgi_work/db/uwsgi.sock fd: 9 ***
ERROR

==================================== ERRORS ====================================
_________________________ ERROR at setup of test_ping __________________________
Traceback (most recent call last):
  File "/rscontainers/sirepo/tests/conftest.py", line 370, in _subprocess_start
    r = c.sr_post('jobSupervisorPing', PKDict(simulationType=sirepo.srunit.SR_SIM_TYPE_DEFAULT))
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/srunit.py", line 157, in sr_post
    r.raise_for_status()
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: http://0.0.0.0:8180/job-supervisor-ping

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/rscontainers/sirepo/tests/conftest.py", line 182, in uwsgi_module
    with _auth_client_module(request, uwsgi=True) as c:
  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/rscontainers/sirepo/tests/conftest.py", line 213, in _auth_client_module
    with _subprocess_start(request, cfg=cfg, uwsgi=uwsgi) as c:
  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/rscontainers/sirepo/tests/conftest.py", line 385, in _subprocess_start
    x.wait()
  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/subprocess.py", line 990, in wait
    return self._wait(timeout=timeout)
  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/subprocess.py", line 1624, in _wait
    (pid, sts) = self._try_wait(0)
  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/subprocess.py", line 1582, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
  File "/rscontainers/sirepo/tests/conftest.py", line 146, in _timeout
    pkunit.pkfail('MAX_CASE_RUN_SECS={} exceeded', MAX_CASE_RUN_SECS)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/pykern/pkunit.py", line 288, in pkfail
    raise PKFail('{} {}'.format(call, msg))
pykern.pkunit.PKFail: tests/conftest.py:146:_timeout MAX_CASE_RUN_SECS=120 exceeded
=============================== warnings summary ===============================
tests/nginx_uwsgi_test.py::test_ping
  /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/pykern/pkrunpy.py:10: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentat\
ion for alternative uses
    import imp

-- Docs: https://docs.pytest.org/en/stable/warnings.html
=================== 1 warning, 1 error in 120.27s (0:02:00) ====================
The command '/bin/sh -c "/rscontainers/build-run.sh"' returned a non-zero code: 1
```

**Comment by robnagler** [comment]
Seems to be fixed.
