### ISSUE TITLE
flash: Simulation library file "flash.tar.gz" does not exist

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#3338]
This is on alpha, after clicking Start Simulation on CapLaserBella.

```txt
00:05:40 sirepo/pkcli/job_cmd.py", line 50, in default_command
00:05:40 sirepo.template.import_module(msg.simulationType)
00:05:40 sirepo/pkcli/job_cmd.py", line 93, in _do_compute
00:05:40 _do_prepare_simulation(msg, template).cmd,
00:05:40 sirepo/pkcli/job_cmd.py", line 215, in _do_prepare_simulation
00:05:40 msg.runDir,
00:05:40 sirepo/simulation_db.py", line 468, in prepare_simulation
00:05:40 s.support_files_to_run_dir(data, run_dir)
00:05:40 sirepo/sim_data/__init__.py", line 523, in support_files_to_run_dir
00:05:40 cls.lib_files_to_run_dir(data, run_dir)
00:05:40 sirepo/sim_data/__init__.py", line 388, in lib_files_to_run_dir
00:05:40 s = cls.lib_file_abspath(b, data=data)
00:05:40 sirepo/sim_data/__init__.py", line 271, in lib_file_abspath
00:05:40 sirepo.auth.logged_in_user(),
00:05:40 sirepo.util.UserAlert: UserAlert(error=Simulation library file "flash.tar.gz" does not exist)
00:05:40 Exception was printed at:
00:05:40 sirepo.util.UserAlert: UserAlert(error=Simulation library file "flash.tar.gz" does not exist)
00:05:40 File "/home/vagrant/.pyenv/versions/py3/bin/sirepo", line 8, in <module>
00:05:40 sys.exit(main())
00:05:40 sirepo/sirepo_console.py", line 18, in main
00:05:40 return pkcli.main('sirepo')
00:05:40 pykern/pkcli/__init__.py", line 108, in main
00:05:40 res = argh.dispatch(parser, argv=argv)
00:05:40 argh/dispatching.py", line 174, in dispatch
00:05:40 for line in lines:
00:05:40 argh/dispatching.py", line 277, in _execute_command
00:05:40 for line in result:
00:05:40 argh/dispatching.py", line 260, in _call
00:05:40 result = function(*positional, **keywords)
00:05:40 ', 'state': 'error'}}
00:05:42 tornado/web.py:2243:log_request INFO:tornado.access:200 POST /job-api-request (<redact>) 1.81ms
```

**Comment by robnagler** [comment]
I think this is something I didn't do. I'll check.

**Comment by robnagler** [comment]
`lib_file_abspath basename=flash.tar.gz not in lib or resource directories uid=<snip>`

Is there a db upgrade that has to happen?

**Comment by robnagler** [comment]
There's a flash.rpm in the directory. I suspect this needs to be a db upgrade that runs at startup:

```sh
# bash ./start sirepo admin audit_proprietary_lib_files
Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/py3/bin/sirepo", line 8, in <module>
    sys.exit(main())
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/sirepo_console.py", line 18, in main
    return pkcli.main('sirepo')
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/pykern/pkcli/__init__.py", line 108, in main
    res = argh.dispatch(parser, argv=argv)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/pkcli/admin.py", line 43, in audit_proprietary_lib_files
    sirepo.auth_db.audit_proprietary_lib_files(u)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/auth_db.py", line 100, in audit_proprietary_lib_files
    _add(d, t, c)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/auth_db.py", line 83, in _add
    f'expecting simulation_lib_dir={l} to be empty'
AssertionError: expecting simulation_lib_dir=/srv/sirepo/db/user/4e7l3yaL/flash/lib
```

**Comment by robnagler** [comment]
Doesn't have to run at startup, because it's not something that needs to be atomic.

**Comment by e-carlin** [comment]
If you want a stop-gap you can run `sirepo admin audit-proprietary-lib-files <uid>` until I implement a fix.
