### ISSUE TITLE
Need better frame detection for SRW

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#338]
This stack trace happened on a cached state, that is, there was no process running. It may be related to #286.

``` text
10.10.10.1 - - [01/Sep/2016 00:40:38] "GET /simulation-frame/srw*f2i6ZOMH*fluxAnimation*1*1*1472688752 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/beaker/middleware.py", line 155, in __call__
    return self.wrap_app(environ, session_start_response)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/server.py", line 425, in app_simulation_frame
    response = _json_response(template.get_simulation_frame(run_dir, data, model_data))
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/template/srw.py", line 513, in get_simulation_frame
    return extract_report_data(str(run_dir.join(_DATA_FILE_FOR_MODEL[data['report']])), data)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/template/srw.py", line 145, in extract_report_data
    data, mode, allrange, arLabels, arUnits = uti_plot_com.file_load(filename)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/uti_plot_com.py", line 116, in file_load
    return _file_load(fname, read_labels)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/uti_plot_com.py", line 61, in _file_load
    ne, nx, ny = [int(hlp[i].replace('#','').split()[0]) for i in [3,6,9]]
IndexError: list index out of range
```

**Comment by mrakitin** [comment]
Sometimes I meet this error when I try to visualize data from SRW partially-coherent calculations by SRWLIB_ExampleViewDataFile.py and the file is being written at that time.

**Comment by robnagler** [comment]
This was a simulation I canceled so do you think the file got partially
written? If so, we should definitely fix the writing so that updates are
atomic. I'll look at it.

**Comment by mrakitin** [comment]
There is a chance it was partially written at that time.

**Comment by robnagler** [comment]
Right, That shouldn't happen. What should happen is a write to a temporary
file and a rename when the file write is complete.

**Comment by robnagler** [comment]
@moellep I suspect this isn't a problem any more, correct?

**Comment by moellep** [comment]
I haven't seen this problem in awhile, but I don't think there is any sort of locking to prevent a cancel simulation to occur at the same time SRW is writing to the output file.

**Comment by robnagler** [comment]
The concurrent write problem is a larger problem that won't be solved with locking.

Ideally, codes would write files properly, but they don't, so we can have all kinds of issues with partially written files. The solution is for Sirepo to be very robust in reading files. Every time we encounter an error like this, we have to fix the code to expect the data to be corrupt. 

There's no general fix, and this specific problem may have been fixed by @mrakitin when I mentioned proper file writing (write to temporary and rename).
