### ISSUE TITLE
warpvnd: error in lattice gate 3D execution

### ISSUE THREAD

**Issue by ncook882** [radiasoft/sirepo#3389]
Upon completing the simulation execution, the following error is given. The Impact Density and Particle Trace Reports are not produced.

![Screen Shot 2021-03-10 at 2 53 30 PM](https://user-images.githubusercontent.com/11053323/110704671-86c2b080-81b2-11eb-9763-52dfd0b17341.png)

Link to Simulation: https://beta2.sirepo.com/warpvnd#/visualization/QBuMmxcP

**Comment by moellep** [comment]
If you run the same simulation with Execution "Serial" it completes successfully. I noticed the field animation also fails for STL simulation when run in parallel mode. I'll create a simple python script which reproduces the problem.

**Comment by moellep** [comment]
Attached is a warp python script which crashes when run with a single CPU. I tested on sirepo dev and on jupyter - both result in a seg fault during the call to scipy_interp1d(). I'm guessing the bug isn't in scipy, but something else is corrupting memory prior to the call.

[warp-crash.zip](https://github.com/radiasoft/sirepo/files/6133483/warp-crash.zip)

**Comment by moellep** [comment]
Top of the gdb stack trace warp toppy:
```
#0  0x00007eff6ab7f686 in dtbsv_ ()
   from /home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/warp/toppy.cpython-37m-x86_64-linux-gnu.so
#1  0x00007eff6845ab81 in dgbtrs_ ()
   from /home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/scipy/special/../../scipy.libs/libopenblasp-r0-085ca
80a.3.9.so
```

**Comment by cchall** [comment]
I wouldn't claim to know what is really going on here, but moving the scipy.interpolate.interp1d before warp is imported seems to allow the script to complete successfully for me.

**Comment by moellep** [comment]
Thanks @cchall - that is a good work-around for now.

**Comment by ncook882** [comment]
I'm still seeing what appears to be slow performance and/or the simulation not completing at the final frame. @cchall are you seeing this as well?

https://www.sirepo.com/warpvnd#/visualization/DzjcEZit
