### ISSUE TITLE
Register jupyter users with pkcli

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#3407]
Supply an email address and it returns the jupyterhub user name created. If the user is already registered, just returns the jupyterhub user. This will allow us to register groups of people for classes in advance.

**Comment by robnagler** [comment]
@e-carlin let's bump the priority of this just to get it done before we forget. :)

**Comment by e-carlin** [comment]
Do you care about supporting migration of old jupyter.radiasoft.org users?

**Comment by robnagler** [comment]
No except assert if there is a user that looks similar (ie if local part matches github user name).

**Comment by e-carlin** [comment]
I think this work is bumping up against two persistent issues in sirepo: 1. when to supply uid vs when to use logged_in_user and 2. initialization. In some ways these issues are related. One initialization problem is dependency cycles and one of those cylcles is between auth and simulation_db. If we supplied uid to all functions in simulation_db then we wouldn't have to depend on auth and the cycle would be fixed. 

Here is the cycle: 
```python
sirepo (issue/3407-pkcli-jupyterhub-user)$ python x.py
Traceback (most recent call last):
  File "x.py", line 1, in <module>
    from sirepo import simulation_db
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/simulation_db.py", line 18, in <module>
    from sirepo.template import template_common
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/template/template_common.py", line 19, in <module>
    import sirepo.http_reply
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/http_reply.py", line 21, in <module>
    import sirepo.uri
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/uri.py", line 11, in <module>
    import sirepo.uri_router
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/uri_router.py", line 17, in <module>
    import sirepo.api_auth
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/api_auth.py", line 12, in <module>
    from sirepo import auth
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/auth/__init__.py", line 739, in <module>
    _init()
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/auth/__init__.py", line 623, in _init
    s = list(simulation_db.SCHEMA_COMMON.common.constants.paymentPlans.keys())
AttributeError: module 'sirepo.simulation_db' has no attribute 'SCHEMA_COMMON'
```

If we are going to initialize auth methods fully outside of flask I think we are going to need to fix this cycle. @robnagler when you have some time let's discuss solutions.
