### ISSUE TITLE
tests/nginx_uwsgi_test.py table auth_github_user_t already exists

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#3609]
During alpha build. I'm rerunning but it seems like there are two things running at once...

```txt
tests/nginx_uwsgi_test.py^[[91merror: FAILED=1 passed=32
^[[0m FAIL tests/nginx_uwsgi_test.log
too many failures=1 aborting
============================= test session starts ==============================
platform linux -- Python 3.7.2, pytest-6.2.3, py-1.10.0, pluggy-0.13.1 -- /home/vagrant/.pyenv/versions/3.7.2/envs/py3/bin/python
cachedir: .pytest_cache
rootdir: /rscontainers/sirepo
collecting ... collected 1 item

tests/nginx_uwsgi_test.py::test_ping Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1771, in _execute_context
    cursor, statement, parameters, context
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: table auth_github_user_t already exists
```

```txt
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/pkcli/job_supervisor.py", line 17, in <module>
    import sirepo.job_driver
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_driver/__init__.py", line 15, in <module>
    import sirepo.auth
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/auth/__init__.py", line 776, in <module>
    _init()
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/auth/__init__.py", line 646, in _init
    _init_full()
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/auth/__init__.py", line 656, in _init_full
    m = importlib.import_module(pkinspect.module_name_join((p, n)))
  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/auth/github.py", line 172, in <module>
    _init()
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/auth/github.py", line 169, in _init
    auth_db.init_model(_init_model)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/auth_db.py", line 254, in init_model
    UserDbBase.metadata.create_all(_engine)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 4745, in create_all
    ddl.SchemaGenerator, self, checkfirst=checkfirst, tables=tables
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3079, in _run_ddl_visitor
    conn._run_ddl_visitor(visitorcallable, element, **kwargs)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2081, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 485, in traverse_single
    return meth(obj, **kw)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 850, in visit_metadata
    _is_metadata_operation=True,
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 485, in traverse_single
    return meth(obj, **kw)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 895, in visit_table
    include_foreign_key_constraints,  # noqa
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1262, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 78, in _execute_on_connection
    self, multiparams, params, execution_options
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1358, in _execute_ddl
    compiled,
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1814, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1995, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1771, in _execute_context
    cursor, statement, parameters, context
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) table auth_github_user_t already exists
```

**Comment by robnagler** [comment]
This was a spurious error, but I think there must be something wrong for it to be happening. Perhaps two processes are creating the db?
