### ISSUE TITLE
corrupt server thread?

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#3727]
The server started not returning static files (last stack trace). This is probably the first error:

```txt
21:19:33 sirepo/uri_router.py:87:call_api api=<function api_staticFile at 0x7ff0823cef28> exception='REQUEST_METHOD' stack=Traceback (most recent call last):
21:19:33 sirepo/uri_router.py", line 79, in call_api
21:19:33 r = flask.make_response(f(**kwargs) if kwargs else f())
21:19:33 sirepo/server.py", line 570, in api_staticFile
21:19:33 return flask.send_file(p, conditional=True)
21:19:33 flask/helpers.py", line 625, in send_file
21:19:33 cache_timeout=cache_timeout,
21:19:33 werkzeug/utils.py", line 789, in send_file
21:19:33 rv = rv.make_conditional(environ, accept_ranges=True, complete_length=size)
21:19:33 werkzeug/wrappers/response.py", line 797, in make_conditional
21:19:33 if environ["REQUEST_METHOD"] in ("GET", "HEAD"):
21:19:33 KeyError: 'REQUEST_METHOD'
21:19:33 Exception was printed at:
21:19:33 KeyError: 'REQUEST_METHOD'
21:19:33 flask/app.py", line 2088, in __call__
21:19:33 return self.wsgi_app(environ, start_response)
21:19:33 flask/app.py", line 2070, in wsgi_app
21:19:33 response = self.full_dispatch_request()
21:19:33 flask/app.py", line 1513, in full_dispatch_request
21:19:33 rv = self.dispatch_request()
21:19:33 flask/app.py", line 1499, in dispatch_request
21:19:33 return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
21:19:33 sirepo/uri_router.py", line 219, in _dispatch
21:19:33 return call_api(route.func, kwargs)
21:19:33 sirepo/http_reply.py:284:_gen_exception_error unsupported exception=<class 'KeyError'> msg='REQUEST_METHOD'
```

```txt
21:19:33 sirepo/uri_router.py:221:_dispatch exception='NoneType' object has no attribute 'save_to_cookie' path=static/css/sirepo.css stack=Traceback (most recent call last):
21:19:33 sirepo/uri_router.py", line 219, in _dispatch
21:19:33 return call_api(route.func, kwargs)
21:19:33 sirepo/uri_router.py", line 93, in call_api
21:19:33 sirepo.cookie.save_to_cookie(r)
21:19:33 sirepo/cookie.py", line 66, in save_to_cookie
21:19:33 _state().save_to_cookie(resp)
21:19:33 AttributeError: 'NoneType' object has no attribute 'save_to_cookie'
21:19:33 Exception was printed at:
21:19:33 AttributeError: 'NoneType' object has no attribute 'save_to_cookie'
21:19:33 flask/app.py", line 2088, in __call__
21:19:33 return self.wsgi_app(environ, start_response)
21:19:33 flask/app.py", line 2070, in wsgi_app
21:19:33 response = self.full_dispatch_request()
21:19:33 flask/app.py", line 1513, in full_dispatch_request
21:19:33 rv = self.dispatch_request()
21:19:33 flask/app.py", line 1499, in dispatch_request
21:19:33 return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
21:19:33 Traceback (most recent call last):
21:19:33 flask/app.py", line 2088, in __call__
21:19:33 return self.wsgi_app(environ, start_response)
21:19:33 flask/app.py", line 2073, in wsgi_app
21:19:33 response = self.handle_exception(e)
21:19:33 flask/app.py", line 2070, in wsgi_app
21:19:33 response = self.full_dispatch_request()
21:19:33 flask/app.py", line 1515, in full_dispatch_request
21:19:33 rv = self.handle_user_exception(e)
21:19:33 flask/app.py", line 1513, in full_dispatch_request
21:19:33 rv = self.dispatch_request()
21:19:33 flask/app.py", line 1499, in dispatch_request
21:19:33 return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
21:19:33 sirepo/uri_router.py", line 219, in _dispatch
21:19:33 return call_api(route.func, kwargs)
21:19:33 sirepo/uri_router.py", line 93, in call_api
21:19:33 sirepo.cookie.save_to_cookie(r)
21:19:33 sirepo/cookie.py", line 66, in save_to_cookie
21:19:33 _state().save_to_cookie(resp)
21:19:33 AttributeError: 'NoneType' object has no attribute 'save_to_cookie'
```

```txt
21:19:42 '<redact> - li-<redact> "GET /static/img/sirepo_animated.gif HTTP/1.1" 200 6847 "https://www.sirepo.com/srw" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/<redact> Safari/537.36"'
21:19:42 sirepo/uri_router.py:221:_dispatch exception='NoneType' object has no attribute 'get' path=static/js/ext/angular.min.js stack=Traceback (most recent call last):
21:19:42 sirepo/uri_router.py", line 219, in _dispatch
21:19:42 return call_api(route.func, kwargs)
21:19:42 sirepo/uri_router.py", line 93, in call_api
21:19:42 sirepo.cookie.save_to_cookie(r)
21:19:42 sirepo/cookie.py", line 66, in save_to_cookie
21:19:42 _state().save_to_cookie(resp)
21:19:42 sirepo/cookie.py", line 229, in _state
21:19:42 return sirepo.srcontext.get(_SRCONTEXT_KEY)
21:19:42 sirepo/srcontext.py", line 48, in get
21:19:42 return _context().get(key, default)
21:19:42 AttributeError: 'NoneType' object has no attribute 'get'
21:19:42 Exception was printed at:
21:19:42 AttributeError: 'NoneType' object has no attribute 'get'
21:19:42 flask/app.py", line 2088, in __call__
21:19:42 return self.wsgi_app(environ, start_response)
21:19:42 flask/app.py", line 2070, in wsgi_app
21:19:42 response = self.full_dispatch_request()
21:19:42 flask/app.py", line 1513, in full_dispatch_request
21:19:42 rv = self.dispatch_request()
21:19:42 flask/app.py", line 1499, in dispatch_request
21:19:42 return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
21:19:42 Traceback (most recent call last):
21:19:42 sirepo/cookie.py", line 123, in _set_state
21:19:42 '<redact> - li-<redact> "GET /static/js/ext/cookieconsent.min.js?20210716.212025 HTTP/1.1" 200 20139 "https://www.sirepo.com/srw" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/<redact> Safari/537.36"'
21:19:42 ctx.auto_pop(error)
```

**Comment by robnagler** [comment]
#3717

**Comment by robnagler** [comment]
Here are some mixed requests from the same user and it might be that in_flask_request is not quite working right:

```txt
20:52:39 '<redact> - li-<redact> "GET /static/js/ext/bootstrap-toggle.min.js?20210716.212025 HTTP/1.1" 304 191 "https://www.sirepo.com/controls" "Mozilla/5.0
(Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/<redact> Safari/537.36"'
20:52:39 Traceback (most recent call last):
20:52:39 sirepo/cookie.py", line 122, in _set_state
20:52:39 '<redact> - li-<redact> "GET /static/js/ext/bootstrap-3.3.7.min.js?20210716.212025 HTTP/1.1" 304 192 "https://www.sirepo.com/controls" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/<redact> Safari/537.36"'
20:52:39 sirepo.srcontext.set(_SRCONTEXT_KEY, _State(header))
20:52:39 '<redact> - li-<redact> "GET /static/css/lattice.css?20210716.212025 HTTP/1.1" 304 180 "https://www.sirepo.com/controls" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/<redact> Safari/537.36"'
20:52:39 sirepo/srcontext.py", line 56, in set
20:52:39 _context()[key] = value
20:52:39 TypeError: 'NoneType' object does not support item assignment
20:52:39 During handling of the above exception, another exception occurred:
20:52:39 Traceback (most recent call last):
20:52:39 sirepo/srcontext.py", line 37, in create
20:52:39 '<redact> - li-<redact> "GET /static/js/ext/canvg-and-dependencies.js?20210716.212025 HTTP/1.1" 304 196 "https://www.sirepo.com/controls" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/<redact> Safari/537.36"'
20:52:39 yield _context()
20:52:39 sirepo/auth_db.py", line 306, in session
20:52:39 yield
20:52:39 sirepo/auth/__init__.py", line 320, in process_request
20:52:39 with auth_db.session(), cookie.process_header(unit_test):
20:52:39 File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/contextlib.py", line 112, in __enter__
20:52:39 return next(self.gen)
20:52:39 sirepo/cookie.py", line 51, in process_header
20:52:39 with _set_state(unit_test or flask.request.environ.get('HTTP_COOKIE', '')):
20:52:39 File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/contextlib.py", line 112, in __enter__
20:52:39 return next(self.gen)
20:52:39 sirepo/cookie.py", line 125, in _set_state
20:52:39 sirepo.srcontext.set(_SRCONTEXT_KEY, p)
20:52:39 sirepo/srcontext.py", line 56, in set
20:52:39 '<redact> - li-<redact> "GET /static/js/ext/FileSaver.js?20210716.212025 HTTP/1.1" 304 180 "https://www.sirepo.com/controls" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/<redact> Safari/537.36"'
20:52:39 _context()[key] = value
20:52:39 TypeError: 'NoneType' object does not support item assignment
20:52:39 During handling of the above exception, another exception occurred:
20:52:39 Traceback (most recent call last):
20:52:39 flask/app.py", line 2073, in wsgi_app
20:52:39 response = self.handle_exception(e)
20:52:39 flask/app.py", line 2070, in wsgi_app
20:52:39 '<redact> - li-<redact> "GET /static/js/ext/Blob.js?20210716.212025 HTTP/1.1" 304 175 "https://www.sirepo.com/controls" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/<redact> Safari/537.36"'
```

**Comment by robnagler** [comment]
This just happened on prod. @moellep and I couldn't get in. Here's the first entry that showed the flask.g error:

```txt
22:44:52 '<redact> - li-<redact> "GET /static/img/favicon.png?20211015.162538 HTTP/1.1" 304 180 "https://www.sirepo.com/srw" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/<redact> Safari/537.36"'
22:44:53 Traceback (most recent call last):
22:44:53 flask/app.py", line 2091, in __call__
22:44:53 Traceback (most recent call last):
22:44:53 sirepo/cookie.py", line 122, in _set_state
22:44:53 sirepo.srcontext.set(_SRCONTEXT_KEY, _State(header))
22:44:53 sirepo/srcontext.py", line 56, in set
22:44:53 return self.wsgi_app(environ, start_response)
22:44:53 flask/app.py", line 2076, in wsgi_app
22:44:53 _context()[key] = value
22:44:53 sirepo/srcontext.py", line 68, in _context
22:44:53 raise AssertionError('no flask.g {_FLASK_G_SR_CONTEXT_KEY}')
22:44:53 AssertionError: no flask.g {_FLASK_G_SR_CONTEXT_KEY}
22:44:53 During handling of the above exception, another exception occurred:
22:44:53 Traceback (most recent call last):
22:44:53 sirepo/srcontext.py", line 37, in create
22:44:53 response = self.handle_exception(e)
22:44:53 flask/app.py", line 2073, in wsgi_app
22:44:53 yield _context()
22:44:53 sirepo/auth_db.py", line 306, in session
22:44:53 yield
22:44:53 sirepo/auth/__init__.py", line 320, in process_request
22:44:53 response = self.full_dispatch_request()
22:44:53 flask/app.py", line 1518, in full_dispatch_request
22:44:53 with auth_db.session(), cookie.process_header(unit_test):
22:44:53 File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/contextlib.py", line 112, in __enter__
22:44:53 return next(self.gen)
22:44:53 sirepo/cookie.py", line 51, in process_header
22:44:53 rv = self.handle_user_exception(e)
22:44:53 flask/app.py", line 1516, in full_dispatch_request
22:44:53 with _set_state(unit_test or flask.request.environ.get('HTTP_COOKIE', '')):
22:44:53 File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/contextlib.py", line 112, in __enter__
22:44:53 return next(self.gen)
22:44:53 sirepo/cookie.py", line 125, in _set_state
22:44:53 rv = self.dispatch_request()
22:44:53 flask/app.py", line 1502, in dispatch_request
22:44:53 sirepo.srcontext.set(_SRCONTEXT_KEY, p)
22:44:53 sirepo/srcontext.py", line 56, in set
22:44:53 _context()[key] = value
22:44:53 sirepo/srcontext.py", line 68, in _context
22:44:53 return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
22:44:53 sirepo/uri_router.py", line 194, in _dispatch
22:44:53 raise AssertionError('no flask.g {_FLASK_G_SR_CONTEXT_KEY}')
22:44:53 AssertionError: no flask.g {_FLASK_G_SR_CONTEXT_KEY}
22:44:53 During handling of the above exception, another exception occurred:
22:44:53 Traceback (most recent call last):
22:44:53 with sirepo.auth.process_request():
22:44:53 flask/app.py", line 2091, in __call__
22:44:53 File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/contextlib.py", line 112, in __enter__
22:44:53 return next(self.gen)
22:44:53 sirepo/auth/__init__.py", line 320, in process_request
22:44:53 with auth_db.session(), cookie.process_header(unit_test):
22:44:53 return self.wsgi_app(environ, start_response)
22:44:53 File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/contextlib.py", line 112, in __enter__
22:44:53 flask/app.py", line 2076, in wsgi_app
22:44:53 return next(self.gen)
22:44:53 sirepo/auth_db.py", line 303, in session
22:44:53 with sirepo.srcontext.create() as c:
22:44:53 File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/contextlib.py", line 112, in __enter__
22:44:53 response = self.handle_exception(e)
22:44:53 flask/app.py", line 2073, in wsgi_app
22:44:53 return next(self.gen)
22:44:53 sirepo/srcontext.py", line 30, in create
22:44:53 f'existing srcontext on flask.g={flask.g}'
22:44:53 AssertionError: existing srcontext on flask.g=<flask.g of 'sirepo.server'>
22:44:53 '<redact> - - "GET /static/img/favicon.ico?20211015.162538 HTTP/1.1" 500 0 "https://www.sirepo.com/srw" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/<redact> Safari/537.36"'
```

```txt
22:53:32 sirepo/uri_router.py", line 79, in call_api
22:53:32 r = flask.make_response(f(**kwargs) if kwargs else f())
22:53:32 sirepo/server.py", line 569, in api_staticFile
22:53:32 return flask.send_file(p, conditional=True)
22:53:32 flask/helpers.py", line 625, in send_file
22:53:32 cache_timeout=cache_timeout,
22:53:32 flask/helpers.py", line 482, in _prepare_send_file_kwargs
22:53:32 max_age = current_app.get_send_file_max_age
22:53:32 werkzeug/local.py", line 422, in __get__
22:53:32 obj = instance._get_current_object()
22:53:32 werkzeug/local.py", line 544, in _get_current_object
22:53:32 return self.__local()  # type: ignore
22:53:32 flask/globals.py", line 47, in _find_app
22:53:32 raise RuntimeError(_app_ctx_err_msg)
22:53:32 RuntimeError: Working outside of application context.
22:53:32 This typically means that you attempted to use functionality that needed
22:53:32 to interface with the current application object in some way. To solve
22:53:32 this, set up an application context with app.app_context().  See the
22:53:32 documentation for more information.
22:53:32 Exception was printed at:
22:53:32 RuntimeError: Working outside of application context.
22:53:32 This typically means that you attempted to use functionality that needed
22:53:32 to interface with the current application object in some way. To solve
22:53:32 this, set up an application context with app.app_context().  See the
22:53:32 documentation for more information.
22:53:32 flask/app.py", line 2091, in __call__
22:53:32 return self.wsgi_app(environ, start_response)
22:53:32 flask/app.py", line 2073, in wsgi_app
22:53:32 response = self.full_dispatch_request()
22:53:32 flask/app.py", line 1516, in full_dispatch_request
22:53:32 rv = self.dispatch_request()
22:53:32 flask/app.py", line 1502, in dispatch_request
22:53:32 return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
22:53:32 sirepo/uri_router.py", line 219, in _dispatch
22:53:32 return call_api(route.func, kwargs)
22:53:32 sirepo/http_reply.py:285:_gen_exception_error unsupported exception=<class 'RuntimeError'> msg=Working outside of application context.
22:53:32 This typically means that you attempted to use functionality that needed
22:53:32 to interface with the current application object in some way. To solve
22:53:32 this, set up an application context with app.app_context().  See the
22:53:32 documentation for more information.
22:53:32 sirepo/uri_router.py:221:_dispatch exception=no sirepo.cookie path=static/js/sirepo-dom.js stack=Traceback (most recent call last):
22:53:32 sirepo/uri_router.py", line 219, in _dispatch
22:53:32 return call_api(route.func, kwargs)
22:53:32 sirepo/uri_router.py", line 93, in call_api
22:53:32 sirepo.cookie.save_to_cookie(r)
22:53:32 sirepo/cookie.py", line 66, in save_to_cookie
22:53:32 _state().save_to_cookie(resp)
22:53:32 sirepo/cookie.py", line 231, in _state
22:53:32 raise AssertionError(f'no {_SRCONTEXT_KEY}')
22:53:32 AssertionError: no sirepo.cookie
22:53:32 Exception was printed at:
22:53:32 AssertionError: no sirepo.cookie
22:53:32 flask/app.py", line 2091, in __call__
22:53:32 return self.wsgi_app(environ, start_response)
22:53:32 flask/app.py", line 2073, in wsgi_app
22:53:32 response = self.full_dispatch_request()
22:53:32 flask/app.py", line 1516, in full_dispatch_request
22:53:32 rv = self.dispatch_request()
22:53:32 flask/app.py", line 1502, in dispatch_request
22:53:32 return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
22:53:32 Traceback (most recent call last):
22:53:32 flask/app.py", line 2091, in __call__
22:53:32 return self.wsgi_app(environ, start_response)
22:53:32 flask/app.py", line 2076, in wsgi_app
22:53:32 response = self.handle_exception(e)
22:53:32 flask/app.py", line 2073, in wsgi_app
22:53:32 response = self.full_dispatch_request()
22:53:32 flask/app.py", line 1518, in full_dispatch_request
22:53:32 rv = self.handle_user_exception(e)
22:53:32 flask/app.py", line 1516, in full_dispatch_request
22:53:32 rv = self.dispatch_request()
22:53:32 flask/app.py", line 1502, in dispatch_request
22:53:32 return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
22:53:32 sirepo/uri_router.py", line 219, in _dispatch
22:53:32 return call_api(route.func, kwargs)
22:53:32 sirepo/uri_router.py", line 93, in call_api
22:53:32 sirepo.cookie.save_to_cookie(r)
22:53:32 sirepo/cookie.py", line 66, in save_to_cookie
22:53:32 _state().save_to_cookie(resp)
22:53:32 sirepo/cookie.py", line 231, in _state
22:53:32 raise AssertionError(f'no {_SRCONTEXT_KEY}')
22:53:32 AssertionError: no sirepo.cookie
22:53:32 '<redact> - li-<redact> "GET /static/js/sirepo-dom.js?20211015.162538 HTTP/1.1" 500 0 "https://www.sirepo.com/srw" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/<redact> Safari/537.36"'
```
