### ISSUE TITLE
srw KeyError: 'beamlineAnimation16'

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#3821]
From @mrakitin
```txt
/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/pkcli/job_agent.py:246:_op opName=analysis o=u35l runDir=/sirepo/user/RADwi8Z4/srw/kyOiCbhr/beamlineAnimation
/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_supervisor.py:956:reply_get _Op(analysis, u35l) await _reply_q.get()
/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_driver/__init__.py:300:_receive LocalDriver(a=2jjM k=sequential u=RADw [_Op(analysis, u35l)]) error msg={'agentId': '2jjMkXBWX8AA2aS30E3i3x1owCM1P6F5', 'opId': 'u35lDHnV3fMs0Zd8DB4wy1GfxZ0gaWJ3', 'opName': 'analysis', 'reply': {'error': ''beamlineAnimation16'', 'stack': 'Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/pkcli/job_cmd.py", line 121, in _do_download_data_file
    options=PKDict(suffix=msg.suffix),
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/template/srw.py", line 427, in get_data_file
    return get_filename_for_model(model)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/template/srw.py", line 433, in get_filename_for_model
    return _OUTPUT_FOR_MODEL[model].filename
KeyError: 'beamlineAnimation16'
```

**Comment by robnagler** [comment]
Duplicate of #3793
