### ISSUE TITLE
SRW - cannot copy simulation

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#384]
@robnagler, after the recent updates, a simulation cannot be copied. Unfortunately, I placed the recent code to the production server, and there are important calculations which need to be shared.

There is the following error appearing in the server log when the link to the simulation entered to the URL string of a browser:
```python
Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/beaker/middleware.py", line 155, in __call__
    return self.wrap_app(environ, session_start_response)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/server.py", line 411, in app_simulation_data
    data = simulation_db.read_simulation_json(simulation_type, sid=simulation_id)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/simulation_db.py", line 433, in read_simulation_json
    new = fixup_old_data(sim_type, copy.deepcopy(data))
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/simulation_db.py", line 140, in fixup_old_data
    sirepo.template.import_module(simulation_type).fixup_old_data(data)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/template/srw.py", line 263, in fixup_old_data
    if data['models']['fluxReport'] and 'photonEnergyPointCount' not in data['models']['fluxReport']:
KeyError: 'models'
```

Could you please fix the issue?

**Comment by robnagler** [comment]
Can you rollback?

**Comment by robnagler** [comment]
I'm working on this now. @mrakitin, please rollback your release to the last alpha commit.

**Comment by mrakitin** [comment]
Thanks Rob! The machine wasn't used much tonight, I just updated the code, and it looks good now. Thanks for the fix.
