### ISSUE TITLE
jupyterhublogin create-user AssertionError: existing user dir with same name=

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#4039]
Is this expected @e-carlin?

```txt
Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/py3/bin/sirepo", line 8, in <module>
    sys.exit(main())
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/sirepo_console.py", line 18, in main
    return pkcli.main('sirepo')
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/pykern/pkcli/__init__.py", line 108, in main
    res = argh.dispatch(parser, argv=argv)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/pkcli/jupyterhublogin.py", line 75, in create_user
    n = sirepo.sim_api.jupyterhublogin.create_user(check_dir=True)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/sim_api/jupyterhublogin.py", line 128, in create_user
    f'existing user dir with same name={h}'
AssertionError: existing user dir with same name=xyzzy
```

**Comment by e-carlin** [comment]
Yes, we have a directory of a user `xyzzy` but we don't not have a record of that user in sqlite. We don't know if the new `xyzzy` and the existing dir `xyzzy` are the same person or not.
