### ISSUE TITLE
server.status fails sporadically

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#4322]

**Comment by robnagler** [comment]
The error is here. There wasn't anything else going on. The previous poll worked and so did the next one (despite the ERROR, see below):

```txt
06:49:29 sirepo/job_supervisor.py:309:receive ServerReq(api_runSimulation, uid0-sid1-initialIntensityReport)
06:49:31 sirepo/job_supervisor.py:981:__init__ _Op(run, amRH) runDir=/db/uid0/srw/sid1/initialIntensityReport
06:49:31 sirepo/job_supervisor.py:109:alloc _Op(run, amRH) situation=Waiting for another simulation to complete
06:49:48 sirepo/job_supervisor.py:309:receive ServerReq(api_runCancel, uid0-sid1-initialIntensityReport)
06:49:49 sirepo/job_supervisor.py:981:__init__ _Op(cancel, wfc6) runDir=/db/uid0/srw/sid1/initialIntensityReport
06:49:49 sirepo/job_supervisor.py:647:_receive_api_runCancel _ComputeJob(uid0-sid1-initialIntensityReport u=uid0 canceled [_Op(run, amRH), _Op(cancel, wfc6)]) cancel={_Op(run, amRH)}
06:49:49 sirepo/job_driver/__init__.py:186:send DockerDriver(a=8IXh k=sequential u=uid0 [_Op(cancel, wfc6)]) _Op(cancel, wfc6) runDir=/db/uid0/srw/sid1/initialIntensityReport
06:49:49 sirepo/job_supervisor.py:1018:reply_get _Op(cancel, wfc6) await _reply_q.get()
06:49:49 sirepo/job_supervisor.py:1049:set_job_situation _Op(run, amRH) situation=Waiting for another simulation to complete stack=Traceback (most recent call last):
06:49:49 sirepo/job_supervisor.py", line 1046, in set_job_situation
06:49:49 yield
06:49:49 sirepo/job_supervisor.py", line 111, in alloc
06:49:49 self._value = await self._q.get()
06:49:49 sirepo/tornado.py", line 49, in get
06:49:49 return await x
06:49:49 concurrent.futures._base.CancelledError
06:49:49 Exception was printed at:
06:49:49 concurrent.futures._base.CancelledError
06:49:49 File "/home/vagrant/.pyenv/versions/py3/bin/sirepo", line 8, in <module>
06:49:49 sys.exit(main())
06:49:49 sirepo/sirepo_console.py", line 18, in main
06:49:49 return pkcli.main('sirepo')
06:49:49 pykern/pkcli/__init__.py", line 108, in main
06:49:49 res = argh.dispatch(parser, argv=argv)
06:49:49 argh/dispatching.py", line 174, in dispatch
06:49:49 for line in lines:
06:49:49 argh/dispatching.py", line 277, in _execute_command
06:49:49 for line in result:
06:49:49 argh/dispatching.py", line 260, in _call
06:49:49 result = function(*positional, **keywords)
06:49:49 sirepo/pkcli/job_supervisor.py", line 78, in default_command
06:49:49 tornado.ioloop.IOLoop.current().start()
06:49:49 tornado/platform/asyncio.py", line 199, in start
06:49:49 self.asyncio_loop.run_forever()
06:49:49 File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/asyncio/base_events.py", line 539, in run_forever
06:49:49 self._run_once()
06:49:49 File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/asyncio/base_events.py", line 1775, in _run_once
06:49:49 handle._run()
06:49:49 File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/asyncio/events.py", line 88, in _run
06:49:49 self._context.run(self._callback, *self._args)
06:49:49 sirepo/job_supervisor.py", line 111, in alloc
06:49:49 self._value = await self._q.get()
06:49:49 File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/contextlib.py", line 130, in __exit__
06:49:49 self.gen.throw(type, value, traceback)
06:49:50 sirepo/job_driver/__init__.py:303:_receive DockerDriver(a=8IXh k=sequential u=uid0 [_Op(cancel, wfc6)]) opName=ok o=wfc6
06:50:11 sirepo/job_supervisor.py:1028:run_timeout _Op(run, 8w0y) max_run_secs=360
06:54:57 sirepo/job_supervisor.py:309:receive ServerReq(api_runSimulation, uid0-sid1-initialIntensityReport)
06:54:58 Apr 13 06:54:58     6     0 /home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/asyncio/base_events.py:1608:default_exception_handler ERROR:asyncio:Task was destroyed but it is pending!
06:54:58 sirepo/job_supervisor.py:853> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f9593ca2438>()]> cb=[IOLoop.add_future.<locals>.<lambda>() at /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/tornado/ioloop.py:688]>
06:54:59 sirepo/job_supervisor.py:981:__init__ _Op(run, 5BOT) runDir=/db/uid0/srw/sid1/initialIntensityReport
06:55:00 sirepo/job_driver/__init__.py:186:send DockerDriver(a=8IXh k=sequential u=uid0 [_Op(run, 5BOT)]) _Op(run, 5BOT) runDir=/db/uid0/srw/sid1/initialIntensityReport
```

**Comment by robnagler** [comment]
We had two failures on alpha today. I didn't look at them. @moellep could you look to see if they are the same?

**Comment by moellep** [comment]
No errors in on the job_supervisor on alpha in the last 24 hours. I didn't receive the failures - did it go out as a text message from 24/7?

**Comment by moellep** [comment]
I'm seeing this in the sirepo log on alpha:

```api=<function api_serverStatus at 0x7fd8d51deae8> exception=simulation timed out: seconds=15```

**Comment by robnagler** [comment]
Yes, that's the error. It's an agent start problem. I'm going to increaes the timeout.

**Comment by robnagler** [comment]
Will be fixed by https://github.com/radiasoft/sirepo/issues/4230
