### ISSUE TITLE
exporter_test.py failing on alpha build

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#4343]
AssertionError: cannot find submodule=template for sim_type=warppba in package_path=('sirepo',)

**Comment by e-carlin** [comment]
```
>>> import sirepo.template.warppba
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/template/warppba.py", line 8, in <module>
    from openpmd_viewer import OpenPMDTimeSeries
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/openpmd_viewer/__init__.py", line 9, in <module>
    from .openpmd_timeseries import OpenPMDTimeSeries, FieldMetaInformation, \
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/openpmd_viewer/openpmd_timeseries/__init__.py", line 2, in <module>
    from .main import OpenPMDTimeSeries, ParticleTracker
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/openpmd_viewer/openpmd_timeseries/main.py", line 13, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
```
