### ISSUE TITLE
AssertionError: cannot find submodule=template for sim_type=elegant in package_path=('sirepo',)

### ISSUE THREAD

**Issue by cchall** [radiasoft/sirepo#4360]
After updating my sirepo install to c3e7dff9e58c11ffb57a71b078f5a2ad2a9050df I'm getting an error when I try to use sirepo.lib:

```
from sirepo import lib
lib.Importer('elegant')

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
/tmp/ipykernel_19939/3405691719.py in <module>
----> 1 lib.Importer('elegant')

~/.pyenv/versions/py3/lib/python3.7/site-packages/sirepo/lib.py in __init__(self, sim_type, ignore_files)
    113         import sirepo.template
    114 
--> 115         self.__adapter = sirepo.template.import_module(sim_type).LibAdapter(ignore_files or [])
    116 
    117     def parse_file(self, path):

~/.pyenv/versions/py3/lib/python3.7/site-packages/sirepo/template/__init__.py in import_module(type_or_data)
     32         module: simulation type module instance
     33     """
---> 34     return sirepo.util.import_submodule('template', type_or_data)
     35 
     36 

~/.pyenv/versions/py3/lib/python3.7/site-packages/sirepo/util.py in import_submodule(submodule, type_or_data)
    256     # gives more debugging info (perhaps more confusion)
    257     pkdc(s)
--> 258     raise AssertionError(f'cannot find submodule={submodule} for sim_type={t} in package_path={r}')
    259 
    260 

AssertionError: cannot find submodule=template for sim_type=elegant in package_path=('sirepo',)
```

**Comment by robnagler** [comment]
Is this running on jupyter?

**Comment by e-carlin** [comment]
@cchall please run `python -c import sirepo.template.elegant` and post the error if there is one. Could be bumping against https://github.com/radiasoft/sirepo/issues/4351

**Comment by cchall** [comment]
@e-carlin 
```
$ python -c "import sirepo.template.elegant"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/sirepo/template/elegant.py", line 12, in <module>
    from sirepo import simulation_db
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/sirepo/simulation_db.py", line 18, in <module>
    from sirepo.template import template_common
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/sirepo/template/template_common.py", line 13, in <module>
    import f90nml
ModuleNotFoundError: No module named 'f90nml'
```

**Comment by robnagler** [comment]
This should be fixed in the latest code. f90nml doesn't need to be imported unless a specific function is used.

**Comment by cchall** [comment]
I get a different error for opal on f25af64e97167322725c3b261abe1351d2fbc0e2:

```
multi_code_example chall$ python -c 'import sirepo.template.opal'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/chall/.local/share/virtualenvs/libe8/lib/python3.8/site-packages/sirepo/template/opal.py", line 9, in <module>
    import astunparse
ModuleNotFoundError: No module named 'astunparse'
```

**Comment by robnagler** [comment]
That's not running inside beamsim so you'll need to pip install astunparse.
