### ISSUE TITLE
simulation gets stuck in running state

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#440]
If a simulation is running and then the client loses the connection or the server is restarted, later requests for the same simulation will cause a server error. Refreshing the browser doesn't fix the problem, but restarting the simulation will new parameters works OK.

  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/sirepo-20160927.155814-py2.7.egg/sirepo/server.py", line 340, in app_run_simulation
    _start_simulation(data)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/sirepo-20160927.155814-py2.7.egg/sirepo/server.py", line 862, in _start_simulation
    cfg.job_queue(data)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/sirepo-20160927.155814-py2.7.egg/sirepo/server.py", line 1043, in __init__
    '{}: simulation already running'.format(self.jid)
AssertionError: 3yNAcFk9-DHxT6FZ5-watchpointReport6: simulation already running

**Comment by moellep** [comment]
Restarting the simulation with new parameters doesn't fix the problem - the server's _job variable is holding on to the failed job id.

**Comment by robnagler** [comment]
If the server is restarted, all the jobs are lost (_job will be reinitialized to {}) (see #411)

For parallel/persistent simulations, runStatus is called first. For sequential/transient, they shouldn't run for more than a few seconds. The general assertion problem is noted in #423. 

I think all simulations should be the same, and there should be a restart button. if a simulation is already running, the server should return an error, and have the client to refresh with runStatus.

**Comment by robnagler** [comment]
A temporary fix is for the client to call runStatus on transient simulations before calling runSimulation.

**Comment by moellep** [comment]
In this case, it was not a background task and there were no active
simulations running on the server. Somehow _job has an entry which didn't
get cleaned up. David ran into this problem yesterday with warp. It is
still happening with my SRW simulation DHxT6FZ5 on alpha. The only fix
would be to restart the server to clear out the _job hash.

**Comment by robnagler** [comment]
This is handled by #423 and #410. I'm pretty sure Celery backend=rpc is
unreliable so we need to switch to Postgres.

When runSimulation is called, it calls _simulation_run_status, which ends
up querying Celery. As far as Celery is concerned, the job is running.
However, Celery is not a process, just a query to the Rabbit. Rabbit is a
queueing/IPC system not a db that is being used strangely within Celery for
this "rpc" backend. I'm slightly concerned that adding Flower may cause
Flask to miss the reply.

In any event, I'll look at adding Postgres. It should be relatively easy.

**Comment by robnagler** [comment]
Rapidly clicking start/end caused this, but it didn't show up as an alert:

```
https://alpha.sirepo.com/run-simulation Failed to load resource: the server responded with a status of 502 (Bad Gateway)
2016-09-28 07:00:52.911 sirepo.js?20160927.000000:860 502 Bad Gateway : error response from server
2016-09-28 07:00:52.911 sirepo.js?20160927.000000:878 502 Bad Gateway
2016-09-28 07:00:53.028 https://alpha.sirepo.com/run-simulation Failed to load resource: the server responded with a status of 502 (Bad Gateway)
2016-09-28 07:00:53.029 sirepo.js?20160927.000000:860 502 Bad Gateway : error response from server
2016-09-28 07:00:53.029 sirepo.js?20160927.000000:878 502 Bad Gateway
```

There are no entries in Rabbit at this time so Celery didn't do anything. Flask gets `simulation already running`. Right before that error, I see two save-simulation calls pretty close together (only one client running).

```
50.253.124.194 - li-3yNAcFk9 [28/Sep/2016:13:00:41 +0000] "POST /run-status HTTP/1.1" 200 384 "https://alpha.sirepo.com/srw" "Mozilla/5.0 (iPhone; CPU iPhone OS 10_0_2 like Mac OS
 X) AppleWebKit/602.1.50 (KHTML, like Gecko) Version/10.0 Mobile/14A456 Safari/602.1"
107.2.238.70 - li-iSbBL0w9 [28/Sep/2016:13:00:41 +0000] "GET /static/html/warp-dynamics.html?20160927.000000 HTTP/1.1" 304 182 "https://alpha.sirepo.com/warp" "Mozilla/5.0 (Macint
osh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36"
107.2.238.70 - li-iSbBL0w9 [28/Sep/2016:13:00:41 +0000] "POST /save-simulation HTTP/1.1" 200 1914 "https://alpha.sirepo.com/warp" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5)
AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36"
107.2.238.70 - li-iSbBL0w9 [28/Sep/2016:13:00:41 +0000] "POST /run-status HTTP/1.1" 200 419 "https://alpha.sirepo.com/warp" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleW
ebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36"
107.2.238.70 - li-iSbBL0w9 [28/Sep/2016:13:00:41 +0000] "POST /save-simulation HTTP/1.1" 200 2266 "https://alpha.sirepo.com/warp" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5)
AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36"
107.2.238.70 - li-iSbBL0w9 [28/Sep/2016:13:00:41 +0000] "GET /simulation-frame/warp*qzM45xk0*fieldAnimation*E_x_1*108*1475017942 HTTP/1.1" 200 425048 "https://alpha.sirepo.com/war
p" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36"
107.2.238.70 - li-iSbBL0w9 [28/Sep/2016:13:00:41 +0000] "GET /simulation-frame/warp*qzM45xk0*particleAnimation*z_x_413_0_0_-5_5_0_0_0_0_0_0_0_0*108*1475017942 HTTP/1.1" 200 874268
 "https://alpha.sirepo.com/warp" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36"
50.253.124.194 - li-3yNAcFk9 [28/Sep/2016:13:00:42 +0000] "POST /run-status HTTP/1.1" 200 384 "https://alpha.sirepo.com/srw" "Mozilla/5.0 (iPhone; CPU iPhone OS 10_0_2 like Mac OS
 X) AppleWebKit/602.1.50 (KHTML, like Gecko) Version/10.0 Mobile/14A456 Safari/602.1"
Sep 28 13:00:43   171 21712 /home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/sirepo-20160927.213356-py2.7.egg/sirepo/server.py:1076:kill iSbBL0w9-qzM45xk0-animatio
n: killing: tid=0faa730e-04b9-4f96-b861-8c470266e40b
107.2.238.70 - li-iSbBL0w9 [28/Sep/2016:13:00:43 +0000] "POST /save-simulation HTTP/1.1" 200 1915 "https://alpha.sirepo.com/warp" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5)
AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36"
50.253.124.194 - li-3yNAcFk9 [28/Sep/2016:13:00:43 +0000] "POST /run-status HTTP/1.1" 200 384 "https://alpha.sirepo.com/srw" "Mozilla/5.0 (iPhone; CPU iPhone OS 10_0_2 like Mac OS
 X) AppleWebKit/602.1.50 (KHTML, like Gecko) Version/10.0 Mobile/14A456 Safari/602.1"
107.2.238.70 - li-iSbBL0w9 [28/Sep/2016:13:00:43 +0000] "POST /save-simulation HTTP/1.1" 200 1914 "https://alpha.sirepo.com/warp" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5)
AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36"
Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/beaker/middleware.py", line 155, in __call__
    return self.wrap_app(environ, session_start_response)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/sirepo-20160927.213356-py2.7.egg/sirepo/server.py", line 578, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/sirepo-20160927.213356-py2.7.egg/sirepo/server.py", line 340, in app_run_simulation
    _start_simulation(data)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/sirepo-20160927.213356-py2.7.egg/sirepo/server.py", line 862, in _start_simulation
    cfg.job_queue(data)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/sirepo-20160927.213356-py2.7.egg/sirepo/server.py", line 1043, in __init__
    '{}: simulation already running'.format(self.jid)
AssertionError: iSbBL0w9-qzM45xk0-animation: simulation already running
```

**Comment by robnagler** [comment]
In general, this morning, alpha seems "more stable". I don't know what was going on yesterday. 

There are a bunch of moving parts here, and one of them is that the packages installed varies on every build. I'm going back to a previous image and install sirepo inside that.

**Comment by robnagler** [comment]
FTR, on my VM:

```sh
docker pull radiasoft/sirepo:20160913.234500 
docker run -it radiasoft/sirepo:20160913.234500
yum install -y postgresql-devel
su - vagrant
mkdir /tmp/b
cd /tmp/b
git clone https://github.com/radiasoft/pykern
cd pykern
pip install -r requirements.txt
git clone https://github.com/radiasoft/sirepo
cd sirepo
pip install -r requirements.txt
exit
exit
docker commit 285d9355d86f radiasoft/sirepo:20160928.132500
docker push radiasoft/sirepo:20160928.132500
```

On alpha:
```sh
docker tag cbdfcbaf5c70 radiasoft/sirepo:20160927.215059
docker pull radiasoft/sirepo:20160928.132500
docker tag -f radiasoft/sirepo:20160928.132500 radiasoft/sirepo:alpha
for f in celery-sirepo sirepo; do service $f restart; done
```

**Comment by robnagler** [comment]
I forgot to pip install sirepo so:

```sh
docker commit bd32366387ae radiasoft/sirepo:20160928.133800
docker push radiasoft/sirepo:20160928.133800
```

**Comment by robnagler** [comment]
This is the sirepo sequence that fails here. 
```txt
107.2.238.70 - li-iSbBL0w9 [28/Sep/2016:13:41:40 +0000] "GET /simulation/warp/qzM45xk0/0 HTTP/1.1" 200 1834 "https://alpha.sirepo.com/warp" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36"
107.2.238.70 - li-iSbBL0w9 [28/Sep/2016:13:41:42 +0000] "POST /run-status HTTP/1.1" 200 242 "https://alpha.sirepo.com/warp" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36"
107.2.238.70 - li-iSbBL0w9 [28/Sep/2016:13:41:42 +0000] "POST /save-simulation HTTP/1.1" 200 2090 "https://alpha.sirepo.com/warp" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36"
107.2.238.70 - li-iSbBL0w9 [28/Sep/2016:13:41:42 +0000] "GET /simulation-frame/warp*qzM45xk0*fieldAnimation*E_x_1*108*1475069639 HTTP/1.1" 200 424643 "https://alpha.sirepo.com/warp" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36"
107.2.238.70 - li-iSbBL0w9 [28/Sep/2016:13:41:42 +0000] "GET /simulation-frame/warp*qzM45xk0*particleAnimation*z_x_413_0_0_-5_5_0_0_0_0_0_0_0_0*108*1475069639 HTTP/1.1" 200 873122 "https://alpha.sirepo.com/warp" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36"
107.2.238.70 - li-iSbBL0w9 [28/Sep/2016:13:41:44 +0000] "POST /save-simulation HTTP/1.1" 200 1914 "https://alpha.sirepo.com/warp" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36"
Sep 28 13:41:44   172 25102 /home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/sirepo-20160927.225617-py2.7.egg/sirepo/server.py:1106:_start_job /var/db/sirepo/user/iSbBL0w9/warp/qzM45xk0/animation: starting queue=parallel
107.2.238.70 - li-iSbBL0w9 [28/Sep/2016:13:41:44 +0000] "POST /run-simulation HTTP/1.1" 200 411 "https://alpha.sirepo.com/warp" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36"
107.2.238.70 - li-iSbBL0w9 [28/Sep/2016:13:41:45 +0000] "POST /save-simulation HTTP/1.1" 200 2260 "https://alpha.sirepo.com/warp" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36"
107.2.238.70 - li-iSbBL0w9 [28/Sep/2016:13:41:47 +0000] "POST /run-status HTTP/1.1" 200 411 "https://alpha.sirepo.com/warp" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36"
107.2.238.70 - li-iSbBL0w9 [28/Sep/2016:13:41:47 +0000] "POST /save-simulation HTTP/1.1" 200 2260 "https://alpha.sirepo.com/warp" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36"
107.2.238.70 - li-iSbBL0w9 [28/Sep/2016:13:41:49 +0000] "POST /run-status HTTP/1.1" 200 411 "https://alpha.sirepo.com/warp" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36"
107.2.238.70 - li-iSbBL0w9 [28/Sep/2016:13:41:49 +0000] "POST /save-simulation HTTP/1.1" 200 2260 "https://alpha.sirepo.com/warp" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36"
107.2.238.70 - li-iSbBL0w9 [28/Sep/2016:13:41:49 +0000] "POST /save-simulation HTTP/1.1" 200 1915 "https://alpha.sirepo.com/warp" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36"
Sep 28 13:41:49   172 17804 /home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/sirepo-20160927.225617-py2.7.egg/sirepo/server.py:1076:kill iSbBL0w9-qzM45xk0-animation: killing: tid=27f9c9c8-3958-41b0-b58a-05e63900b3dc
107.2.238.70 - li-iSbBL0w9 [28/Sep/2016:13:41:50 +0000] "POST /save-simulation HTTP/1.1" 200 1914 "https://alpha.sirepo.com/warp" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36"
Sep 28 13:41:50   172 44722 /home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/sirepo-20160927.225617-py2.7.egg/sirepo/server.py:1106:_start_job /var/db/sirepo/user/iSbBL0w9/warp/qzM45xk0/animation: starting queue=parallel
107.2.238.70 - li-iSbBL0w9 [28/Sep/2016:13:41:50 +0000] "POST /run-simulation HTTP/1.1" 200 411 "https://alpha.sirepo.com/warp" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36"
107.2.238.70 - li-iSbBL0w9 [28/Sep/2016:13:41:50 +0000] "POST /save-simulation HTTP/1.1" 200 2260 "https://alpha.sirepo.com/warp" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36"
Sep 28 13:41:51   172 17804 /home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/sirepo-20160927.225617-py2.7.egg/sirepo/server.py:1084:kill iSbBL0w9-qzM45xk0-animation: deleted
107.2.238.70 - li-iSbBL0w9 [28/Sep/2016:13:41:49 +0000] "POST /run-cancel HTTP/1.1" 200 92 "https://alpha.sirepo.com/warp" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36"
Sep 28 13:41:52   172 24344 /home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/sirepo-20160927.225617-py2.7.egg/sirepo/server.py:753:_simulation_error error in read_result: /var/db/sirepo/user/iSbBL0w9/warp/qzM45xk0/animation: error: ERROR: Terminated unexpectedly
107.2.238.70 - li-iSbBL0w9 [28/Sep/2016:13:41:52 +0000] "POST /run-status HTTP/1.1" 200 125 "https://alpha.sirepo.com/warp" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36"
107.2.238.70 - li-iSbBL0w9 [28/Sep/2016:13:41:52 +0000] "POST /save-simulation HTTP/1.1" 200 1976 "https://alpha.sirepo.com/warp" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36"
107.2.238.70 - li-iSbBL0w9 [28/Sep/2016:13:42:37 +0000] "GET /warp HTTP/1.1" 200 3561 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36"
107.2.238.70 - li-iSbBL0w9 [28/Sep/2016:13:42:37 +0000] "GET /static/css/bootstrap-3.3.4.min.css?20160927.000001 HTTP/1.1" 304 184 "https://alpha.sirepo.com/warp" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36"
```

Celery

```txt
[2016-09-28 13:41:45,353: WARNING/Worker-2] Sep 28 13:41:45   168     0 /home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/pykern-20160925.181333-py2.7.egg/pykern/pksubprocess.py:63:check_call_with_signals 171: started: [u'sirepo', u'warp', u'run-background', u'/var/db/sirepo/user/iSbBL0w9/warp/qzM45xk0/animation']
[2016-09-28 13:41:49,453: WARNING/Worker-2] Sep 28 13:41:49   168     0 /home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/pykern-20160925.181333-py2.7.egg/pykern/pksubprocess.py:79:check_call_with_signals 171: terminating: [u'sirepo', u'warp', u'run-background', u'/var/db/sirepo/user/iSbBL0w9/warp/qzM45xk0/animation']
[2016-09-28 13:41:49,676: ERROR/MainProcess] Task sirepo.celery_tasks.start_simulation[27f9c9c8-3958-41b0-b58a-05e63900b3dc] raised unexpected: Terminated(-70,)
Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/billiard/pool.py", line 1678, in _set_terminated
    raise Terminated(-(signum or 0))
Terminated: -70
[2016-09-28 13:41:50,976: WARNING/Worker-3] Sep 28 13:41:50   169     0 /home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/pykern-20160925.181333-py2.7.egg/pykern/pksubprocess.py:63:check_call_with_signals 202: started: [u'sirepo', u'warp', u'run-background', u'/var/db/sirepo/user/iSbBL0w9/warp/qzM45xk0/animation']
[2016-09-28 13:45:23,379: WARNING/Worker-3] Sep 28 13:45:23   169     0 /home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/pykern-20160925.181333-py2.7.egg/pykern/pksubprocess.py:69:check_call_with_signals 202: normal exit(0): [u'sirepo', u'warp', u'run-background', u'/var/db/sirepo/user/iSbBL0w9/warp/qzM45xk0/animation']
```

Rabbit

```
=INFO REPORT==== 28-Sep-2016::13:41:36 ===
accepting AMQP connection <0.11686.13> (172.17.42.1:52588 -> 172.17.0.35:5672)

=INFO REPORT==== 28-Sep-2016::13:41:49 ===
accepting AMQP connection <0.11810.13> (172.17.42.1:52800 -> 172.17.0.35:5672)

=INFO REPORT==== 28-Sep-2016::13:41:49 ===
closing AMQP connection <0.11810.13> (172.17.42.1:52800 -> 172.17.0.35:5672)

=INFO REPORT==== 28-Sep-2016::13:41:50 ===
accepting AMQP connection <0.11837.13> (172.17.42.1:52812 -> 172.17.0.35:5672)

=INFO REPORT==== 28-Sep-2016::13:45:23 ===
accepting AMQP connection <0.13570.13> (172.17.42.1:52972 -> 172.17.0.35:5672)

=WARNING REPORT==== 28-Sep-2016::13:45:23 ===
closing AMQP connection <0.13570.13> (172.17.42.1:52972 -> 172.17.0.35:5672):
client unexpectedly closed TCP connection
```

**Comment by robnagler** [comment]
Fixed
