### ISSUE TITLE
warp simulation fails every other time

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#443]
I'm not sure if celery has gotten confused on alpha, but if you open the "Warp example laser simulation" and select Start Simulation, half the time it will show "Initializing Laxer Pulse" but has not started a background job. If the select End Simulation and try again it will work, but if you select End Simulation and try again, it will fail.

I couldn't reproduce this on dev running celery/rabbit.

**Comment by moellep** [comment]
On beta, it is similar, except every other time it shows Pending, then stops everything and shows Start New Simulation.

**Comment by robnagler** [comment]
Try it now on alpha

**Comment by robnagler** [comment]
Yes, things are confused. It's running on AWS.

**Comment by robnagler** [comment]
I removed AWS and flower. Try it now

**Comment by robnagler** [comment]
I can't reproduce it.

**Comment by moellep** [comment]
This appears fixed on alpha. Probably worth stopping flower on beta and
seeing if it fixes it there.

**Comment by robnagler** [comment]
I stopped it. Please test.

I'm also building a release that will allow us to override the result
backend. It seems to work fine with postgres. Both alpha and beta already
have pg configured so it should be relatively simple to test.

**Comment by moellep** [comment]
Still a problem on beta. The second try to run the simulation,
/run-status returns {"state": "error", "error": "Terminated
unexpectedly"} to the client.

**Comment by robnagler** [comment]
```text
[2016-09-27 21:42:08,752: WARNING/Worker-30] /home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/pykern-20160925.181333-py2.7.egg/pykern/pksubprocess.py:63:check_call_with_signals 9677: started: [u'sirepo', u'warp', u'run-background', u'/var/db/sirepo/user/VXQkLQtn/warp/OsmE1lcZ/animation']
[2016-09-27 21:42:16,559: WARNING/Worker-30] /home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/pykern-20160925.181333-py2.7.egg/pykern/pksubprocess.py:79:check_call_with_signals 9677: terminating: [u'sirepo', u'warp', u'run-background', u'/var/db/sirepo/user/VXQkLQtn/warp/OsmE1lcZ/animation']
[2016-09-27 21:42:16,676: ERROR/MainProcess] Task sirepo.celery_tasks.start_simulation[d9220dbf-4d3e-4d95-acf7-c2ce9dac00dc] raised unexpected: Terminated(-70,)
Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/billiard/pool.py", line 1678, in _set_terminated
    raise Terminated(-(signum or 0))
Terminated: -70
[2016-09-27 21:42:18,983: ERROR/MainProcess] Task sirepo.celery_tasks.start_simulation[65ec29fb-6271-4bc2-9bd3-166e119fa724] raised unexpected: py.error.EEXIST 'File exists': open(u'/var/db/sirepo/user/VXQkLQtn/warp/OsmE1lcZ/animation/status', 'w')
Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/sirepo-20160926.213517-py2.7.egg/sirepo/celery_tasks.py", line 79, in start_simulation
    simulation_db.write_status('running', run_dir)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/sirepo-20160926.213517-py2.7.egg/sirepo/simulation_db.py", line 663, in write_status
    pkio.write_text(run_dir.join(_STATUS_FILE), status)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/pykern-20160925.181333-py2.7.egg/pykern/pkio.py", line 156, in write_text
    f.write_text(pkcompat.locale_str(contents), encoding=locale.getpreferredencoding())
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/py/_path/local.py", line 465, in write_text
    with self.open('w', encoding=encoding) as f:
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/py/_path/local.py", line 352, in open
    return py.error.checked_call(io.open, self.strpath, mode, encoding=encoding)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/py/_error.py", line 84, in checked_call
    raise cls("%s%r" % (func.__name__, args))
EEXIST: [File exists]: open(u'/var/db/sirepo/user/VXQkLQtn/warp/OsmE1lcZ/animation/status', 'w')
```

**Comment by robnagler** [comment]
Fixed
