### ISSUE TITLE
File exists when worker writes

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#448]
This is an NFS problem. The Celery worker is writing just after it is started and the NFS write from Flask hasn't propagated.

```txt
[2016-09-28 23:38:03,891: ERROR/MainProcess] Task sirepo.celery_tasks.start_simulation[7079fd37-909e-4eb7-8c3b-3da0837070bc] raised unexpected: IOError(17, 'File exists')
Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/sirepo-20160928.225042-py2.7.egg/sirepo/celery_tasks.py", line 90, in start_simulation
    simulation_db.write_status('running', run_dir)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/sirepo-20160928.225042-py2.7.egg/sirepo/simulation_db.py", line 667, in write_status
    pkio.write_text(run_dir.join(_STATUS_FILE), status)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/pykern-20160928.212331-py2.7.egg/pykern/pkio.py", line 156, in write_text
    with io.open(str(fn), 'w', encoding=locale.getpreferredencoding()) as f:
IOError: [Errno 17] File exists: '/var/db/sirepo/user/VXQkLQtn/warp/CluKTa5d/animation/status'
```

**Comment by robnagler** [comment]
Fixed. Needs config of 10x .0.5s. I set in env vars but also updated simulation_db.py.
