### ISSUE TITLE
job_timeout_test failing

### ISSUE THREAD

**Issue by rorour** [radiasoft/sirepo#4493]
tests/job_timeout_test.py is failing beginning with commit 6194651695f1822319eb5501c816822b26dfd347. 

```
=================================== FAILURES ===================================
_____________________________ test_myapp_analysis ______________________________
Traceback (most recent call last):
  File "/home/vagrant/src/radiasoft/sirepo/tests/job_timeout_test.py", line 81, in test_myapp_analysis
    pkunit.pkok(r.status_code == 404, 'r={}', r)
  File "/home/vagrant/src/radiasoft/pykern/pykern/pkunit.py", line 339, in pkok
    pkfail(fmt, *args, **kwargs)
  File "/home/vagrant/src/radiasoft/pykern/pykern/pkunit.py", line 305, in pkfail
    raise PKFail('{} {}'.format(call, msg))
pykern.pkunit.PKFail: tests/job_timeout_test.py:81:test_myapp_analysis r=<WrapperTestResponse streamed [200 OK]>
=================== 1 failed, 1 passed in 123.30s (0:02:03) ====================
```

**Comment by mkeilman** [comment]
Yes, a running simulation no longer blocks downloadDataFile. Nice to have independent confirmation that it works ;)

I'll find another way to check for job timeouts
