### ISSUE TITLE
Error: pg_config executable not found.

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#461]
I tried to run `python setup.py test` to test the code, but got the following error:
```bash
[2.7.10;@maximus sirepo]$ python setup.py test
Error: pg_config executable not found.

Please add the directory containing pg_config to the PATH
or specify the full executable path with the option:

    python setup.py build_ext --pg-config /path/to/pg_config build ...

or with the pg_config option in 'setup.cfg'.
Traceback (most recent call last):
  File "setup.py", line 34, in <module>
    'Topic :: Software Development :: Libraries :: Application Frameworks',
  File "/home/vagrant/src/radiasoft/pykern/pykern/pksetup.py", line 328, in setup
    op(**base)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/setuptools/dist.py", line 348, in __init__
    self.fetch_build_eggs(attrs['setup_requires'])
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/setuptools/dist.py", line 394, in fetch_build_eggs
    replace_conflicting=True,
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/pkg_resources/__init__.py", line 826, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1098, in best_match
    return self.obtain(req, installer)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1110, in obtain
    return installer(requirement)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/setuptools/dist.py", line 461, in fetch_build_egg
    return cmd.easy_install(req)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 664, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 694, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 875, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1114, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1102, in run_setup
    raise DistutilsError("Setup script exited with %s" % (v.args[0],))
distutils.errors.DistutilsError: Setup script exited with 1
[2.7.10;@maximus sirepo]$
```
What should be installed? I suppose `pg_config` is from Postgres SQL. Which package do I need to install on my dev machine?

**Comment by mrakitin** [comment]
I followed the suggestion from http://stackoverflow.com/a/14225130/4143531:
```bash
sudo yum install postgresql-libs
sudo yum install postgresql-devel
sudo yum install python-devel
```
After that it worked fine.

**Comment by robnagler** [comment]
You shouldn't need python-devel. Just "yum install -y postgresql-devel"
