### ISSUE TITLE
quieter 404 not found

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/sirepo#4616]
Currently this is what the logs look like when there is a 404

```
../sirepo/uri_router.py:332:_dispatch exception=404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again. path=font-roboto/hMqPNLsu_dywMa4C_DEpY4gp9Q8gbYr\
hqGlRav_IXfk.woff2 stack=Traceback (most recent call last):
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/uri_router.py", line 330, in _dispatch
    return call_api(route, kwargs)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/uri_router.py", line 110, in call_api
    r = sirepo.http_reply.gen_exception(e)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/http_reply.py", line 63, in gen_exception
    return _gen_exception_werkzeug(exc)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/http_reply.py", line 401, in _gen_exception_werkzeug
    raise exc
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/uri_router.py", line 101, in call_api
    r = flask.make_response(getattr(f.cls(), f.func_name)(**kwargs))
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/api.py", line 73, in _wrapper
    return self.func(*args, **kwargs)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/server.py", line 452, in api_root
    sirepo.util.raise_not_found(f"unknown path={path_info}")
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/util.py", line 324, in raise_not_found
    _raise("NotFound", *args, **kwargs)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/util.py", line 418, in _raise
    raise getattr(werkzeug.exceptions, exc)()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

Exception was printed at:

werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/flask/app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
```

This is a lot of noise for a not very interesting error. 

With the addition of juppyter-tensoboard-proxy (radiasoft/container-beamsim-jupyter#64) we are going to see more of these errors because tensorboard assumes /font-roboto is available by the root server (https://github.com/tensorflow/tensorboard/issues/1885).

**Comment by robnagler** [comment]
Fix b3bba2bc0149dbe0a46f977de0c2541006250ae4
