### ISSUE TITLE
test_synergia_data_file failed to complete

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#4633]
___________________________ test_synergia_data_file ____________________________
Traceback (most recent call last):
  File "/home/vagrant/src/radiasoft/sirepo/tests/server_test.py", line 138, in test_synergia_data_file
    pkunit.pkfail("runStatus: failed to complete: {}", run)
  File "/home/vagrant/src/radiasoft/pykern/pykern/pkunit.py", line 355, in pkfail
    raise PKFail("{} {}".format(call, msg))
pykern.pkunit.PKFail: tests/server_test.py:138:test_synergia_data_file runStatus: failed to complete: {'computeJobHash': 'HashIsUnused', 'computeJobSerial': 1658427663, 'computeJobSt\
art': 0, 'computeModel': 'animation', 'dbUpdateTime': 1658427683, 'elapsedTime': 16, 'frameCount': 0, 'jobStatusMessage': 'Entered __create._run', 'lastUpdateTime': 1658427676, 'next\
Request': {'computeJobHash': 'HashIsUnused', 'computeJobSerial': 1658427663, 'computeJobStart': 1658427667, 'report': 'animation', 'simulationId': 'XxKtoLh6', 'simulationType': 'syne\
rgia'}, 'nextRequestSeconds': 2, 'percentComplete': 0, 'state': 'running'}
=============================== warnings summary ============================

**Comment by robnagler** [comment]
______________________ test_elegant_concurrent_sim_frame _______________________
Traceback (most recent call last):
  File "/home/vagrant/src/radiasoft/sirepo/tests/job_concurrency1_test.py", line 146, in test_elegant_concurrent_sim_frame
    pkunit.pkfail("runStatus: failed to complete: {}", r1)

**Comment by robnagler** [comment]
_____________________________ test_myapp_analysis ______________________________
Traceback (most recent call last):
  File "/home/vagrant/src/radiasoft/sirepo/tests/job_timeout_test.py", line 74, in test_myapp_analysis
    r = fc.sr_run_sim(d, "heightWeightReport", expect_completed=True)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/srunit.py", line 494, in sr_run_sim
    r,
  File "/home/vagrant/src/radiasoft/pykern/pykern/pkunit.py", line 389, in pkok
    pkfail(fmt, *args, **kwargs)
  File "/home/vagrant/src/radiasoft/pykern/pykern/pkunit.py", line 355, in pkfail
    raise PKFail("{} {}".format(call, msg))
pykern.pkunit.PKFail: sirepo/srunit.py:494:sr_run_sim nextRequest missing from reply={'state': 'canceled'}
