### ISSUE TITLE
apa19 not handling beta

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#466]
@moellep wrote in #465 : apa19b was not handling long running requests so I stopped celery-sirepo on that server.

Paul, Is this text from apa19? Was there anything in the run log?

```txt
[2016-10-01 23:54:12,139: ERROR/MainProcess] Task sirepo.celery_tasks.start_simulation[69f62de9-067e-4997-9245-7cff53f8d69b] raised unexpected: RuntimeError('error exit(1)',)
Traceback (most recent call last):
File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
R = retval = fun(args, *kwargs)
File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/celery/app/trace.py", line 38, in protected_call
return self.run(args, *kwargs)
File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/sirepo-20160929.5800-py2.7.egg/sirepo/celery_tasks.py", line
95, in start_simulation
output=str(run_dir.join(template_common.RUN_LOG)),
File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/pykern-20160928.212331-py2.7.egg/pykern/pksubprocess.py", line 67, in check_call_with_signals
raise RuntimeError('error exit({})'.format(rc))
RuntimeError: error exit(1)
```

**Comment by bruhwile** [comment]
Not sure if this is related, but I'm getting an error with the partially coherent simulation of the basic CHX beamline on beta. The simulation URL is  https://beta.sirepo.com/srw#/beamline/hX3kFill 

Here's a screenshot of the error:
![image](https://cloud.githubusercontent.com/assets/3825435/19021585/5ee6aefa-8882-11e6-806d-cca12e71a600.png)

**Comment by bruhwile** [comment]
This previous problem doesn't seem to be repeatable.
Maybe I was doing something specific to cause the error.

**Comment by bruhwile** [comment]
Again, not sure if the problem is related to the this issue.
The URL is  https://beta.sirepo.com/srw#/beamline/sv5hBX4C?show_item_id=sv5hBX4C
When I used  cog-wheel --> 'related simulations' --> NCLS-II CHX beamline
I see the error message below:

![image](https://cloud.githubusercontent.com/assets/3825435/19021904/fd49ca9a-8888-11e6-982f-63a793bf9f8f.png)

**Comment by robnagler** [comment]
@moellep I just shutdown apa25 and started apa19, clicked on your link, and it definitely runs:

<img width="438" alt="screen shot 2016-10-03 at 10 44 45 am" src="https://cloud.githubusercontent.com/assets/5495179/19031792/74f59fec-8956-11e6-8817-79d70bf14e94.png">

I verified it is running on the right server.

We have no demos today so I'll leave it on apa19 without apa25 for now so you can check in the am.

**Comment by robnagler** [comment]
I mean I turned off apa14 (not apa25).

**Comment by robnagler** [comment]
@moellep I'm going to turn on apa14 for now, because talk is this afternoon and want both machines online.
