### ISSUE TITLE
py.test: DoctestTextfile' object has no attribute '_request'

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#475]
Running py.test from root results in configuration error of some sort.

``` text
$ py.test
================================= test session starts =================================
platform linux2 -- Python 2.7.10, pytest-2.9.2, py-1.4.31, pluggy-0.3.1
rootdir: /home/vagrant/src/radiasoft/sirepo, inifile:
plugins: xdist-1.14, pykern-20161003.151727
collected 13 items
INTERNALERROR> Traceback (most recent call last):
dir: /home/vagrant/src/radiasoft/sirepo, inifile:INTERNALERROR>   File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/main.py", line 94, in wrap_ses\
sion
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/main.py", line 125, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 724, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 596, in execute
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/main.py", line 150, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 724, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 595, in execute
INTERNALERROR>     return _wrapped_call(hook_impl.function(*args), self.execute)
INTERNALERROR>   File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 253, in _wrapped_call
INTERNALERROR>     return call_outcome.get_result()
INTERNALERROR>   File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 279, in get_result
INTERNALERROR>     _reraise(*ex)  # noqa
INTERNALERROR>   File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 264, in __init__
INTERNALERROR>     self.result = func()
INTERNALERROR>   File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 596, in execute
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/vagrant/src/radiasoft/pykern/pykern/pytest_plugin.py", line 72, in pytest_runtest_protocol
INTERNALERROR>     m = item._request.module
INTERNALERROR> AttributeError: 'DoctestTextfile' object has no attribute '_request'
```

**Comment by robnagler** [comment]
This does not happen for `python setup.py test`

**Comment by robnagler** [comment]
pykern test handles this.
