### ISSUE TITLE
20221025 file error in coherent modes on Young's Double Slit Experiment 

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#4942]
I looked at srwlib.py, and it is possible that `_file_path=fp_cm` is None. I was running on my machine with one core so maybe it's related. Here's the stack from the run.log:

```txt
Coherent Mode Decomposition done in: 45.415 s
Common Quadratic Terms were added to CMs in: 0.015 s
Traceback (most recent call last):
  File "parameters.py", line 231, in <module>
    main()
  File "parameters.py", line 229, in main
    srwl_bl.SRWLBeamline(_name=v.name).calc_all(v, op)
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/srwl_bl.py", line 3173, in calc_all
    _cm_wfr = lstWfrCM) #OC02072021
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/srwl_bl.py", line 1951, in calc_wfr_emit_prop_me
    _file_bkp = _fbk, _rand_opt = _op_rnd, _file_form = _fform, _n_mpi=_nmm, _n_cm=_ncm) #OC27062021
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/srwlib.py", line 10386, in srwl_wfr_emit_prop_multi_e
    srwl_uti_save_wfr_cm_hdf5(cohModes, None, _awfr=wfrA, _file_path=fp_cm) #OC28062021
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/srwlib.py", line 6828, in srwl_uti_save_wfr_cm_hdf5
    with h5.File(_file_path, 'w') as hf:
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/h5py/_hl/files.py", line 395, in __init__
    name = filename_encode(name)
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/h5py/_hl/compat.py", line 111, in filename_encode
    filename = fspath(filename)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by moellep** [comment]
The coherent modes simulation only works with >= 3 cores, otherwise it will go down the wrong path in srw.

I'd like that simulation to fail with an error, "Coherent Modes requires 3 or more cores to run", but I don't want it to fail on the code-generation side, just the running side.

I don't see how the parallel case is being handled for srw - there is no pkcli.srw run_background, so I don't know the appropriate place to add this assertion.

**Comment by robnagler** [comment]
It looks like `simState.sbatchCores` will be set by the directive sbatchOptions (sirepo-components.js). That would need to be checked although unlikely to be less than 32. 

Otherwise, simulation_db.JOB_RUN_MODE_MAP is used which is returned in authState.jobRunModeMap. This tells you how many cores are available in SMP.

When you click Simulate, it would need to check these in the UI. I'm not sure where that is.

**Comment by robnagler** [comment]
@gurhar1133 since you worked on this recently. We want to get an error in the UI when someone tries to connect run coherent modes with fewer than 3 cores.
