### ISSUE TITLE
20221026 built-in extruded shapes do not appear in workspace

### ISSUE THREAD

**Issue by mkeilman** [radiasoft/sirepo#5013]
When these objects are dragged in they don't appear in the workspace, and a javascript error gets thrown:
```javascript
TypeError: Cannot read properties of undefined (reading 'length')
    at self.updateExtrudedSize (radia.js?20221018.184701:170:31)
    at self.updateExtruded (radia.js?20221018.184701:165:14)
    at radia.js?20221018.184701:4037:26
    at m.$broadcast (angular.js:19720:15)
    at broadcastChanged (sirepo.js?20221018.184701:338:20)
    at self.saveChanges (sirepo.js?20221018.184701:797:13)
    at $scope.saveChanges (sirepo-components.js?20221018.184701:352:30)
    at fn (eval at compile (angular.js:16418:15), <anonymous>:4:153)
    at e (angular.js:28951:13)
    at m.$eval (angular.js:19393:16)
```
The object does appear in the visualization tab, so this is strictly an error in the designer.

**Comment by mkeilman** [comment]
Fixed by #4997
