### ISSUE TITLE
20221026: job agent unable to open auth.db

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/sirepo#5017]
Seeing this on alpha
```
15:40:08 sirepo/pkcli/job_agent.py:209:loop error=(sqlite3.OperationalError) unable to open database file
15:40:08 (Background on this error at: https://sqlalche.me/e/14/e3q8) stack=Traceback (most recent call last):
15:40:08 sqlalchemy/engine/base.py", line 3361, in _wrap_pool_connect
15:40:08     return fn()
15:40:08 sqlalchemy/pool/base.py", line 320, in connect
15:40:08     return _ConnectionFairy._checkout(self)
15:40:08 sqlalchemy/pool/base.py", line 884, in _checkout
15:40:08     fairy = _ConnectionRecord.checkout(pool)
15:40:08 sqlalchemy/pool/base.py", line 486, in checkout
15:40:08     rec = pool._do_get()
15:40:08 sqlalchemy/pool/impl.py", line 256, in _do_get
15:40:08     return self._create_connection()
15:40:08 sqlalchemy/pool/base.py", line 266, in _create_connection
15:40:08     return _ConnectionRecord(self)
15:40:08 sqlalchemy/pool/base.py", line 381, in __init__
15:40:08     self.__connect()
15:40:08 sqlalchemy/pool/base.py", line 678, in __connect
15:40:08     pool.logger.debug("Error on connect(): %s", e)
15:40:08 sqlalchemy/util/langhelpers.py", line 72, in __exit__
15:40:08     with_traceback=exc_tb,
15:40:08 sqlalchemy/util/compat.py", line 208, in raise_
15:40:08     raise exception
15:40:08 sqlalchemy/pool/base.py", line 673, in __connect
15:40:08     self.dbapi_connection = connection = pool._invoke_creator(self)
15:40:08 sqlalchemy/engine/create.py", line 578, in connect
15:40:08     return dialect.connect(*cargs, **cparams)
15:40:08 sqlalchemy/engine/default.py", line 598, in connect
15:40:08     return self.dbapi.connect(*cargs, **cparams)
15:40:08 sqlite3.OperationalError: unable to open database file
15:40:08
15:40:08 The above exception was the direct cause of the following exception:
15:40:08
15:40:08 Traceback (most recent call last):
15:40:08 sirepo/pkcli/job_agent.py", line 206, in loop
15:40:08     with sirepo.quest.start():
15:40:08   File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/contextlib.py", line 112, in __enter__
15:40:08     return next(self.gen)
15:40:08 sirepo/quest.py", line 44, in start
15:40:08     auth = sirepo.modules.import_and_init("sirepo.auth")
15:40:08 sirepo/modules.py", line 35, in import_and_init
15:40:08     _i("sirepo.auth_db", [])
15:40:08 sirepo/modules.py", line 24, in _i
15:40:08     m.init_module(**{k: values[k] for k in kw})
15:40:08 sirepo/auth_db.py", line 422, in init_module
15:40:08     b.metadata.create_all(_engine)
15:40:08 sqlalchemy/sql/schema.py", line 4918, in create_all
15:40:08     ddl.SchemaGenerator, self, checkfirst=checkfirst, tables=tables
15:40:08 sqlalchemy/engine/base.py", line 3227, in _run_ddl_visitor
15:40:08     with self.begin() as conn:
15:40:08 sqlalchemy/engine/base.py", line 3143, in begin
15:40:08     conn = self.connect(close_with_result=close_with_result)
15:40:08 sqlalchemy/engine/base.py", line 3315, in connect
15:40:08     return self._connection_cls(self, close_with_result=close_with_result)
15:40:08 sqlalchemy/engine/base.py", line 96, in __init__
15:40:08     else engine.raw_connection()
15:40:08 sqlalchemy/engine/base.py", line 3394, in raw_connection
15:40:08     return self._wrap_pool_connect(self.pool.connect, _connection)
15:40:08 sqlalchemy/engine/base.py", line 3365, in _wrap_pool_connect
15:40:08     e, dialect, self
15:40:08 sqlalchemy/engine/base.py", line 2199, in _handle_dbapi_exception_noconnection
15:40:08     sqlalchemy_exception, with_traceback=exc_info[2], from_=e
15:40:08 sqlalchemy/util/compat.py", line 208, in raise_
15:40:08     raise exception
15:40:08 sqlalchemy/engine/base.py", line 3361, in _wrap_pool_connect
15:40:08     return fn()
15:40:08 sqlalchemy/pool/base.py", line 320, in connect
15:40:08     return _ConnectionFairy._checkout(self)
15:40:08 sqlalchemy/pool/base.py", line 884, in _checkout
15:40:08     fairy = _ConnectionRecord.checkout(pool)
15:40:08 sqlalchemy/pool/base.py", line 486, in checkout
15:40:08     rec = pool._do_get()
15:40:08 sqlalchemy/pool/impl.py", line 256, in _do_get
15:40:08     return self._create_connection()
15:40:08 sqlalchemy/pool/base.py", line 266, in _create_connection
15:40:08     return _ConnectionRecord(self)
15:40:08 sqlalchemy/pool/base.py", line 381, in __init__
15:40:08     self.__connect()
15:40:08 sqlalchemy/pool/base.py", line 678, in __connect
15:40:08     pool.logger.debug("Error on connect(): %s", e)
15:40:08 sqlalchemy/util/langhelpers.py", line 72, in __exit__
15:40:08     with_traceback=exc_tb,
15:40:08 sqlalchemy/util/compat.py", line 208, in raise_
15:40:08     raise exception
15:40:08 sqlalchemy/pool/base.py", line 673, in __connect
15:40:08     self.dbapi_connection = connection = pool._invoke_creator(self)
15:40:08 sqlalchemy/engine/create.py", line 578, in connect
15:40:08     return dialect.connect(*cargs, **cparams)
15:40:08 sqlalchemy/engine/default.py", line 598, in connect
15:40:08     return self.dbapi.connect(*cargs, **cparams)
15:40:08 sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
15:40:08 (Background on this error at: https://sqlalche.me/e/14/e3q8)
15:40:08
15:40:08 Exception was printed at:
15:40:08
15:40:08 sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
15:40:08 (Background on this error at: https://sqlalche.me/e/14/e3q8)
15:40:08   File "/home/vagrant/.pyenv/versions/py3/bin/sirepo", line 8, in <module>
15:40:08     sys.exit(main())
15:40:08 sirepo/sirepo_console.py", line 18, in main
15:40:08     return pkcli.main("sirepo")
15:40:08 pykern/pkcli/__init__.py", line 157, in main
15:40:08     res = argh.dispatch(parser, argv=argv)
15:40:08   File "/home/vagrant/.pyenv/versions/3.7.2/envs/p<SNIP>
```

I don't think the job_agent should be opening auth.db. It can't in docker because it isn't mounted.

**Comment by e-carlin** [comment]
Seeing this as well
```
15:51:26 sirepo/pkcli/job_agent.py:209:loop error=[Permission denied]: mkdir('/<snip>/supervisor-srv',) stack=Traceback (most recent call last):
15:51:26 py/_error.py", line 66, in checked_call
15:51:26     return func(*args, **kwargs)
15:51:26 PermissionError: [Errno 13] Permission denied: '/<snip>/supervisor-srv'
15:51:26
15:51:26 During handling of the above exception, another exception occurred:
15:51:26
15:51:26 Traceback (most recent call last):
15:51:26 sirepo/pkcli/job_agent.py", line 206, in loop
15:51:26     with sirepo.quest.start():
15:51:26   File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/contextlib.py", line 112, in __enter__
15:51:26     return next(self.gen)
15:51:26 sirepo/quest.py", line 44, in start
15:51:26     auth = sirepo.modules.import_and_init("sirepo.auth")
15:51:26 sirepo/modules.py", line 39, in import_and_init
15:51:26     m = _i("sirepo.uri_router", ["want_apis", "simulation_db"])
15:51:26 sirepo/modules.py", line 24, in _i
15:51:26     m.init_module(**{k: values[k] for k in kw})
15:51:26 sirepo/uri_router.py", line 136, in init_module
15:51:26     register_api_module("sirepo." + n)
15:51:26 sirepo/uri_router.py", line 173, in register_api_module
15:51:26     m.init_apis(uri_router=pkinspect.this_module())
15:51:26 sirepo/job_api.py", line 340, in init_apis
15:51:26     pykern.pkio.mkdir_parent(sirepo.job.LIB_FILE_ROOT)
15:51:26 pykern/pkio.py", line 105, in mkdir_parent
15:51:26     return py_path(path).ensure(dir=True)
15:51:26 py/_path/local.py", line 538, in ensure
15:51:26     return p._ensuredirs()
15:51:26 py/_path/local.py", line 520, in _ensuredirs
15:51:26     parent._ensuredirs()
15:51:26 py/_path/local.py", line 523, in _ensuredirs
15:51:26     self.mkdir()
15:51:26 py/_path/local.py", line 473, in mkdir
15:51:26     py.error.checked_call(os.mkdir, fspath(p))
15:51:26 py/_error.py", line 86, in checked_call
15:51:26     raise cls("%s%r" % (func.__name__, args))
15:51:26 py.error.EACCES: [Permission denied]: mkdir('/<snip>/supervisor-srv',)
```
