### ISSUE TITLE
Serial did not increase

### ISSUE THREAD

**Issue by mkeilman** [radiasoft/sirepo#5114]
I've recently been seeing a lot of these error popping up, seemingly at random:
```python
Nov 11 03:38:53 405220   422 ../sirepo/uri_router.py:280:_call_api api=saveSimulationData exception=1668137933336940: serial did not increase: prev=1668137933819117 stack=Traceback (most recent call last):
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/uri_router.py", line 274, in _call_api
    r = _response(getattr(qcall, qcall.uri_route.func_name)(**kwargs))
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/quest.py", line 312, in _wrapper
    return self.func(*args, **kwargs)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/server.py", line 492, in api_saveSimulationData
    simulation_db.save_simulation_json(d, fixup=True, modified=True),
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/simulation_db.py", line 578, in save_simulation_json
    s.simulationSerial = _serial_new()
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/simulation_db.py", line 1068, in _serial_new
    res, _serial_prev
AssertionError: 1668137933336940: serial did not increase: prev=1668137933819117
```
The errors clear up on their own but break the save that started things off. Again seems recent and may be hard to reproduce on purpose...

**Comment by robnagler** [comment]
Time is flowing backwards on your VM or there are multiple threads active and there's a very strange race condition. One thing you could do is move `res = int(time.time() * 1000000)` inside the lock. This tests the first possibility (time flowing backwards).

**Comment by mkeilman** [comment]
I tend to let the vm run until I have a specific need to restart it - a restart seems to have cured this. I'll close this and make a note to restart if the issue recurs.
