### ISSUE TITLE
sirepo test failures preventing beamsim from being built

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/sirepo#5230]
I saw the below errors, ran the build again, and saw the same error

```
___________________________________ test_srw ___________________________________
Traceback (most recent call last):
  File "/home/vagrant/src/radiasoft/sirepo/tests/job_timeout_test.py", line 51, in test_srw
    r = fc.sr_post("runStatus", r.nextRequest)
  File "/home/vagrant/src/radiasoft/pykern/pykern/pkcollections.py", line 69, in __getattr__
    f"'{type(self).__name__}' object has no attribute '{name}'"
AttributeError: 'PKDict' object has no attribute 'nextRequest'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vagrant/src/radiasoft/sirepo/tests/job_timeout_test.py", line 66, in test_srw
    raise AssertionError("cancel failed")
AssertionError: cancel failed
_____________________________ test_myapp_analysis ______________________________
Traceback (most recent call last):
  File "/home/vagrant/src/radiasoft/sirepo/tests/job_timeout_test.py", line 76, in test_myapp_analysis
    r = fc.sr_run_sim(d, "heightWeightReport", expect_completed=True)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/srunit.py", line 524, in sr_run_sim
    raise AssertionError("cancel failed")
AssertionError: cancel failed
```

**Comment by e-carlin** [comment]
May be related to https://github.com/radiasoft/download/pull/387 . Seeing "no module sklearn" in the logs.

**Comment by e-carlin** [comment]
Yes. The latest rscode-ml was built in fedora 32 repo but using python 3.10. Moving to download
