### ISSUE TITLE
fedora36: silas two mirrors example laser cavity simulation doesn't work

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/sirepo#5275]
```bash
[py3;@v4 animation]$ cat run.log
L_eff= 7.99
beta0= 2.830189922955701
sigx0= 0.00042444378460500373
Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/py3/bin/sirepo", line 33, in <module>
    sys.exit(load_entry_point('sirepo', 'console_scripts', 'sirepo')())
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/sirepo_console.py", line 18, in main
    return pkcli.main("sirepo")
  File "/home/vagrant/src/radiasoft/pykern/pykern/pkcli/__init__.py", line 158, in main
    res = argh.dispatch(parser, argv=argv)
  File "/home/vagrant/.pyenv/versions/3.10.5/envs/py3/lib/python3.10/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/home/vagrant/.pyenv/versions/3.10.5/envs/py3/lib/python3.10/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/home/vagrant/.pyenv/versions/3.10.5/envs/py3/lib/python3.10/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/pkcli/silas.py", line 23, in run_background
    template_common.exec_parameters()
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/template/template_common.py", line 376, in exec_parameters
    return pkrunpy.run_path_as_module(path or PARAMETERS_PYTHON_FILE)
  File "/home/vagrant/src/radiasoft/pykern/pykern/pkrunpy.py", line 28, in run_path_as_module
    exec(code, m.__dict__)
  File "parameters.py", line 113, in <module>
    lc = laser_cavity.LaserCavity(cavity_inputs)
  File "/home/vagrant/.pyenv/versions/3.10.5/envs/py3/lib/python3.10/site-packages/rslaser/cavity/laser_cavity.py", line 50, in __init__
    self.laser_pulse = pulse.LaserPulse(params.pulse_params)
  File "/home/vagrant/.pyenv/versions/3.10.5/envs/py3/lib/python3.10/site-packages/rslaser/pulse/pulse.py", line 117, in __init__
    self.sigx_waist = params.slice_params.sigx_waist
  File "/home/vagrant/src/radiasoft/pykern/pykern/pkcollections.py", line 68, in __getattr__
    raise AttributeError(
AttributeError: 'PKDict' object has no attribute 'sigx_waist'
```

**Comment by moellep** [comment]
I think the silas API has been changed quite a bit and the sirepo app hasn't been updated.

**Comment by e-carlin** [comment]
Thanks Paul. We decided we aren't going to fix this now.
