### ISSUE TITLE
20221221 Python export fails for simulations with material or stl files

### ISSUE THREAD

**Issue by mkeilman** [radiasoft/sirepo#5286]
The error is
```bash
Dec 17 15:34:26 81345   320 ../sirepo/uri_router.py:284:_call_api api=pythonSource exception=uid not supplied and no logged_in_user config stack=Traceback (most recent call last):
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/uri_router.py", line 275, in _call_api
    r = _response(getattr(qcall, qcall.uri_route.func_name)(**kwargs))
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/quest.py", line 289, in _wrapper
    return self.func(*args, **kwargs)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/server.py", line 428, in api_pythonSource
    req.template.python_source_for_model(d, model=m, qcall=self),
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/template/radia.py", line 356, in python_source_for_model
    return _generate_parameters_file(data, False, for_export=True, qcall=qcall)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/template/radia.py", line 920, in _generate_parameters_file
    width_dir=dirs.width_dir,
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/template/radia.py", line 1523, in _update_geom_from_freehand
    _update_geom_objects(geom_objs)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/template/radia.py", line 1656, in _update_geom_objects
    _update_geom_obj(o)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/template/radia.py", line 1704, in _update_geom_obj
    _SIM_DATA.lib_file_name_with_type(o.file, SCHEMA.constants.fileTypeSTL)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/sim_data/__init__.py", line 343, in lib_file_abspath
    p = cls._lib_file_abspath(basename, data=data, qcall=qcall)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/sim_data/__init__.py", line 740, in _lib_file_abspath
    qcall=qcall,
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/simulation_db.py", line 666, in simulation_lib_dir
    return simulation_dir(simulation_type, qcall=qcall).join(_LIB_DIR)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/simulation_db.py", line 646, in simulation_dir
    p = user_path(qcall=qcall)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/simulation_db.py", line 777, in user_path
    uid = _uid_arg(uid, qcall)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/simulation_db.py", line 1102, in _uid_arg
    assert uid, "uid not supplied and no logged_in_user config"
AssertionError: uid not supplied and no logged_in_user config
```

**Comment by mkeilman** [comment]
Came across this while investigating #5283
