### ISSUE TITLE
SRW: main python export for gaussian beam broken

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#531]
When exporting SRW python source from the simulations page, gaussian beam simulations generate code which will crash because non-gaussian reports are included.

**Comment by mrakitin** [comment]
I think the problem is more general and affects the electron beams. I'm trying to run the exported Undulator Radiation script with all the reports included, and get the following error:
```py
> python Undulator_Radiation.py
Electron trajectory calculation ... completed
Saving trajectory data to a file ... completed
Single-electron SR calculation ... completed (lasted 3.296914 s)
Extracting intensity and saving it to a file ... completed (lasted 0.025036 s)
Single-electron SR calculation ... completed (lasted 1.355639 s)
Extracting intensity and saving it to a file ... completed (lasted 0.028076 s)
Propagation ... Traceback (most recent call last):
  File "Undulator_Radiation.py", line 218, in <module>
    main()
  File "Undulator_Radiation.py", line 214, in main
    srwl_bl.SRWLBeamline(_name=v.name, _mag_approx=mag).calc_all(v, op)
  File "C:\bin\mrakitin\SRW\env\work\srw_python\srwl_bl.py", line 1665, in calc_all
    _fname = os.path.join(_v.fdir, _v.ws_fni) if(len(_v.ws_fni) > 0) else '')
  File "C:\bin\mrakitin\SRW\env\work\srw_python\srwl_bl.py", line 1183, in calc_wfr_prop
    srwl.PropagElecField(_wfr, self.optics)
RuntimeError: No objects were submitted for parsing
```

**Comment by mrakitin** [comment]
Some simulation reports can only accept `None` instead of the `set_optics()` return. Need to correct it.
