### ISSUE TITLE
SRW - partially-coherent calculation with Sample fails

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#538]
```python
Traceback (most recent call last):
  File "mpi_run.py", line 231, in <module>
    main()
  File "mpi_run.py", line 224, in main
    op = set_optics(v)
  File "mpi_run.py", line 34, in set_optics
    prefix='op_sample1'))
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/srwl_samples.py", line 161, in srwl_opt_setup_transmission_from_file
    prefix=prefix,
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/srwl_samples.py", line 54, in __init__
    self._check_files()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/srwl_samples.py", line 117, in _check_files
    raise ValueError('Provided file "{}" does not exist.'.format(self.file_path))
ValueError: Provided file "R5.tif" does not exist.
```

**Comment by mrakitin** [comment]
The error is fixed in 7e6c688. The calculation starts fine now, but fails later when it's trying to write the data file after averaging of 20 particles. It's the problem with the configuration of the simulation. When I reduced the sampling factor to 0.3, it worked fine.
