### ISSUE TITLE
Cannot access simulations when invalid simulation in directory

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#54]
Unable to see simulations when there is a symlink in the simulations directory. I think the code should ignore symlinks with invalid simulation ids. I use those to mark simulations easily.

```text
RuntimeError: lineout-incorrect: invalid simulation id
[2016-01-26 13:39:22,379] {/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py:1423} ERROR - Exception on /simulation-list [POST]
Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/sirepo-20160122.175403-py2.7.egg/sirepo/server.py", line 424, in app_simulation_list
    _iterate_simulation_datafiles(simulation_type, _process_simulation_list, search),
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/sirepo-20160122.175403-py2.7.egg/sirepo/server.py", line 564, in _iterate_simulation_datafiles
    op(res, path, data)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/sirepo-20160122.175403-py2.7.egg/sirepo/server.py", line 600, in _process_simulation_list
    'simulationId': _sid_from_path(path),
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/sirepo-20160122.175403-py2.7.egg/sirepo/server.py", line 714, in _sid_from_path
    raise RuntimeError('{}: invalid simulation id'.format(sid))
RuntimeError: lineout-incorrect: invalid simulation id
```

**Comment by robnagler** [comment]
I think this is fixed, and the code is more stable around reading invalid data. It just marks simulation in an error and will re-run.
