### ISSUE TITLE
auth_role_moderation_test.py failing with sqlalchemy 2.0

### ISSUE THREAD

**Issue by rorour** [radiasoft/sirepo#5435]
```
127.0.0.1 - - [27/Jan/2023 19:13:18] "POST /get-moderation-request-rows HTTP/1.1" 403 -
127.0.0.1 - - [27/Jan/2023 19:13:18] "GET /auth-state HTTP/1.1" 200 -
Jan 27 19:13:18 16921    15 ../../../sirepo/uri_router.py:273:_call_api api=getModerationRequestRows exception=keys stack=Traceback (most recent call last):
  File "lib/sqlalchemy/cyextension/resultproxy.pyx", line 71, in sqlalchemy.cyextension.resultproxy.BaseRow._get_by_key_impl_mapping
KeyError: 'keys'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "lib/sqlalchemy/cyextension/resultproxy.pyx", line 88, in sqlalchemy.cyextension.resultproxy.BaseRow.__getattr__
  File "lib/sqlalchemy/cyextension/resultproxy.pyx", line 73, in sqlalchemy.cyextension.resultproxy.BaseRow._get_by_key_impl_mapping
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sqlalchemy/engine/result.py", line 134, in _key_fallback
    raise KeyError(key) from err
KeyError: 'keys'

```

**Comment by robnagler** [comment]
Pin version 1.4.1. 2.0 has a lot of big changes.

**Comment by robnagler** [comment]
This is how I fixed it for my current PR: https://github.com/radiasoft/sirepo/pull/5436/commits/947b68b71047c3368b8835be49f2a0e2d20cff4b
