### ISSUE TITLE
Celery doesn't stop job properly

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#55]
I had ended the simulation in the UI, and you can see from the log that the task exited. However, the master seems to think it is running and after two hours (not 3600s?) it stops the job for exceeding the time limit. 

Need to do research on how to properly exit a job in celery (what signal to catch?) and how to let he master know that it's really dead.

```text
[2016-01-28 02:16:27,306: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2016-01-28 02:16:27,328: INFO/MainProcess] mingle: searching for neighbors
[2016-01-28 02:16:28,344: INFO/MainProcess] mingle: all alone
[2016-01-28 02:16:28,408: WARNING/MainProcess] celery@v ready.
[2016-01-28 02:17:09,896: INFO/MainProcess] Received task: sirepo.celery_tasks.start_simulation[108b3e4f-8c9e-405a-8370-3181b27cdeab]
[2016-01-28 02:17:23,086: INFO/MainProcess] Terminating 108b3e4f-8c9e-405a-8370-3181b27cdeab (15)
[2016-01-28 02:17:25,187: WARNING/Worker-1] Traceback (most recent call last):
[2016-01-28 02:17:25,187: WARNING/Worker-1] File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/srwlib.py", line 3530, in srwl_wfr_emit_prop_multi_e
[2016-01-28 02:17:25,188: WARNING/Worker-1] srwl.CalcElecFieldSR(wfr, 0, _mag, arPrecParSR) #calculate Electric Field emitted by current electron
[2016-01-28 02:17:25,188: WARNING/Worker-1] File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/billiard/common.py", line 95, in _shutdown_cleanup
[2016-01-28 02:17:25,188: WARNING/Worker-1] sys.exit(-(256 - signum))
[2016-01-28 02:17:25,188: WARNING/Worker-1] File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/billiard/pool.py", line 286, in exit
[2016-01-28 02:17:25,188: WARNING/Worker-1] return _exit()
[2016-01-28 02:17:25,189: WARNING/Worker-1] SystemExit
[2016-01-28 04:20:25,731: ERROR/MainProcess] Task sirepo.celery_tasks.start_simulation[108b3e4f-8c9e-405a-8370-3181b27cdeab] raised unexpected: TimeLimitExceeded(3600,)
Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/billiard/pool.py", line 645, in on_hard_timeout
    raise TimeLimitExceeded(job._timeout)
TimeLimitExceeded: TimeLimitExceeded(3600,)
[2016-01-28 04:20:25,734: ERROR/MainProcess] Hard time limit (3600s) exceeded for sirepo.celery_tasks.start_simulation[108b3e4f-8c9e-405a-8370-3181b27cdeab]
```

**Comment by robnagler** [comment]
Fix 8e7b244
