### ISSUE TITLE
react build unable to load simulation: undefined variable error

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#5544]
```
react-dom.production.min.js:189 Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at ks (react-dom.production.min.js:303:64)
    at e (react-dom.production.min.js:161:400)
    at Lo (react-dom.production.min.js:192:308)
    at Bc (react-dom.production.min.js:296:369)
    at vs (react-dom.production.min.js:280:389)
    at ms (react-dom.production.min.js:280:320)
    at ps (react-dom.production.min.js:280:180)
    at as (react-dom.production.min.js:271:88)
    at As (react-dom.production.min.js:268:429)
    at w (scheduler.production.min.js:13:203)
fo @ react-dom.production.min.js:189
t.callback @ react-dom.production.min.js:189
Pa @ react-dom.production.min.js:144
Hc @ react-dom.production.min.js:262
vc @ react-dom.production.min.js:260
gc @ react-dom.production.min.js:259
(anonymous) @ react-dom.production.min.js:283
Ls @ react-dom.production.min.js:281
As @ react-dom.production.min.js:270
w @ scheduler.production.min.js:13
S @ scheduler.production.min.js:14
react-dom.production.min.js:303 Uncaught Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at ks (react-dom.production.min.js:303:64)
    at e (react-dom.production.min.js:161:400)
    at Lo (react-dom.production.min.js:192:308)
    at Bc (react-dom.production.min.js:296:369)
    at vs (react-dom.production.min.js:280:389)
    at ms (react-dom.production.min.js:280:320)
    at ps (react-dom.production.min.js:280:180)
    at as (react-dom.production.min.js:271:88)
    at As (react-dom.production.min.js:268:429)
    at w (scheduler.production.min.js:13:203)
```

**Comment by garsuga** [comment]
This ended up being a really weird error. I got lucky searching for it by removing views one by one in myapp. Turns out the syntax `<this.SomeComponent>` in JSX works for the dev version but fails for the build version. It felt weird writing it and it technically breaks some JSX rules anyways but it's still definitely a React/Typescript bug. The fix is to just unpack that call into a temporary variable first.
```tsx
// instead of
<this.SomeComponent/>

// use
let Comp = this.SomeComponent
<Comp/>
```
