### ISSUE TITLE
react bundle Throttling navigation to prevent the browser from hanging.

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#5546]
The browser consumes cpu when react run from bundle where files are pip installed  (not pip install -e):

`history.ts:561 Throttling navigation to prevent the browser from hanging. See https://crbug.com/1038223. Command line switch --disable-ipc-flooding-protection can be used to bypass the protection`

This is the only history.ts in the repo: ./node_modules/@remix-run/router/history.ts

**Comment by garsuga** [comment]
Can you attempt to recreate this with the changes made to your branch now? I am not sure how I would recreate this.

**Comment by robnagler** [comment]
The pip install is a red herring. Happens with normal pip install -e. 

Visit http://v.radia.run:8000/jspec and it starts happening. I don't have to click on Simulations. 

I tried a hard refresh, and interestingly it redirects to http://v.radia.run:8000/jspec/ which gets an error on the  server:

```txt
10.10.10.1 - - [08/Mar/2023 01:38:44] "GET /auth-state2 HTTP/1.1" 200 -
../sirepo/uri_router.py:321:_call_api api=root exception=empty component in uri=react/jspec/ stack=Traceback (most recent call last):
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/uri_router.py", line 311, in _call_api
    getattr(qcall, qcall.uri_route.func_name)(**kwargs),
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/quest.py", line 287, in _wrapper
    return self.func(*args, **kwargs)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/server.py", line 499, in api_root
    self._proxy_react(path_info)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/server.py", line 742, in _proxy_react
    _build() if cfg.react_server == _REACT_SERVER_BUILD else _dev()
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/server.py", line 724, in _build
    sirepo.resource.static(sirepo.util.validate_path(f"react/{p}")),
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/util.py", line 479, in validate_path
    raise AssertionError(f"empty component in uri={uri}")
AssertionError: empty component in uri=react/jspec/

Exception was printed at:

AssertionError: empty component in uri=react/jspec/
  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/werkzeug/serving.py", line 347, in handle
    BaseHTTPRequestHandler.handle(self)
  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/werkzeug/serving.py", line 379, in handle_one_request
    self.run_wsgi()
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/werkzeug/serving.py", line 324, in run_wsgi
    execute(self.server.app)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/werkzeug/serving.py", line 313, in execute
    application_iter = app(environ, start_response)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/flask/app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/uri_router.py", line 371, in _flask_dispatch
    reply_op=lambda r: r.flask_response(_app.response_class),
../sirepo/reply.py:540:_gen_exception_error unsupported exception=<class 'AssertionError'> msg=empty component in uri=react/jspec/
```

Here's the javascript message:


```txt
history.ts:561 Throttling navigation to prevent the browser from hanging. See https://crbug.com/1038223. Command line switch --disable-ipc-flooding-protection can be used to bypass the protection
push @ history.ts:561
history.ts:561 Throttling navigation to prevent the browser from hanging. See https://crbug.com/1038223. Command line switch --disable-ipc-flooding-protection can be used to bypass the protection
push @ history.ts:561
(anonymous) @ hooks.tsx:240
(anonymous) @ components.tsx:214
rc @ react-dom.production.min.js:244
ws @ react-dom.production.min.js:286
(anonymous) @ react-dom.production.min.js:282
w @ scheduler.production.min.js:13
S @ scheduler.production.min.js:14
```

**Comment by robnagler** [comment]
On Safari, visiting /jspec renders the page and then redirects automatically to /jspec/ which gets an error:

```txt
10.10.10.1 - - [08/Mar/2023 01:43:37] "^[[36mGET /jspec HTTP/1.1^[[0m" 304 -
10.10.10.1 - - [08/Mar/2023 01:43:37] "^[[36mGET /favicon.ico HTTP/1.1^[[0m" 304 -
10.10.10.1 - - [08/Mar/2023 01:43:37] "^[[36mGET /static/css/main.cd2ba4b8.css HTTP/1.1^[[0m" 304 -
10.10.10.1 - - [08/Mar/2023 01:43:37] "^[[36mGET /manifest.json HTTP/1.1^[[0m" 304 -
10.10.10.1 - - [08/Mar/2023 01:43:37] "^[[36mGET /react/img/sirepo.gif HTTP/1.1^[[0m" 304 -
10.10.10.1 - - [08/Mar/2023 01:43:37] "^[[36mGET /static/svg/slack.svg HTTP/1.1^[[0m" 304 -
10.10.10.1 - - [08/Mar/2023 01:43:37] "^[[36mGET /static/js/main.9758139a.js HTTP/1.1^[[0m" 304 -
10.10.10.1 - - [08/Mar/2023 01:43:37] "^[[36mGET /static/react-json/common-schema.json HTTP/1.1^[[0m" 304 -
10.10.10.1 - - [08/Mar/2023 01:43:37] "^[[36mGET /static/react-json/jspec-schema.json HTTP/1.1^[[0m" 304 -
10.10.10.1 - - [08/Mar/2023 01:43:37] "^[[36mGET /static/react-json/common-schema.json HTTP/1.1^[[0m" 304 -
10.10.10.1 - - [08/Mar/2023 01:43:37] "^[[36mGET /static/react-json/jspec-schema.json HTTP/1.1^[[0m" 304 -
10.10.10.1 - - [08/Mar/2023 01:43:37] "GET /auth-state2 HTTP/1.1" 200 -
10.10.10.1 - - [08/Mar/2023 01:43:37] "GET /auth-state2 HTTP/1.1" 200 -
../sirepo/uri_router.py:321:_call_api api=root exception=empty component in uri=react/jspec/ stack=Traceback (most recent call last):
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/uri_router.py", line 311, in _call_api
    getattr(qcall, qcall.uri_route.func_name)(**kwargs),
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/quest.py", line 287, in _wrapper
    return self.func(*args, **kwargs)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/server.py", line 499, in api_root
    self._proxy_react(path_info)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/server.py", line 742, in _proxy_react
    _build() if cfg.react_server == _REACT_SERVER_BUILD else _dev()
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/server.py", line 724, in _build
    sirepo.resource.static(sirepo.util.validate_path(f"react/{p}")),
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/util.py", line 479, in validate_path
    raise AssertionError(f"empty component in uri={uri}")
AssertionError: empty component in uri=react/jspec/

Exception was printed at:

AssertionError: empty component in uri=react/jspec/
  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/werkzeug/serving.py", line 347, in handle
    BaseHTTPRequestHandler.handle(self)
  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/werkzeug/serving.py", line 379, in handle_one_request
    self.run_wsgi()
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/werkzeug/serving.py", line 324, in run_wsgi
    execute(self.server.app)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/werkzeug/serving.py", line 313, in execute
    application_iter = app(environ, start_response)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/flask/app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/uri_router.py", line 371, in _flask_dispatch
    reply_op=lambda r: r.flask_response(_app.response_class),
../sirepo/reply.py:540:_gen_exception_error unsupported exception=<class 'AssertionError'> msg=empty component in uri=react/jspec/
10.10.10.1 - - [08/Mar/2023 01:43:39] "GET /jspec/ HTTP/1.1" 200 -
10.10.10.1 - - [08/Mar/2023 01:43:39] "GET / HTTP/1.1" 200 -
```
