### ISSUE TITLE
SRW - unpleasant error causing simulations to hang

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#563]
During today's simulations of the custom beamline layout @ochubar and me met this unpleasant error:
```py
../sirepo/server.py:780:_simulation_run_status k7ZiqAMr-WQIHhwEp-watchpointReport13: parametersChanged=True req_hash=20ae8de2ab50d2b7e2619f99e4deffa6 cached_hash=ab8111b721
8b1c613ea636d0a2765ac1
../sirepo/simulation_db.py:592:report_info /home/vagrant/src/radiasoft/sirepo/run/user/k7ZiqAMr/srw/WQIHhwEp/watchpointReport13: ignore IOError: [Errno 2] No such file or d
irectory: '/home/vagrant/src/radiasoft/sirepo/run/user/k7ZiqAMr/srw/WQIHhwEp/watchpointReport13/in.json' errno=2
../sirepo/server.py:700:_simulation_error /home/vagrant/src/radiasoft/sirepo/run/user/k7ZiqAMr/srw/WQIHhwEp/watchpointReport13/in.json: error: input file not found, but job
 is running
10.0.2.2 - - [02/Dec/2016 22:03:12] "POST /run-simulation HTTP/1.1" 200 -
Exception in thread Thread-40618:
Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/SocketServer.py", line 602, in process_request_thread
    self.handle_error(request, client_address)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/werkzeug/serving.py", line 216, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/werkzeug/serving.py", line 251, in handle_one_request
    return self.run_wsgi()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/werkzeug/serving.py", line 193, in run_wsgi
    execute(self.server.app)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/werkzeug/serving.py", line 181, in execute
    application_iter = app(environ, start_response)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/beaker/middleware.py", line 155, in __call__
    return self.wrap_app(environ, session_start_response)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/server.py", line 590, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/server.py", line 332, in app_run_simulation
    _start_simulation(data)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/server.py", line 820, in _start_simulation
    cfg.job_queue(data)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/runner.py", line 195, in __init__
    jid,
NameError: global name 'jid' is not defined

10.0.2.2 - - [02/Dec/2016 22:04:51] "POST /save-simulation HTTP/1.1" 200 -
```
It's not reported in the UI, so a user may think the simulation is running, but actually the server does nothing after that exception, which may cause negative impression. Need to fix this issue asap.

**Comment by mrakitin** [comment]
@robnagler, do you mind to look at the issue please?

**Comment by robnagler** [comment]
Looking now.

**Comment by robnagler** [comment]
Please attach simulation json. It's not on our servers.

**Comment by robnagler** [comment]
I pushed a change that fixes the "jid" error.@moellep, can you build alpha? I have a call.

**Comment by mrakitin** [comment]
Thanks for fixing this issue Rob. Do you still need the simulation json?

**Comment by robnagler** [comment]
I don't think so. I think if the Collision exception was raised then it would have been caught later up the stack and the right error would be returned.

We still need to handle errors in general.

**Comment by mrakitin** [comment]
OK, thanks.
