### ISSUE TITLE
ComputeJob._run Task was destroyed but it is pending!

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#5645]
To reproduce, use nersc supervisor, but without proxy setup.

```txt
Apr 05 18:42:30  3093     0 sirepo/job_supervisor.py:233:receive ServerReq(api_runSimulation, a1UykWt2-mNFwWw6z-multiElectronAnimation)
Apr 05 18:42:30  3093     0 sirepo/job_supervisor.py:1076:__init__ _Op(run, jHRu) runDir=/home/vagrant/src/radiasoft/sirepo/run/user/a1UykWt2/srw/mNFwWw6z/multiElectronAnimation
Apr 05 18:42:30  3093     0 sirepo/job_supervisor.py:1111:reply_get _Op(run, jHRu) await _reply_q.get()
Apr 05 18:42:45  3093     0 sirepo/job_supervisor.py:243:receive ServerReq(api_runStatus, a1UykWt2-mNFwWw6z-multiElectronAnimation) error=SRException(params={'host': 'perlmutter-p1.ne\
rsc.gov', 'isModal': True, 'isGeneral': True, 'reason': 'no-creds', 'computeModel': 'multiElectronAnimation', 'simulationId': 'mNFwWw6z', 'simulationType': 'srw'},routeName=sbatchLogi\
n) stack=Traceback (most recent call last):
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/job_supervisor.py", line 236, in receive
    return await getattr(
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/job_supervisor.py", line 841, in _receive_api_runStatus
    raise self.pkdel("_sr_exception")
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/job_supervisor.py", line 907, in _send_op
    await op.prepare_send()
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/job_supervisor.py", line 1104, in prepare_send
    await self.driver.prepare_send(self)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/job_driver/sbatch.py", line 112, in prepare_send
    self._raise_sbatch_login_srexception("no-creds", m)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/job_driver/sbatch.py", line 233, in _raise_sbatch_login_srexception
    raise util.SRException(
sirepo.util.SRException: SRException(params={'host': 'perlmutter-p1.nersc.gov', 'isModal': True, 'isGeneral': True, 'reason': 'no-creds', 'computeModel': 'multiElectronAnimation', 'si\
mulationId': 'mNFwWw6z', 'simulationType': 'srw'},routeName=sbatchLogin)

Exception was printed at:

sirepo.util.SRException: SRException(params={'host': 'perlmutter-p1.nersc.gov', 'isModal': True, 'isGeneral': True, 'reason': 'no-creds', 'computeModel': 'multiElectronAnimation', 'si\
mulationId': 'mNFwWw6z', 'simulationType': 'srw'},routeName=sbatchLogin)
  File "/home/vagrant/.pyenv/versions/py3/bin/sirepo", line 33, in <module>
    sys.exit(load_entry_point('sirepo', 'console_scripts', 'sirepo')())
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/sirepo_console.py", line 18, in main
    return pkcli.main("sirepo")
  File "/home/vagrant/src/radiasoft/pykern/pykern/pkcli/__init__.py", line 158, in main
    res = argh.dispatch(parser, argv=argv)
  File "/home/vagrant/.pyenv/versions/3.9.15/envs/py3/lib/python3.9/site-packages/argh/dispatching.py", line 179, in dispatch
    for line in lines:
  File "/home/vagrant/.pyenv/versions/3.9.15/envs/py3/lib/python3.9/site-packages/argh/dispatching.py", line 290, in _execute_command
    for line in result:
  File "/home/vagrant/.pyenv/versions/3.9.15/envs/py3/lib/python3.9/site-packages/argh/dispatching.py", line 273, in _call
    result = function(*positional, **keywords)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/pkcli/job_supervisor.py", line 79, in default_command
    tornado.ioloop.IOLoop.current().start()
  File "/home/vagrant/.pyenv/versions/3.9.15/envs/py3/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 215, in start
    self.asyncio_loop.run_forever()
  File "/home/vagrant/.pyenv/versions/3.9.15/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/home/vagrant/.pyenv/versions/3.9.15/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/home/vagrant/.pyenv/versions/3.9.15/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/vagrant/.pyenv/versions/3.9.15/envs/py3/lib/python3.9/site-packages/tornado/web.py", line 1713, in _execute
    result = await result
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/pkcli/job_supervisor.py", line 150, in post
    self.write(await _incoming(self.request.body, self))
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/pkcli/job_supervisor.py", line 211, in _incoming
    return await handler.sr_class(handler=handler, content=c).receive()
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/job_supervisor.py", line 100, in receive
    return await _Supervisor.receive(self)
Apr 05 18:45:40  3093     0 sirepo/job_supervisor.py:233:receive ServerReq(api_beginSession, None)
Apr 05 18:45:40  3093     0 sirepo/job_supervisor.py:1076:__init__ _Op(begin_session, XZQQ) runDir=None
Task was destroyed but it is pending!
task: <Task pending name='Task-732' coro=<_ComputeJob._run() done, defined at /home/vagrant/src/radiasoft/sirepo/sirepo/job_supervisor.py:892> wait_for=<Future pending cb=[<TaskWakeup\
MethWrapper object at 0x7ff47ab54550>()]> cb=[IOLoop.add_future.<locals>.<lambda>() at /home/vagrant/.pyenv/versions/3.9.15/envs/py3/lib/python3.9/site-packages/tornado/ioloop.py:687]\
>
```

**Comment by robnagler** [comment]
I saw another case of this. see [20230929123700-log.txt](https://github.com/radiasoft/sirepo/files/12771609/20230929123700-log.txt). Here are some interesting events:

- 12:42:49 runCancel 
- 12:47:57 Waiting for another simulation to complete
- 12:53:44 ERROR:asyncio:Task was destroyed but it is pending!
