### ISSUE TITLE
api-tornado: when agent fails to start, javascript hangs on loading wheel

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#5659]
API is proxied tornado through nginx. The supervisor is trying to start a session, and there's something wrong with the agent (in this case can't find sirepo). An assertion occurs and that's the last output. The browser is hung waiting for the schema, because the tornado server is hung. This may be something other than what I've described, just documenting here.

```txt
Apr 10 23:05:42 v4.radia.run sirepo-7780[11944]: Apr 10 23:05:42     6     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/tornado/web.py:2275:log_request INFO:tornado.access:200 GET /static/js/sirepo-dom.js?20230410.230541 (10.10.10.1) 3.56ms
Apr 10 23:05:42 v4.radia.run sirepo-7781[11992]: Apr 10 23:05:42     7     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/tornado/web.py:2275:log_request INFO:tornado.access:200 GET /static/js/ext/angular.min.js.map (10.10.10.1) 7.46ms
Apr 10 23:05:42 v4.radia.run sirepo-7782[12022]: Apr 10 23:05:42     7     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_api.py:257:_content_and_uri api=api_beginSession runDir=None
Apr 10 23:05:42 v4.radia.run sirepo-7783[11978]: Apr 10 23:05:42     7     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/tornado/web.py:2275:log_request INFO:tornado.access:200 GET /static/img/favicon.png?20230410.230541 (10.10.10.1) 4.98ms
Apr 10 23:05:42 v4.radia.run sirepo_job_supervisor[11692]: Apr 10 23:05:42     6     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_supervisor.py:233:receive ServerReq(api_beginSession, None)
Apr 10 23:05:42 v4.radia.run sirepo_job_supervisor[11692]: Apr 10 23:05:42     6     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_supervisor.py:1076:__init__ _Op(begin_session, K0MY) runDir=None
Apr 10 23:05:42 v4.radia.run sirepo_job_supervisor[11692]: Apr 10 23:05:42     6     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_driver/__init__.py:266:_agent_start DockerDriver(a=SKmI k=sequential u=ABrk [_Op(begin_session, K0MY)]) _Op(begin_session, K0MY) await _do_agent_start
Apr 10 23:05:42 v4.radia.run sirepo_job_supervisor[11692]: Apr 10 23:05:42     6     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_driver/docker.py:120:kill DockerDriver(a=SKmI k=sequential u=ABrk [_Op(begin_session, K0MY)]) cid=None
Apr 10 23:05:42 v4.radia.run sirepo-7784[11980]: Apr 10 23:05:42     7     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/tornado/web.py:2275:log_request INFO:tornado.access:200 GET /static/img/favicon.ico?20230410.230541 (10.10.10.1) 3.82ms
Apr 10 23:05:42 v4.radia.run sirepo_job_supervisor[11692]: Apr 10 23:05:42     6     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_driver/docker.py:172:_do_agent_start DockerDriver(a=SKmI k=sequential u=ABrk [_Op(begin_session, K0MY)]) agent_exec_dir=/srv/sirepo/db/user/ABrk5G5s/agent-docker/v4.radia.run/srj-s-ABrk5G5s
Apr 10 23:05:42 v4.radia.run containerd[2935]: time="2023-04-10T23:05:42.477593854Z" level=info msg="loading plugin \"io.containerd.event.v1.publisher\"..." runtime=io.containerd.runc.v2 type=io.containerd.event.v1
Apr 10 23:05:42 v4.radia.run containerd[2935]: time="2023-04-10T23:05:42.477732115Z" level=info msg="loading plugin \"io.containerd.internal.v1.shutdown\"..." runtime=io.containerd.runc.v2 type=io.containerd.internal.v1
Apr 10 23:05:42 v4.radia.run containerd[2935]: time="2023-04-10T23:05:42.477765961Z" level=info msg="loading plugin \"io.containerd.ttrpc.v1.task\"..." runtime=io.containerd.runc.v2 type=io.containerd.ttrpc.v1
Apr 10 23:05:42 v4.radia.run containerd[2935]: time="2023-04-10T23:05:42.478050049Z" level=info msg="starting signal loop" namespace=moby path=/run/containerd/io.containerd.runtime.v2.task/moby/779aff13306612e09b41434b3347f26beb86115b419a3102942d8fe2a761723c pid=17372 runtime=io.containerd.runc.v2
Apr 10 23:05:42 v4.radia.run sirepo_job_supervisor[11692]: Apr 10 23:05:42     6     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_driver/docker.py:198:_do_agent_start DockerDriver(a=SKmI k=sequential u=ABrk [_Op(begin_session, K0MY)]) cname=srj-s-ABrk5G5s cid=779aff133066
Apr 10 23:05:42 v4.radia.run sirepo_job_supervisor[11692]: Apr 10 23:05:42     6     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_driver/__init__.py:239:_agent_ready DockerDriver(a=SKmI k=sequential u=ABrk [_Op(begin_session, K0MY)]) _Op(begin_session, K0MY) await _websocket_ready
Apr 10 23:05:42 v4.radia.run 779aff133066[11171]: /bin/bash: line 29: exec: sirepo: not found
Apr 10 23:05:42 v4.radia.run containerd[2935]: time="2023-04-10T23:05:42.792857519Z" level=info msg="shim disconnected" id=779aff13306612e09b41434b3347f26beb86115b419a3102942d8fe2a761723c
Apr 10 23:05:42 v4.radia.run containerd[2935]: time="2023-04-10T23:05:42.792914810Z" level=warning msg="cleaning up after shim disconnected" id=779aff13306612e09b41434b3347f26beb86115b419a3102942d8fe2a761723c namespace=moby
Apr 10 23:05:42 v4.radia.run containerd[2935]: time="2023-04-10T23:05:42.792957706Z" level=info msg="cleaning up dead shim"
Apr 10 23:05:42 v4.radia.run dockerd[11171]: time="2023-04-10T23:05:42.793227114Z" level=info msg="ignoring event" container=779aff13306612e09b41434b3347f26beb86115b419a3102942d8fe2a761723c module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
Apr 10 23:05:42 v4.radia.run containerd[2935]: time="2023-04-10T23:05:42.804843029Z" level=warning msg="cleanup warnings time=\"2023-04-10T23:05:42Z\" level=info msg=\"starting signal loop\" namespace=moby pid=17497 runtime=io.containerd.runc.v2\n"
Apr 10 23:05:50 v4.radia.run sirepo_job_supervisor[11692]: Apr 10 23:05:50     6     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_driver/__init__.py:290:_agent_starting_timeout_handler DockerDriver(a=SKmI k=sequential u=ABrk [_Op(begin_session, K0MY)]) timeout=8
Apr 10 23:05:50 v4.radia.run sirepo_job_supervisor[11692]: Apr 10 23:05:50     6     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_driver/docker.py:120:kill DockerDriver(a=SKmI k=sequential u=ABrk [_Op(begin_session, K0MY)]) cid=779aff133066
Apr 10 23:05:50 v4.radia.run sirepo_job_supervisor[11692]: Apr 10 23:05:50     6     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_driver/docker.py:131:kill DockerDriver(a=SKmI k=sequential u=ABrk [_Op(begin_session, K0MY)]) error=('docker', '--host=tcp://v4.radia.run:2376', '--tlsverify', '--tlscacert=/srv/sirepo_job_supervisor/docker_tls/v4.radia.run/cacert.pem', '--tlscert=/srv/sirepo_job_supervisor/docker_tls/v4.radia.run/cert.pem', '--tlskey=/srv/sirepo_job_supervisor/docker_tls/v4.radia.run/key.pem', 'stop', '--time=3', 'srj-s-ABrk5G5s'): failed: exit=1 output=Error response from daemon: No such container: srj-s-ABrk5G5s stack=Traceback (most recent call last):
Apr 10 23:05:50 v4.radia.run sirepo_job_supervisor[11692]: File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_driver/docker.py", line 125, in kill
Apr 10 23:05:50 v4.radia.run sirepo_job_supervisor[11692]: ("stop", "--time={}".format(job_driver.KILL_TIMEOUT_SECS), self._cname),
Apr 10 23:05:50 v4.radia.run sirepo_job_supervisor[11692]: File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_driver/docker.py", line 222, in _cmd
Apr 10 23:05:50 v4.radia.run sirepo_job_supervisor[11692]: assert r == 0, "{}: failed: exit={} output={}".format(c, r, o)
Apr 10 23:05:50 v4.radia.run sirepo_job_supervisor[11692]: AssertionError: ('docker', '--host=tcp://v4.radia.run:2376', '--tlsverify', '--tlscacert=/srv/sirepo_job_supervisor/docker_tls/v4.radia.run/cacert.pem', '--tlscert=/srv/sirepo_job_supervisor/docker_tls/v4.radia.run/cert.pem', '--tlskey=/srv/sirepo_job_supervisor/docker_tls/v4.radia.run/key.pem', 'stop', '--time=3', 'srj-s-ABrk5G5s'): failed: exit=1 output=Error response from daemon: No such container: srj-s-ABrk5G5s
Apr 10 23:05:50 v4.radia.run sirepo_job_supervisor[11692]: Exception was printed at:
Apr 10 23:05:50 v4.radia.run sirepo_job_supervisor[11692]: AssertionError: ('docker', '--host=tcp://v4.radia.run:2376', '--tlsverify', '--tlscacert=/srv/sirepo_job_supervisor/docker_tls/v4.radia.run/cacert.pem', '--tlscert=/srv/sirepo_job_supervisor/docker_tls/v4.radia.run/cert.pem', '--tlskey=/srv/sirepo_job_supervisor/docker_tls/v4.radia.run/key.pem', 'stop', '--time=3', 'srj-s-ABrk5G5s'): failed: exit=1 output=Error response from daemon: No such container: srj-s-ABrk5G5s
Apr 10 23:05:50 v4.radia.run sirepo_job_supervisor[11692]: File "/home/vagrant/.pyenv/versions/py3/bin/sirepo", line 8, in <module>
Apr 10 23:05:50 v4.radia.run sirepo_job_supervisor[11692]: sys.exit(main())
Apr 10 23:05:50 v4.radia.run sirepo_job_supervisor[11692]: File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/sirepo_console.py", line 18, in main
Apr 10 23:05:50 v4.radia.run sirepo_job_supervisor[11692]: return pkcli.main("sirepo")
Apr 10 23:05:50 v4.radia.run sirepo_job_supervisor[11692]: File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/pykern/pkcli/__init__.py", line 158, in main
Apr 10 23:05:50 v4.radia.run sirepo_job_supervisor[11692]: res = argh.dispatch(parser, argv=argv)
Apr 10 23:05:50 v4.radia.run sirepo_job_supervisor[11692]: File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/argh/dispatching.py", line 174, in dispatch
Apr 10 23:05:50 v4.radia.run sirepo_job_supervisor[11692]: for line in lines:
Apr 10 23:05:50 v4.radia.run sirepo_job_supervisor[11692]: File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/argh/dispatching.py", line 277, in _execute_command
Apr 10 23:05:50 v4.radia.run sirepo_job_supervisor[11692]: for line in result:
Apr 10 23:05:50 v4.radia.run sirepo_job_supervisor[11692]: File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/argh/dispatching.py", line 260, in _call
Apr 10 23:05:50 v4.radia.run sirepo_job_supervisor[11692]: result = function(*positional, **keywords)
Apr 10 23:05:50 v4.radia.run sirepo_job_supervisor[11692]: File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/pkcli/job_supervisor.py", line 79, in default_command
Apr 10 23:05:50 v4.radia.run sirepo_job_supervisor[11692]: tornado.ioloop.IOLoop.current().start()
Apr 10 23:05:50 v4.radia.run sirepo_job_supervisor[11692]: File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/tornado/platform/asyncio.py", line 215, in start
Apr 10 23:05:50 v4.radia.run sirepo_job_supervisor[11692]: self.asyncio_loop.run_forever()
Apr 10 23:05:50 v4.radia.run sirepo_job_supervisor[11692]: File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/asyncio/base_events.py", line 539, in run_forever
Apr 10 23:05:50 v4.radia.run sirepo_job_supervisor[11692]: self._run_once()
Apr 10 23:05:50 v4.radia.run sirepo_job_supervisor[11692]: File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/asyncio/base_events.py", line 1775, in _run_once
Apr 10 23:05:50 v4.radia.run sirepo_job_supervisor[11692]: handle._run()
Apr 10 23:05:50 v4.radia.run sirepo_job_supervisor[11692]: File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/asyncio/events.py", line 88, in _run
Apr 10 23:05:50 v4.radia.run sirepo_job_supervisor[11692]: self._context.run(self._callback, *self._args)
Apr 10 23:05:50 v4.radia.run sirepo_job_supervisor[11692]: File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_driver/__init__.py", line 291, in _agent_starting_timeout_handler
Apr 10 23:05:50 v4.radia.run sirepo_job_supervisor[11692]: await self.kill()
Apr 10 23:05:50 v4.radia.run sirepo_job_supervisor[11692]: Apr 10 23:05:50     6     0 /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_driver/__init__.py:108:free_resources DockerDriver(a=SKmI k=sequential u=ABrk [_Op(begin_session, K0MY)]) internal_error=timeout waiting for agent to start

```

**Comment by robnagler** [comment]
The exec sirepo failure can be reproduced by:

```bash
export 'SIREPO_JOB_DRIVER_DOCKER_DEV_VOLUMES=1'
```

This is the default behavior when running servers configured in dev with rsconf.
