### ISSUE TITLE
react list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#5739]
I can't reproduce this on master. It happens on 5464-shadow-rev-branch. I think the error is `elements` doesn't exist in srw, but validate_models is checking for it. e5243b55e0409985cf1f3cdcd4dfdc1c650ff7c5 appears to be the problem.

```txt
../sirepo/job_driver/__init__.py:300:_receive LocalDriver(a=0U4Z k=sequential u=3N7a [_Op(run, GIuC)]) error msg={'agentId': '0U4Zb4civBIid6QrLfl2g6XtsEH3qso9', 'opId': 'GIuCOP7d41merYGEmWtzMXhGnUmKiTLQ', 'opName': 'run', 'reply': {'error': 'list indices m\
ust be integers or slices, not str', 'stack': 'Traceback (most recent call last):
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/pkcli/job_cmd.py", line 50, in default_command
    res = globals()["_do_" + msg.jobCmd](
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/pkcli/job_cmd.py", line 127, in _do_compute
    _do_prepare_simulation(msg, template).cmd,
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/pkcli/job_cmd.py", line 263, in _do_prepare_simulation
    cmd=simulation_db.prepare_simulation(
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/simulation_db.py", line 451, in prepare_simulation
    c = template.write_parameters(
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/template/srw.py", line 1119, in write_parameters
    p = _trim(_generate_parameters_file(data, run_dir=run_dir))
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/template/srw.py", line 1906, in _generate_parameters_file
    _validate_data(data, SCHEMA)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/template/srw.py", line 2552, in _validate_data
    template_common.validate_models(data, schema)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/template/template_common.py", line 828, in validate_models
    for m in model_data["models"]["beamline"]["elements"]:
TypeError: list indices must be integers or slices, not str
```

**Comment by garsuga** [comment]
This will happen until we can separate React logic from the old logic on the server side as we discussed before. Shadow required changes to the lattice.py file.
