### ISSUE TITLE
Integrate with podman-hpc

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#5803]
See #5798 

This basically works:

```sh
podman-hpc pull docker.io/radiasoft/sirepo:alpha
podman-hpc run -it --mpi --userns keep-id --rm -v $SCRATCH/sirepo-dev:$SCRATCH/sirepo-dev radiasoft/sirepo:alpha bash
```

Problems:
- Images are not shared between users. There seems to be a NERSC registry. Might be able to get sirepo in there
- To run a job, you need to `podman-hpc migrate radasoft/sirepo:alpha`. Not sure if that has to be done on a per user basis.
- Tried `--net host`, but that seemed to hang every other time.
- Haven't tried in sbatch
- Exiting the run causes, which seems to be a Python output, but wasn't running Python:
```txt
send_complete failed for None
encoding without a string argument
```

**Comment by robnagler** [comment]
```txt
Sometimes podman-hpc can get into a bad configuration state. You can try clearing several storage areas.

On a local login node you can delete:
/images/<userid>_hpc
On a compute or login node you can delete:
$SCRATCH/storage (and then recreate this directory)
~/.local/share/containers
On a compute node you can delete:
/tmp/<userid>_hpc
```

**Comment by robnagler** [comment]
podman isn't working right now...

```txt
> podman-hpc run -it --mpi --userns keep-id --rm -v $SCRATCH/sirepo-dev:$SCRATCH/sirepo-dev radiasoft/sirepo:alpha bash

^CProcess Process-1:

Aborted!
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/site-packages/podman_hpc/podman_hpc.py", line 365, in monitor
    conn, addr = s.accept()
  File "/usr/lib64/python3.6/socket.py", line 205, in accept
    fd, addr = self._accept()
KeyboardInterrupt
```

**Comment by robnagler** [comment]
[Cleared cache](https://github.com/radiasoft/sirepo/issues/5803#issuecomment-1536890229) to fix the issue. This is problematic, because the cache is shared across all containers and images. Can't just clear an arbitrary user's cache. I'll discuss with NERSC.

**Comment by robnagler** [comment]
Useful links:

- https://www.nersc.gov/assets/Uploads/06-Containers-for-HPC-Shifter-and-Podman.pdf
- https://github.com/NERSC/podman-hpc

**Comment by robnagler** [comment]
Lowering priority of this. We'll help with podman, but it's still a work in progress. Shifter will be around for quite some time.
