### ISSUE TITLE
export-archive {"state":"error","error":"Simulation library file \".zip\" does not exist"}

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/sirepo#5894]
Trying to export https://alpha.sirepo.com/flash#/setup/AxKOHrpZ

**Comment by e-carlin** [comment]
Not sure if this is related but I tried one of the examples and got an error as well. Seeing this in the server logs

```
17:17:44 sirepo/uri_router.py:322:_call_api api=exportArchive exception='PKDict' object has no attribute 'flashSchema' stack=Traceback (most recent call last):
17:17:44 sirepo/uri_router.py", line 313, in _call_api
17:17:44 await getattr(qcall, qcall.uri_route.func_name)(**kwargs)
17:17:44 sirepo/server.py", line 172, in api_exportArchive
17:17:44 return exporter.create_archive(req, self)
17:17:44 sirepo/exporter.py", line 37, in create_archive
17:17:44 f, c = _create_zip(sim, out_dir=d, qcall=qcall)
17:17:44 sirepo/exporter.py", line 64, in _create_zip
17:17:44 for f in _python(data, sim, qcall):
17:17:44 sirepo/exporter.py", line 99, in _python
17:17:44 t = template.python_source_for_model(d, model=None, qcall=qcall)
17:17:44 sirepo/template/flash.py", line 167, in python_source_for_model
17:17:44 return _generate_parameters_file(data, None)
17:17:44 sirepo/template/flash.py", line 545, in _generate_parameters_file
17:17:44 res = _generate_par_file(data)
17:17:44 sirepo/template/flash.py", line 498, in _generate_par_file
17:17:44 flash_schema = data.models.flashSchema
17:17:44 pykern/pkcollections.py", line 68, in __getattr__
17:17:44 raise AttributeError(
17:17:44 AttributeError: 'PKDict' object has no attribute 'flashSchema'
17:17:44 Exception was printed at:
17:17:44 AttributeError: 'PKDict' object has no attribute 'flashSchema'
17:17:44 flask/app.py", line 2091, in __call__
17:17:44 return self.wsgi_app(environ, start_response)
17:17:44 flask/app.py", line 2073, in wsgi_app
17:17:44 response = self.full_dispatch_request()
17:17:44 flask/app.py", line 1516, in full_dispatch_request
17:17:44 rv = self.dispatch_request()
17:17:44 flask/app.py", line 1502, in dispatch_request
17:17:44 return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
17:17:44 sirepo/uri_router.py", line 368, in _flask_dispatch
17:17:44 return asyncio.run(
17:17:44 File "/home/vagrant/.pyenv/versions/3.9.15/lib/python3.9/asyncio/runners.py", line 44, in run
17:17:44 return loop.run_until_complete(main)
17:17:44 File "/home/vagrant/.pyenv/versions/3.9.15/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
17:17:44 self.run_forever()
17:17:44 File "/home/vagrant/.pyenv/versions/3.9.15/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
17:17:44 self._run_once()
17:17:44 File "/home/vagrant/.pyenv/versions/3.9.15/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
17:17:44 handle._run()
17:17:44 File "/home/vagrant/.pyenv/versions/3.9.15/lib/python3.9/asyncio/events.py", line 80, in _run
17:17:44 self._context.run(self._callback, *self._args)
17:17:44 sirepo/reply.py:540:_gen_exception_error unsupported exception=<class 'AttributeError'> msg='PKDict' object has no attribute 'flashSchema'
```

**Comment by e-carlin** [comment]
This is happening on prod too. 

@ncook882 cc

**Comment by e-carlin** [comment]
{"state":"error","error":"Simulation library file \".zip\" does not exist"} this is related to the extraction that happens when a user opens a flash example for the first time. It is unlikely to happen to users (i doubt many folks share simulations they've never opened) so I'm not going to solve now. But we should at least get a better error message.

The "flashSchema" error is a real problem though. No flash simulations can be shared because of it.

**Comment by e-carlin** [comment]
The flashSchema error only happens if a user hasn't run the setup/compile step of the simulation. So again, I think unlikely to appear much in the wild.

@ncook882 I'm going to defer to you on whether or not either of these bugs are worth solving at the moment. Both can be worked around and I think users are unlikely to run into.
