### ISSUE TITLE
Tabulated Undulator KeyError animationArgs

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#595]
Fresh pull running on a simulation directory last updated on 1/5/2017.

```
10.10.10.1 - - [07/Jan/2017 20:45:12] "GET /simulation-frame/srw*XdV1QagN*fluxAnimation*1*1*1483821849196543 HTTP/1.1" 500 -
10.10.10.1 - - [07/Jan/2017 20:43:08] "GET /simulation-frame/srw*XdV1QagN*fluxAnimation*1*1*1483821657864465 HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/werkzeug/serving.py", line 193, in run_wsgi
    execute(self.server.app)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/werkzeug/serving.py", line 181, in execute
    application_iter = app(environ, start_response)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1994, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/beaker/middleware.py", line 156, in __call__
    return self.wrap_app(environ, session_start_response)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/server.py", line 634, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/server.py", line 422, in app_simulation_frame
    response = _json_response(template.get_simulation_frame(run_dir, data, model_data))
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/template/srw.py", line 493, in get_simulation_frame
    return extract_report_data(str(run_dir.join(get_filename_for_model(data['report']))), model_data)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/template/srw.py", line 126, in extract_report_data
    flux_type = int(model_data['animationArgs'])
KeyError: 'animationArgs'
```

**Comment by robnagler** [comment]
removing the directory did not get rid of the error.

**Comment by mrakitin** [comment]
It's due to 9726f29b897bcb26a46fa36a1c42dc507dc7ac91. I'll check it on Monday.

**Comment by mrakitin** [comment]
It's fixed in 65b8841. I don't know why it was decided to implement passing of the `fluxType` via `model_data['animationArgs']`. Now it's passed from the schema model.

@moellep, could you please release alpha to see if it fixed the issue? Thanks!

**Comment by robnagler** [comment]
This fixed it for my system.

**Comment by mrakitin** [comment]
Great 😄

**Comment by mrakitin** [comment]
It works fine on alpha - https://alpha.sirepo.com/srw#/source/6e7oCsvi.
