### ISSUE TITLE
importer_test: beams.json no longer needed?

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#603]
I realize that I didn't test this after moving beams.json, but now beams.json is gone, this test fails. I'm not sure if we should be testing this at all? 

```
py.test importer_test.py
================================= test session starts ==================================
platform linux2 -- Python 2.7.10, pytest-3.0.5, py-1.4.32, pluggy-0.4.0
rootdir: /home/vagrant/src/radiasoft/sirepo, inifile:
plugins: xdist-1.15.0, pykern-20170104.155145
collected 1 items

importer_test.py F

======================================= FAILURES =======================================
____________________________________ test_importer _____________________________________
def test_importer():
        from sirepo.importer import import_python
        dat_dir = py.path.local(pkresource.filename('template/srw/', import_python))
        with pkunit.save_chdir_work():
            work_dir = py.path.local('.')
            for f in glob.glob(str(dat_dir.join('mirror_*d.dat'))):
                py.path.local(f).copy(work_dir)
            py.path.local(str(dat_dir.join('sample.tif'))).copy(work_dir)
            for b in sorted(_TESTS.keys()):
                base_py = '{}.py'.format(_TESTS[b][0])
                code = pkio.read_text(pkunit.data_dir().join(base_py))
                error, actual = import_python(
                    code,
                    tmp_dir=str(work_dir),
                    lib_dir=str(work_dir),
                    user_filename=r'c:\anything\{}.anysuffix'.format(_TESTS[b][0]),
                    arguments=_TESTS[b][1],
                )
>               assert not error, \
                    '{}: should import with an error: {}'.format(base_py, error)
E               AssertionError: amx.py: should import with an error: Error on line ?: [Errno 2] No such file or directory: '/home/vagran
E               assert not "Error on line ?: [Errno 2] No such file or directory: '/home/vagran"

importer_test.py:60: AssertionError
--------------------------------- Captured stdout call ---------------------------------
[0.9999999999999999, -2.5866939514398794e-09, -1.6653345369377348e-16]
[2.5866939514398827e-09, 1.0, -1.1486052770794924e-08]
[1.6653345369377348e-16, 1.1486052770794924e-08, 0.9999999999999999]
--------------------------------- Captured stderr call ---------------------------------
../sirepo/importer.py:129:import_python Error: Import failed: error unknown; exception=[Errno 2] No such file or directory: '/home/vagrant/src/radiasoft/sirepo/sirepo/package_\
data/template/srw/beams.json'; script=/home/vagrant/src/radiasoft/sirepo/tests/importer_work/in.py; filename=c:\anything\amx.anysuffix; stack:
Traceback (most recent call last):
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/importer.py", line 117, in import_python
    arguments=arguments,
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/importer.py", line 53, in __init__
    self.data = _parsed_dict(self.var_param, self.optics)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/importer.py", line 598, in _parsed_dict
    with open(str(template_dir + '/beams.json'), 'r') as f:
IOError: [Errno 2] No such file or directory: '/home/vagrant/src/radiasoft/sirepo/sirepo/package_data/template/srw/beams.json'
=============================== 1 failed in 2.31 seconds ===============================
```

**Comment by mrakitin** [comment]
I think the problem is deeper than the testing - it's rather in the importer code which is probably broken now since it used to use `beams.json`. Need to update it to use the new functions instead.

**Comment by moellep** [comment]
I broke this when I replaced beams.json with direct calls to
srwl_uti_src.py. I'll fix the import code.

**Comment by mrakitin** [comment]
Thanks @moellep.
