### ISSUE TITLE
SRW - problem with the tabulated data in Mac EOL format

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#607]
Request from NSLS-II scientist:
> I have tried to upload some measurements on the Sirepo server but I got the following error.

Here is the error in the server log:
```python
Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/SocketServer.py", line 602, in process_request_thread
    self.handle_error(request, client_address)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/werkzeug/serving.py", line 216, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/werkzeug/serving.py", line 251, in handle_one_request
    return self.run_wsgi()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/werkzeug/serving.py", line 193, in run_wsgi
    execute(self.server.app)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/werkzeug/serving.py", line 181, in execute
    application_iter = app(environ, start_response)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/beaker/middleware.py", line 155, in __call__
    return self.wrap_app(environ, session_start_response)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/server.py", line 637, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/server.py", line 354, in app_run_simulation
    data = _parse_data_input(validate=True)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/server.py", line 723, in _parse_data_input
    return simulation_db.fixup_old_data(data)[0] if validate else data
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/simulation_db.py", line 183, in fixup_old_data
    sirepo.template.import_module(data['simulationType']).fixup_old_data(data)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/template/srw.py", line 406, in fixup_old_data
    data['models']['tabulatedUndulator'] = _compute_undulator_length(data['models']['tabulatedUndulator'])
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/template/srw.py", line 893, in _compute_undulator_length
    d = _find_tab_undulator_length(zip_file, model['gap'])
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/template/srw.py", line 1063, in _find_tab_undulator_length
    step = float(dat_content[8].split('#')[1].strip())
IndexError: list index out of range
```

I checked the files, and it looks like they are in the Mac EOL format:
![crlf_cr](https://cloud.githubusercontent.com/assets/13209176/21858304/984d8876-d7f6-11e6-99c3-c6e7475c21e3.png)

**Comment by mrakitin** [comment]
Fixed in 1ca21ac.
@robnagler, I added TODO tag regarding #611 for you.
