### ISSUE TITLE
Disabling watchpoint results in CopyRedirect

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#609]
Did not debug this. For sample from image on beamline, I disable a watch point, and then on save simulation, I get this exception:

```
10.10.10.1 - - [11/Jan/2017 17:33:54] "POST /save-simulation HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/werkzeug/serving.py", line 193, in run_wsgi
    execute(self.server.app)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/werkzeug/serving.py", line 181, in execute
    application_iter = app(environ, start_response)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1994, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/beaker/middleware.py", line 156, in __call__
    return self.wrap_app(environ, session_start_response)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/server.py", line 643, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/server.py", line 385, in app_save_simulation_data
    res = _validate_serial(data)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/server.py", line 885, in _validate_serial
    res = simulation_db.validate_serial(data)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/simulation_db.py", line 746, in validate_serial
    curr = read_simulation_json(sim_type, sid=sid)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/simulation_db.py", line 568, in read_simulation_json
    data = open_json_file(sim_type, fixup=False, *args, **kwargs)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/simulation_db.py", line 388, in open_json_file
    'userCopySimulationId': user_copy_sid,
CopyRedirect
../sirepo/server.py:833:_simulation_run_status J4IJUIaI-iDcXBGvn-initialIntensityReport: parametersChanged=True req_hash=91a151bcfed4f2d33422b74985dba420 cached_hash=70043e61d\
4bb2453293dc87a33927440
../sirepo/runner.py:145:_start_job J4IJUIaI-iDcXBGvn-initialIntensityReport: started: pid=18760 cmd=['sirepo', 'srw', 'run', '/home/vagrant/src/radiasoft/sirepo/run/user/J4IJU\
IaI/srw/iDcXBGvn/initialIntensityReport']
```

**Comment by moellep** [comment]
This can be reproduced by opening a simulation and then clearing the browser cookies. When it tries to save, it finds the simulation in a different session and gets confused.

**Comment by robnagler** [comment]
Not an issue with logged in users.
