### ISSUE TITLE
tiara tally render bug

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#6122]
The TIARA sim output (Vertical tally) is causing the javascript to crash with a bad array size:

https://www.sirepo.com/cloudmc#/visualization/DvLkh2HK

- [x] #6081

**Comment by mkeilman** [comment]
fyi I'm getting an error with the scintillator plane tally before the javascript has a chance to do anything:
```python
Jul 20 00:51:36  5515     0 sirepo/job_driver/__init__.py:306:_receive LocalDriver(a=OtdF k=sequential u=Ycss [_Op(analysis, DdXd)]) error msg={'agentId': 'OtdFFyBlFHLBdYHUWVAVCX7es7lmkBd3', 'opId': 'DdXdkYv77sJpl3dw9pgV2kIbSvr1Y4B4', 'opName': 'analysis', 'reply': {'error': 'report not generated', 'stack': 'Traceback (most recent call last):
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/pkcli/job_cmd.py", line 252, in _do_get_simulation_frame
    return template_common.sim_frame_dispatch(
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/template/template_common.py", line 705, in sim_frame_dispatch
    res = o(frame_args)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/template/cloudmc.py", line 151, in sim_frame
    t.find_filter(openmc.MeshFilter).mesh.write_data_to_vtk(
  File "/home/vagrant/.pyenv/versions/3.9.15/envs/py3/lib/python3.9/site-packages/openmc/mesh.py", line 782, in write_data_to_vtk
    return super().write_data_to_vtk(
  File "/home/vagrant/.pyenv/versions/3.9.15/envs/py3/lib/python3.9/site-packages/openmc/mesh.py", line 242, in write_data_to_vtk
    raise ValueError(errmsg)
ValueError: The size of the dataset 'mean' (490000) should be equal to the number of mesh cells (10000)
```
When I change the tally to vertical I then see the javascript error. Not sure if they are related.

**Comment by mkeilman** [comment]
The js error is due to min x (4) being greater than max x (0.1) in the 2d view. In the short term, that can be corrected by hand  to keep the display from freaking out. Meanwhile #6081 will prevent things from coming to that pass.

**Comment by moellep** [comment]
I think this issue has been resolved.
