### ISSUE TITLE
SRW - cannot export Python code after renaming of the simulation

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#617]
I performed several simulation with a tabulated undulator, and after they finished, I renamed them and then tried to export Python code, which resulted in `502 Bad Gateway` and the error on the server:
```py
Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1994, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/py2/lib/python2.7/site-packages/beaker/middleware.py", line 156, in __call__
    return self.wrap_app(environ, session_start_response)
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/py2/lib/python2.7/site-packages/sirepo-20170110.61455-py2.7.egg/sirepo/server.py", line 631, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/py2/lib/python2.7/site-packages/sirepo-20170110.61455-py2.7.egg/sirepo/server.py", line 294, in app_python_source
    flask.make_response(template.python_source_for_model(data, model)),
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/py2/lib/python2.7/site-packages/sirepo-20170110.61455-py2.7.egg/sirepo/template/srw.py", line 642, in python_source_for_model
    """.format(_generate_parameters_file(data, plot_reports=True))
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/py2/lib/python2.7/site-packages/sirepo-20170110.61455-py2.7.egg/sirepo/template/srw.py", line 1324, in _generate_parameters_file
    _validate_data(data, _SCHEMA)
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/py2/lib/python2.7/site-packages/sirepo-20170110.61455-py2.7.egg/sirepo/template/srw.py", line 1679, in _validate_data
    template_common.validate_model(data['models'][k], schema['model'][k], enum_info)
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/py2/lib/python2.7/site-packages/sirepo-20170110.61455-py2.7.egg/sirepo/template/template_common.py", line 131, in validate_model
    raise Exception('no value for field "{}" and no default value in schema'.format(k))
Exception: no value for field "indexFileName" and no default value in schema
```

I suspect it's due to the recent updates regarding `indexFileName` - https://github.com/radiasoft/sirepo/commit/4adfeac133e2e643b4d5006676cb7539c21dba84.

```bash
docker ps -a
CONTAINER ID        IMAGE                      COMMAND                  CREATED             STATUS              PORTS                                                                                                          NAMES
53aa13c413f9        radiasoft/sirepo:alpha     "bash -c '/radia-run "   3 days ago          Up 3 days           0.0.0.0:7000->7000/tcp                                                                                         sirepo
b11f392db6c0        radiasoft/sirepo:alpha     "bash -c '/radia-run "   3 days ago          Up 3 days                                                                                                                          celery-sirepo
3bec4e69ded8        radiasoft/rabbitmq:alpha   "/vagrant/bivio-servi"   3 days ago          Up 3 days           0.0.0.0:4369->4369/tcp, 0.0.0.0:5672->5672/tcp, 0.0.0.0:15672->15672/tcp, 0.0.0.0:25672->25672/tcp, 5671/tcp   rabbitmq
```

**Comment by robnagler** [comment]
Not related to renaming. I forgot to bump the version when I renamed indexFile to indexFileName.
Fix f20e963
