### ISSUE TITLE
20231020 flash oauth not working in dev (and maybe beyond)?

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/sirepo#6378]
Trying to test https://github.com/radiasoft/sirepo/pull/6376/files I ran flash. I got back the following error:

`https://flash.rochester.edu/id/oauth2/fallbacks/error?error=invalid_request&error_description=The+request+is+missing+a+required+parameter%2C+includes+an+invalid+parameter+value%2C+includes+a+parameter+more+than+once%2C+or+is+otherwise+malformed.+The+%27redirect_uri%27+parameter+does+not+match+any+of+the+OAuth+2.0+Client%27s+pre-registered+redirect+urls.`

It could be a change on our end or their end. Need to debug.

**Comment by e-carlin** [comment]
I ran into it while testing #6376 so I don't think so

**Comment by e-carlin** [comment]
New flash errors when trying to log in on prod.

```
22:58:12 sirepo/oauth.py:44:check_authorized_callback url=https://www.sirepo.com/sim-oauth-flash-authorized exception=missing_code: Missing "code" in response. stack=Traceback (most recent call last):
22:58:12 sirepo/oauth.py", line 33, in check_authorized_callback
22:58:12 c.fetch_token(
22:58:12 authlib/oauth2/client.py", line 196, in fetch_token
22:58:12 body = self._prepare_token_endpoint_body(body, grant_type, **kwargs)
22:58:12 authlib/oauth2/client.py", line 410, in _prepare_token_endpoint_body
22:58:12 return prepare_token_request(grant_type, body, **kwargs)
22:58:12 authlib/oauth2/rfc6749/parameters.py", line 101, in prepare_token_request
22:58:12 raise MissingCodeException()
22:58:12 authlib.oauth2.rfc6749.errors.MissingCodeException: missing_code: Missing "code" in response.
22:58:12 Exception was printed at:
22:58:12 authlib.oauth2.rfc6749.errors.MissingCodeException: missing_code: Missing "code" in response.
22:58:12 File "/home/vagrant/.pyenv/versions/py3/bin/sirepo", line 8, in <module>
22:58:12 sys.exit(main())
22:58:12 sirepo/sirepo_console.py", line 18, in main
22:58:12 return pkcli.main("sirepo")
22:58:12 pykern/pkcli/__init__.py", line 158, in main
22:58:12 res = argh.dispatch(parser, argv=argv)
22:58:12 argh/dispatching.py", line 183, in dispatch
22:58:12 for line in lines:
22:58:12 argh/dispatching.py", line 294, in _execute_command
22:58:12 for line in result:
22:58:12 argh/dispatching.py", line 277, in _call
22:58:12 result = function(*positional, **keywords)
22:58:12 sirepo/pkcli/service.py", line 194, in tornado
22:58:12 sirepo.modules.import_and_init("sirepo.uri_router").start_tornado(
22:58:12 sirepo/uri_router.py", line 334, in start_tornado
22:58:12 ioloop.IOLoop.current().start()
22:58:12 tornado/platform/asyncio.py", line 195, in start
22:58:12 self.asyncio_loop.run_forever()
22:58:12 File "/home/vagrant/.pyenv/versions/3.9.15/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
22:58:12 self._run_once()
22:58:12 File "/home/vagrant/.pyenv/versions/3.9.15/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
22:58:12 handle._run()
22:58:12 File "/home/vagrant/.pyenv/versions/3.9.15/lib/python3.9/asyncio/events.py", line 80, in _run
22:58:12 self._context.run(self._callback, *self._args)
22:58:12 tornado/web.py", line 1786, in _execute
22:58:12 result = await result
22:58:12 sirepo/uri_router.py", line 203, in get
22:58:12 await self._route()
22:58:12 sirepo/uri_router.py", line 194, in _route
22:58:12 await _call_api(
22:58:12 sirepo/uri_router.py", line 416, in _call_api
22:58:12 await getattr(qcall, qcall.uri_route.func_name)(**kwargs)
22:58:12 sirepo/sim_oauth/flash.py", line 25, in api_simOauthFlashAuthorized
22:58:12 o, _ = sirepo.oauth.check_authorized_callback(self)
22:58:12 sirepo/sim_oauth/flash.py:25:api_simOauthFlashAuthorized user denied access from sim_type=flash
```
