### ISSUE TITLE
Parsing elegant input fails with "ModuleNotFoundError: No module named 'pymeshlab' "

### ISSUE THREAD

**Issue by cchall** [radiasoft/sirepo#6498]
```
>>> lib.Importer('elegant').parse('rule.ele')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/chall/opt/miniconda3/lib/python3.9/site-packages/sirepo/lib.py", line 119, in __init__
    self.__adapter = sirepo.template.import_module(sim_type).LibAdapter(
  File "/Users/chall/opt/miniconda3/lib/python3.9/site-packages/sirepo/template/__init__.py", line 23, in import_module
    return sirepo.util.import_submodule("template", type_or_data)
  File "/Users/chall/opt/miniconda3/lib/python3.9/site-packages/sirepo/util.py", line 308, in import_submodule
    return importlib.import_module(n)
  File "/Users/chall/opt/miniconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/chall/opt/miniconda3/lib/python3.9/site-packages/sirepo/template/elegant.py", line 12, in <module>
    from sirepo import simulation_db
  File "/Users/chall/opt/miniconda3/lib/python3.9/site-packages/sirepo/simulation_db.py", line 1103, in <module>
    _init()
  File "/Users/chall/opt/miniconda3/lib/python3.9/site-packages/sirepo/simulation_db.py", line 935, in _init
    _init_schemas()
  File "/Users/chall/opt/miniconda3/lib/python3.9/site-packages/sirepo/simulation_db.py", line 978, in _init_schemas
    srschema.validate(s)
  File "/Users/chall/opt/miniconda3/lib/python3.9/site-packages/sirepo/srschema.py", line 159, in validate
    _validate_job_run_mode(field_name, schema)
  File "/Users/chall/opt/miniconda3/lib/python3.9/site-packages/sirepo/srschema.py", line 232, in _validate_job_run_mode
    m = pkcli.import_module(t)
  File "/Users/chall/opt/miniconda3/lib/python3.9/site-packages/sirepo/pkcli/__init__.py", line 19, in import_module
    return util.import_submodule("pkcli", type_or_data)
  File "/Users/chall/opt/miniconda3/lib/python3.9/site-packages/sirepo/util.py", line 308, in import_submodule
    return importlib.import_module(n)
  File "/Users/chall/opt/miniconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/chall/opt/miniconda3/lib/python3.9/site-packages/sirepo/pkcli/cloudmc.py", line 15, in <module>
    import pymeshlab
ModuleNotFoundError: No module named 'pymeshlab'
```
It looks like both pymeshlab and pymoab are needed but no declared as dependencies. This prevents use of the parsers on Perlmutter.

**Comment by moellep** [comment]
@cchall A work-around for this in the meantime might be to set the sirepo sim_types explicitly:

export SIREPO_FEATURE_CONFIG_SIM_TYPES=opal:elegant:madx:genesis

and leave out cloudmc, which is the one bringing in pymoab.

**Comment by cchall** [comment]
Thanks @moellep, that seems to work well for my purposes

**Comment by robnagler** [comment]
> This prevents use of the parsers on Perlmutter.

Are you using shifter? I suspect not.

We don't really have a solution for this except what @moellep suggested. We do not install all dependencies for Sirepo via setup.py (or requirements.txt). Most users use docker or set sim_types when they have a local install.

There have been discussions of having, say, sirepo-elegant, sirepo-madx, etc. These could have specific dependencies, but would put a load on users not using docker.
