### ISSUE TITLE
SRW - 502 Bad Gateway error

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#665]
I observed the following error while trying to change the parameters of the Source Intensity report and the undulator of the ESM beamline example (tabulated undulator):
```python
Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1994, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/py2/lib/python2.7/site-packages/beaker/middleware.py", line 156, in __call__
    return self.wrap_app(environ, session_start_response)
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/py2/lib/python2.7/site-packages/sirepo-20170205.155930-py2.7.egg/sirepo/server.py", line 711, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/py2/lib/python2.7/site-packages/sirepo-20170205.155930-py2.7.egg/sirepo/uri_router.py", line 168, in _dispatch
    return route.func(**kwargs)
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/py2/lib/python2.7/site-packages/sirepo-20170205.155930-py2.7.egg/sirepo/server.py", line 437, in api_runSimulation
    _start_simulation(data)
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/py2/lib/python2.7/site-packages/sirepo-20170205.155930-py2.7.egg/sirepo/server.py", line 956, in _start_simulation
    cfg.job_queue(data)
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/py2/lib/python2.7/site-packages/sirepo-20170205.155930-py2.7.egg/sirepo/runner.py", line 196, in __init__
    self.async_result,
AttributeError: 'Celery' object has no attribute 'async_result'
```

This causes the simulation to fail and the `502 Bad Gateway` error appears.

Attaching the exported zip-archive for more details - 
[NSLS-II ESM beamline (tabulated undulator).zip](https://github.com/radiasoft/sirepo/files/759295/NSLS-II.ESM.beamline.tabulated.undulator.zip).

**Comment by robnagler** [comment]
would be good to have the celery and sirepo log output

**Comment by mrakitin** [comment]
Attached - [esm_logs.zip](https://github.com/radiasoft/sirepo/files/759351/esm_logs.zip)

**Comment by moellep** [comment]
I saw the say "async_result" error just now on alpha. (sirepo/init.log at
2/9/17 21:56:46). I didn't see anything unusual in the celery init.log.

**Comment by robnagler** [comment]
I'll take a look

**Comment by robnagler** [comment]
Can we "double click"? 

```
[09/Feb/2017:21:56:46 +0000] "POST /run-simulation HTTP/1.1" 200 988768 
[09/Feb/2017:21:56:47 +0000] "POST /run-simulation HTTP/1.1" 500 0
```

It's definitely a locking bug, and there is [a related todo](https://github.com/radiasoft/sirepo/blob/bcff467654279901b41d5cc7d829d6fe17e8300b/sirepo/server.py#L867):

```python
    try:
        #TODO(robnagler): Lock
        rep = simulation_db.report_info(data)
```

However, there is [a lock with a sanity check](https://github.com/radiasoft/sirepo/blob/bcff467654279901b41d5cc7d829d6fe17e8300b/sirepo/runner.py#L189) on the runner:

```
        with self._lock:
            self.jid = simulation_db.job_id(data)
            pkdc('{}: created', self.jid)
            if self.jid in self._job:
                pkdlog(
                    '{}: Collision tid={} celery_state={}',
                    self.jid,
                    self.async_result,
                    self.async_result and self.async_result.state,
                )
                raise Collision(self.jid)
```

However, the reference is incorrect. `self` should be `self = self._job[self.jid]`. Dumb code. I'll fix.
