### ISSUE TITLE
invalid data is not caught in parsing url

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#6665]
https://github.com/moellep/ml/raw/master/CIFAR-4.h5

```txt
../sirepo/uri_router.py:270:parse_msg start ws_id=2 req_seq=19 uri=/save-simulation
../sirepo/uri_router.py:435:_call_api api=saveSimulationData exception=Out of range float values are not JSON compliant: nan stack=Traceback (most recent call last):
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/uri_router.py", line 426, in _call_api
    await getattr(qcall, qcall.uri_route.func_name)(**kwargs)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/server.py", line 463, in api_saveSimulationData
    simulation_db.save_simulation_json(
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/simulation_db.py", line 668, in save_simulation_json
    write_json(fn, d)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/simulation_db.py", line 862, in write_json
    util.json_dump(data, path=json_filename(filename), pretty=True)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/util.py", line 354, in json_dump
    res = pykern.pkjson.dump_pretty(obj, pretty=pretty, allow_nan=False, **kwargs)
  File "/home/vagrant/src/radiasoft/pykern/pykern/pkjson.py", line 56, in dump_pretty
    json.dumps(
  File "/home/vagrant/.pyenv/versions/3.9.15/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/home/vagrant/.pyenv/versions/3.9.15/lib/python3.9/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/home/vagrant/.pyenv/versions/3.9.15/lib/python3.9/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/home/vagrant/.pyenv/versions/3.9.15/lib/python3.9/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/home/vagrant/.pyenv/versions/3.9.15/lib/python3.9/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/home/vagrant/.pyenv/versions/3.9.15/lib/python3.9/json/encoder.py", line 397, in _iterencode_dict
    yield _floatstr(value)
  File "/home/vagrant/.pyenv/versions/3.9.15/lib/python3.9/json/encoder.py", line 239, in floatstr
    raise ValueError(
ValueError: Out of range float values are not JSON compliant: nan
```

**Comment by mkeilman** [comment]
This particular case seems unrelated to the data itself, but rather due to some integer fields in the schema having no default values:
```
"partition": {
...
    "cutoff0": ["Cutoff 0", "Integer"],
    "cutoff1": ["Cutoff 1", "Integer"],
...
},
```
which you can see in sirepo-data by allowing NaN in the json dump:
```
"partition": {
    "cutoff0": NaN,
    "cutoff1": NaN,
...
},
```
We should fix the schema and fix the schema validation - we currently ignore empty default values. Whether this issue is thus obviated I don't know
