### ISSUE TITLE
SRW - problem with self-extracting file

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#668]
I was trying to port a simulation from one server to another, but met the following error in the server log:
```py
../sirepo/uri_router.py:174:_dispatch import-archive: error: AssertionError: R5.tif duplicate file in archive
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/threading.py", line 783, in __bootstrap
    self.__bootstrap_inner()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/werkzeug/serving.py", line 216, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/werkzeug/serving.py", line 251, in handle_one_request
    return self.run_wsgi()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/werkzeug/serving.py", line 193, in run_wsgi
    execute(self.server.app)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/werkzeug/serving.py", line 181, in execute
    application_iter = app(environ, start_response)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/beaker/middleware.py", line 155, in __call__
    return self.wrap_app(environ, session_start_response)
  File "/vagrant/sirepo/sirepo/server.py", line 711, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/vagrant/sirepo/sirepo/uri_router.py", line 168, in _dispatch
    return route.func(**kwargs)
  File "/vagrant/sirepo/sirepo/server.py", line 279, in api_importArchive
    data = sirepo.importer.do_form(flask.request.form)
  File "/vagrant/sirepo/sirepo/importer.py", line 27, in do_form
    data = read_zip(StringIO.StringIO(base64.decodestring(form['zip'])))
  File "/vagrant/sirepo/sirepo/importer.py", line 86, in read_zip
    '{} duplicate file in archive'.format(i.filename)
Exception in thread Thread-142:
Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/SocketServer.py", line 602, in process_request_thread
    self.handle_error(request, client_address)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/werkzeug/serving.py", line 216, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/werkzeug/serving.py", line 251, in handle_one_request
    return self.run_wsgi()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/werkzeug/serving.py", line 193, in run_wsgi
    execute(self.server.app)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/werkzeug/serving.py", line 181, in execute
    application_iter = app(environ, start_response)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/beaker/middleware.py", line 155, in __call__
    return self.wrap_app(environ, session_start_response)
  File "/vagrant/sirepo/sirepo/server.py", line 711, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/vagrant/sirepo/sirepo/uri_router.py", line 168, in _dispatch
    return route.func(**kwargs)
  File "/vagrant/sirepo/sirepo/server.py", line 279, in api_importArchive
    data = sirepo.importer.do_form(flask.request.form)
  File "/vagrant/sirepo/sirepo/importer.py", line 27, in do_form
    data = read_zip(StringIO.StringIO(base64.decodestring(form['zip'])))
  File "/vagrant/sirepo/sirepo/importer.py", line 86, in read_zip
    '{} duplicate file in archive'.format(i.filename)
AssertionError: R5.tif duplicate file in archive
```

**Comment by mrakitin** [comment]
The same issue when I try to import a previously exported zip-file:
```py
../sirepo/server.py:319:api_importFile NSLS-II CHX with Julien's sample (thick sample, rings).zip: exception: AssertionError: R5.tif duplicate file in archive
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/threading.py", line 783, in __bootstrap
    self.__bootstrap_inner()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/werkzeug/serving.py", line 216, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/werkzeug/serving.py", line 251, in handle_one_request
    return self.run_wsgi()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/werkzeug/serving.py", line 193, in run_wsgi
    execute(self.server.app)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/werkzeug/serving.py", line 181, in execute
    application_iter = app(environ, start_response)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/beaker/middleware.py", line 155, in __call__
    return self.wrap_app(environ, session_start_response)
  File "/vagrant/sirepo/sirepo/server.py", line 711, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/vagrant/sirepo/sirepo/uri_router.py", line 168, in _dispatch
    return route.func(**kwargs)
  File "/vagrant/sirepo/sirepo/server.py", line 307, in api_importFile
    data = sirepo.importer.read_zip(f.stream, template)
  File "/vagrant/sirepo/sirepo/importer.py", line 86, in read_zip
    '{} duplicate file in archive'.format(i.filename)
```

**Comment by mrakitin** [comment]
I think that's a wrong export procedure causing several files with the same name to appear in the exported archive:
![bad_export](https://cloud.githubusercontent.com/assets/13209176/22725358/ec17316e-ed9a-11e6-8f9b-7c81cb968a53.png)

That's for the thick sample, where several sample elements with the same image file are used. The archive is attached - [several_samples.zip](https://github.com/radiasoft/sirepo/files/759833/several_samples.zip).

**Comment by robnagler** [comment]
Good thing there was an assertion. :)

I'll check it out.
