### ISSUE TITLE
'sirepo service rabbitmq' does not work

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#698]
I tried to start rabbitmq with the short command `sirepo service rabbitmq` on my dev machine, but it failed with the error:
```
17:02 $ sirepo service rabbitmq
2017-03-15 17:05:45 Cookie file /var/lib/rabbitmq/.erlang.cookie must be accessible by owner only
2017-03-15 17:05:45 crash_report
    initial_call: {auth,init,['Argument__1']}
    pid:     registered_name:     error_info: <0.46.0>
[]
{exit,{"Cookie file /var/lib/rabbitmq/.erlang.cookie must be accessible by owner only",[{auth,init_cookie,0,[{file,"auth.erl"},{line,286}]},{auth,init,1,[{file,"auth.erl"},
{line,140}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]},[{gen_server,init_it,6,[{file,"ge
n_server.erl"},{line,352}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
[net_sup,kernel_sup,<0.34.0>]
[]
[<0.44.0>]
[]
true
running
610
27
446
{local    ancestors:     messages:     links:     dictionary:     trap_exit:     status:     heap_size:     stack_size:     reductions: 2017-03-15 17:05:45 supervisor_repor
t
    supervisor:     errorContext:     reason: ,net_sup}
start_error
{"Cookie file /var/lib/rabbitmq/.erlang.cookie must be accessible by owner only",[{auth,init_cookie,0,[{file,"auth.erl"},{line,286}]},{auth,init,1,[{file,"auth.erl"},{line,
140}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
 [{pid,undefined},{id,auth},{mfargs,{auth,start_link,[]}},{restart_type,permanent},{shutdown,2000},{child_type,worker}]
   offender: 2017-03-15 17:05:45 supervisor_report
    supervisor: {local,kernel_sup}
    errorContext:     reason: start_error
{shutdown,{failed_to_start_child,auth,{"Cookie file /var/lib/rabbitmq/.erlang.cookie must be accessible by owner only",[{auth,init_cookie,0,[{file,"auth.erl"},{line,286}]},
{auth,init,1,[{file,"auth.erl"},{line,140}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}}
[{pid,undefined},{id,net_sup},{mfargs,{erl_distribution,start_link,[]}},{restart_type,p    offender: 2ermanent},{shutdown,infinity},{child_type,supervisor}]
{application_master,init,['Argument__1','Argument__2','Argument__3','Argument__4']}
<0.33.0>
017-03-15 17:05:45 crash_report
    initial_call:     pid:   [  registered_name: ]
 {  error_info: exit,{{shutdown,{failed_to_start_child,net_sup,{shutdown,{failed_to_start_child,auth,{"Cookie file /var/lib/rabbitmq/.erlang.cookie must be accessible by ow
ner only",[{auth,init_cookie,0,[{file,"auth.erl"},{line,286}]},{auth,init,1,[{file,"auth.erl"},{line,140}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{pro
c_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}}}},{kernel,start,[normal,[]]}},[{application_master,init,4,[{file,"application_master.erl"},{line,134}]},{pro
c_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
    ancestors:    [<0.32.0>]
 messages: [{'EXIT',<0.34.0>,normal}]
    links: [<0.32.0>,<0.31.0>]
   dictionary:     trap_exit:     status:     h[]
true
running
987
27
227
kernel
{{shutdown,{failed_to_start_child,net_sup,{shutdown,{failed_to_start_child,auth,{"Cookie file /var/lib/rabbitmq/.erlang.cookie must be accessible by owner only",[{auth,init
_cookie,0,[{file,"auth.erl"},{line,286}]},{auth,init,1,[{file,"auth.erl"},{line,140}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply
,3,[{file,"proc_lib.erl"},{line,247}]}]}}}}},{kernel,start,[normal,[]]}}
permanent
eap_size:     stack_size:     reductions: 2017-03-15 17:05:45 std_info
    application:     exited:     type: {"Kernel pid terminated",application_controller,"{application_start_failure,kernel,{{shutdown,{failed_to_start_child,net_sup,{shutdow
n,{failed_to_start_child,auth,{\"Cookie file /var/lib/rabbitmq/.erlang.cookie must be accessible by owner only\",[{auth,init_cookie,0,[{file,\"auth.erl\"},{line,286}]},{aut
h,init,1,[{file,\"auth.erl\"},{line,140}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,247}]}]}
}}}},{kernel,start,[normal,[]]}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,kernel,{{shutdown,{failed_to_start_child,net_sup,{shutdown,{failed_to_start_child,auth,{"Cookie f
ile /var/lib/rabbitmq/.erlan

Crash dump is being written to: erl_crash.dump...Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/2.7.10/bin/sirepo", line 9, in <module>
    load_entry_point('sirepo', 'console_scripts', 'sirepo')()
  File "/vagrant/sirepo/sirepo/sirepo_console.py", line 18, in main
    return pkcli.main('sirepo')
  File "/home/vagrant/src/radiasoft/pykern/pykern/pkcli/__init__.py", line 98, in main
    argh.dispatch(parser, argv=argv)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "/vagrant/sirepo/sirepo/pkcli/service.py", line 113, in rabbitmq
    pksubprocess.check_call_with_signals(cmd)
  File "/home/vagrant/src/radiasoft/pykern/pykern/pksubprocess.py", line 67, in check_call_with_signals
    raise RuntimeError('error exit({})'.format(rc))
RuntimeError: error exit(1)
```

Any known workarounds?

**Comment by mrakitin** [comment]
The problem is observed on the vboxsf filesystem (a shared folder with Windows host).

**Comment by robnagler** [comment]
what directory are you running it in? There might be something funny with run_dir.

**Comment by mrakitin** [comment]
It's in `/vagrant/sirepo/run/`, which is a shared folder provided by VirtualBox. The permissions are 444 for the cookie file and cannot be changed to 600 on the filesystem. Maybe that's the reason.

**Comment by robnagler** [comment]
Why not run in /home/vagrant?

**Comment by mrakitin** [comment]
It's for sharing & web development purposes, so that the code is available in a browser on a host. I don't think if I mount it to /home/vagrant something will change.

**Comment by robnagler** [comment]
Maybe you can run it inside Docker directly? There's something wrong with the vboxsf config. Maybe this: http://serverfault.com/questions/337809/virtualbox-vboxsf-filesystem-wrongly-detected-as-readonly

**Comment by mrakitin** [comment]
It's `rw` since I can write to the filesystem. I'll check if it can run with the local filesystem.

**Comment by robnagler** [comment]
Obsolete
