### ISSUE TITLE
SRW - GitHub login is not possible for a user with copied simulation

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#793]
It looks like it's not possible to login using GitHub login when a simulation was copied in 2 browser under anonymous user, and then it was an attempt to log in in the two browser. The second one causes the following error:
```py
10.0.2.2 - - [21/Jun/2017 18:08:28] "GET /login/srw/github?next=/simulations HTTP/1.1" 302 -
../sirepo/simulation_db.py:360:move_user_simulations /vagrant/sirepo/run/user/f8hI2bco/srw/8v3Piuoo -> /vagrant/sirepo/run/user/yZDbXOvm/srw/8v3Piuoo
../sirepo/uri_router.py:174:_dispatch oauth-authorized/github: error: OSError: [Errno 17] File exists
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/threading.py", line 783, in __bootstrap
    self.__bootstrap_inner()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/werkzeug/serving.py", line 216, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/werkzeug/serving.py", line 251, in handle_one_request
    return self.run_wsgi()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/werkzeug/serving.py", line 193, in run_wsgi
    execute(self.server.app)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/werkzeug/serving.py", line 181, in execute
    application_iter = app(environ, start_response)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/beaker/middleware.py", line 155, in __call__
    return self.wrap_app(environ, session_start_response)
  File "/vagrant/sirepo/sirepo/server.py", line 743, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/vagrant/sirepo/sirepo/uri_router.py", line 168, in _dispatch
    return route.func(**kwargs)
  File "/vagrant/sirepo/sirepo/server.py", line 357, in api_oauthAuthorized
    return oauth.authorized_callback(app, oauth_type)
  File "/vagrant/sirepo/sirepo/oauth.py", line 83, in authorized_callback
    user = _update_database(user_data, oauth_type)
  File "/vagrant/sirepo/sirepo/oauth.py", line 162, in _update_database
    simulation_db.move_user_simulations(user.uid)
  File "/vagrant/sirepo/sirepo/simulation_db.py", line 362, in move_user_simulations
    os.rename(dir_path, new_dir_path)
Exception in thread Thread-632:
Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/SocketServer.py", line 602, in process_request_thread
    self.handle_error(request, client_address)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/werkzeug/serving.py", line 216, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/werkzeug/serving.py", line 251, in handle_one_request
    return self.run_wsgi()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/werkzeug/serving.py", line 193, in run_wsgi
    execute(self.server.app)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/werkzeug/serving.py", line 181, in execute
    application_iter = app(environ, start_response)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/beaker/middleware.py", line 155, in __call__
    return self.wrap_app(environ, session_start_response)
  File "/vagrant/sirepo/sirepo/server.py", line 743, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/vagrant/sirepo/sirepo/uri_router.py", line 168, in _dispatch
    return route.func(**kwargs)
  File "/vagrant/sirepo/sirepo/server.py", line 357, in api_oauthAuthorized
    return oauth.authorized_callback(app, oauth_type)
  File "/vagrant/sirepo/sirepo/oauth.py", line 83, in authorized_callback
    user = _update_database(user_data, oauth_type)
  File "/vagrant/sirepo/sirepo/oauth.py", line 162, in _update_database
    simulation_db.move_user_simulations(user.uid)
  File "/vagrant/sirepo/sirepo/simulation_db.py", line 362, in move_user_simulations
    os.rename(dir_path, new_dir_path)
OSError: [Errno 17] File exists
``
GUI is not responding, but at least should throw and error message.

**Comment by robnagler** [comment]
Not clear about the steps. Is this what happened?

1. User copies simulation, e.g. in Chrome
2. User copies simulation, e.g. in Firefox
3. User logs in with GitHub in Chrome
4. User logs in with GitHub in Firefox and gets error

**Comment by mrakitin** [comment]
Yes, Rob, that's exactly what I did.

**Comment by robnagler** [comment]
OK. I'll add it to my queue. Working on Shadow CRL now.

**Comment by mrakitin** [comment]
Great, thanks! It's not the highest priority though, Shadow CRL is way more important :-).

**Comment by robnagler** [comment]
I'm not seeing this behavior. I am seeing that the simulations get merged and there are two simulations with the same name, which is a known issue, #58:

![screen shot 2017-07-03 at 4 20 11 pm](https://user-images.githubusercontent.com/5495179/27809286-830cede2-600b-11e7-948d-bff19bce073e.png)
