### ISSUE TITLE
pytest does not work on my dev VM

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/sirepo#929]
```python
12:15 $ bash test.sh
running test
running egg_info
writing requirements to sirepo.egg-info/requires.txt
writing sirepo.egg-info/PKG-INFO
writing top-level names to sirepo.egg-info/top_level.txt
writing dependency_links to sirepo.egg-info/dependency_links.txt
writing entry points to sirepo.egg-info/entry_points.txt
reading manifest file 'sirepo.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'sirepo.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 34, in <module>
    'Topic :: Software Development :: Libraries :: Application Frameworks',
  File "/home/vagrant/src/radiasoft/pykern/pykern/pksetup.py", line 372, in setup
    op(**base)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/setuptools/command/test.py", line 211, in run
    self.run_tests()
  File "/home/vagrant/src/radiasoft/pykern/pykern/pksetup.py", line 228, in run_tests
    sys.exit(pytest.main([TESTS_DIR]))
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/config.py", line 47, in main
    config = _prepareconfig(args, plugins)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/config.py", line 156, in _prepareconfig
    pluginmanager=pluginmanager, args=args)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 613, in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 250, in _wrapped_call
    wrap_controller.send(call_outcome)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/helpconfig.py", line 32, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 280, in get_result
    _reraise(*ex)  # noqa
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 265, in __init__
    self.result = func()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
    res = hook_impl.function(*args)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/config.py", line 923, in pytest_cmdline_parse
    self.parse(args)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/config.py", line 1080, in parse
    self._preparse(args, addopts=addopts)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/config.py", line 1051, in _preparse
    args=args, parser=self._parser)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 613, in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 254, in _wrapped_call
    return call_outcome.get_result()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 280, in get_result
    _reraise(*ex)  # noqa
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 265, in __init__
    self.result = func()
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
    res = hook_impl.function(*args)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/config.py", line 969, in pytest_load_initial_conftests
    self.pluginmanager._set_initial_conftests(early_config.known_args_namespace)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/config.py", line 308, in _set_initial_conftests
    self._try_load_conftest(anchor)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/config.py", line 314, in _try_load_conftest
    self._getconftestmodules(anchor)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/config.py", line 339, in _getconftestmodules
    mod = self._importconftest(conftestpath)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/config.py", line 375, in _importconftest
    self.consider_conftest(mod)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/config.py", line 399, in consider_conftest
    self.consider_module(conftestmodule)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/config.py", line 405, in consider_module
    self._import_plugin_specs(getattr(mod, 'pytest_plugins', []))
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/config.py", line 410, in _import_plugin_specs
    self.import_plugin(import_spec)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/config.py", line 441, in import_plugin
    self.register(mod, modname)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/config.py", line 250, in register
    ret = super(PytestPluginManager, self).register(plugin, name)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 351, in register
    (plugin_name, plugin, self._name2plugin))
ValueError: Plugin already registered: pykern.pytest_plugin=<module 'pykern.pytest_plugin' from '/home/vagrant/src/radiasoft/pykern/pykern/pytest_plugin.py'>
{'cacheprovider': <module '_pytest.cacheprovider' from '/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/cacheprovider.pyc'>, 'debugging': <module '_pytest.debugging' from '/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/debugging.pyc'>, 'pytestconfig': <_pytest.config.Config object at 0x7fe9193f6bd0>, 'helpconfig': <module '_pytest.helpconfig' from '/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/helpconfig.pyc'>, 'runner': <module '_pytest.runner' from '/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/runner.pyc'>, 'unittest': <module '_pytest.unittest' from '/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/unittest.pyc'>, 'xdist.looponfail': <module 'xdist.looponfail' from '/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/xdist/looponfail.py'>, 'xdist': <module 'xdist.plugin' from '/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/xdist/plugin.py'>, 'pykern': <module 'pykern.pytest_plugin' from '/home/vagrant/src/radiasoft/pykern/pykern/pytest_plugin.py'>, 'pastebin': <module '_pytest.pastebin' from '/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/pastebin.pyc'>, 'skipping': <module '_pytest.skipping' from '/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/skipping.pyc'>, 'fixtures': <module '_pytest.fixtures' from '/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/fixtures.pyc'>, 'tmpdir': <module '_pytest.tmpdir' from '/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/tmpdir.pyc'>, 'capture': <module '_pytest.capture' from '/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/capture.pyc'>, 'assertion': <module '_pytest.assertion' from '/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/assertion/__init__.pyc'>, 'mark': <module '_pytest.mark' from '/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/mark.pyc'>, 'terminal': <module '_pytest.terminal' from '/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/terminal.pyc'>, 'main': <module '_pytest.main' from '/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/main.pyc'>, '/home/vagrant/src/radiasoft/sirepo/tests/conftest.py': <module 'conftest' from '/home/vagrant/src/radiasoft/sirepo/tests/conftest.py'>, 'nose': <module '_pytest.nose' from '/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/nose.pyc'>, 'xdist.boxed': <module 'xdist.boxed' from '/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/xdist/boxed.py'>, 'python': <module '_pytest.python' from '/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/python.pyc'>, '140639134530576': <_pytest.config.PytestPluginManager object at 0x7fe919a7bc10>, 'recwarn': <module '_pytest.recwarn' from '/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/recwarn.pyc'>, 'monkeypatch': <module '_pytest.monkeypatch' from '/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/monkeypatch.pyc'>, 'resultlog': <module '_pytest.resultlog' from '/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/resultlog.pyc'>, 'setuponly': <module '_pytest.setuponly' from '/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/setuponly.pyc'>, 'capturemanager': <_pytest.capture.CaptureManager instance at 0x7fe918b4f680>, 'pytest_cov': <module 'pytest_cov.plugin' from '/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/pytest_cov/plugin.py'>, 'junitxml': <module '_pytest.junitxml' from '/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/junitxml.pyc'>, 'doctest': <module '_pytest.doctest' from '/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/doctest.pyc'>, 'setupplan': <module '_pytest.setupplan' from '/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/setupplan.pyc'>, 'freeze_support': <module '_pytest.freeze_support' from '/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_pytest/freeze_support.pyc'>}
```

**Comment by robnagler** [comment]
Try reinstalling pykern.

**Comment by mrakitin** [comment]
Thanks Rob. That helped.
